# translation of po_update-manager-ar.po to Arabic
# Arabic translation for update-manager
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the update-manager package.
#
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
# OsamaKhalid <osamak.wfm@gmail.com>, 2009.
msgid ""
msgstr ""
"Project-Id-Version: po_update-manager-ar\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2012-06-14 00:53+0100\n"
"PO-Revision-Date: 2012-04-17 08:34+0000\n"
"Last-Translator: Ibrahim Saed <ibraheem5000@gmail.com>\n"
"Language-Team: Arabic\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n % 100 >= "
"3 && n % 100 <= 10 ? 3 : n % 100 >= 11 && n % 100 <= 99 ? 4 : 5;\n"
"X-Launchpad-Export-Date: 2012-04-17 13:41+0000\n"
"X-Generator: Launchpad (build 15099)\n"

#. TRANSLATORS: download size of small updates, e.g. "250 kB"
#: ../DistUpgrade/utils.py:433 ../UpdateManager/Core/utils.py:433
#, python-format
msgid "%(size).0f kB"
msgid_plural "%(size).0f kB"
msgstr[0] "%(size).0f ك.بايت"
msgstr[1] "%(size).0f ك.بايت"
msgstr[2] "%(size).0f ك.بايت"
msgstr[3] "%(size).0f ك.بايت"
msgstr[4] "%(size).0f ك.بايت"
msgstr[5] "%(size).0f ك.بايت"

#. TRANSLATORS: download size of updates, e.g. "2.3 MB"
#: ../DistUpgrade/utils.py:436 ../UpdateManager/Core/utils.py:436
#, python-format
msgid "%.1f MB"
msgstr "%.1f م.بايت"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:206 ../DistUpgrade/distro.py:436
#, python-format
msgid "Server for %s"
msgstr "خادوم %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:224 ../DistUpgrade/distro.py:230
#: ../DistUpgrade/distro.py:246
msgid "Main server"
msgstr "الخادوم الرئيسي"

#: ../DistUpgrade/distro.py:250
msgid "Custom servers"
msgstr "خواديم مخصصة"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:142
msgid "Could not calculate sources.list entry"
msgstr "تعذر حساب مدخلة source.list"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:251
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr "تعذّر إيجاد أي ملفات حزم، لعل هذا ليس قرص أوبونتو أو البنية الخطأ؟"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:294
msgid "Failed to add the CD"
msgstr "فشلت إضافة الاسطوانة"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:295
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"حدث خطأ بإضافة القرص، ستلغى عملية الترقية. من فضلك قم بالإبلاغ عن هذا كعلّة "
"إذا كانت هذه إسطوانة صالحة لأوبونتو.\n"
"\n"
"رسالة الخطأ كانت:\n"
"'%s'"

#: ../DistUpgrade/DistUpgradeCache.py:151
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "أزل الحزمة التي في حالة سيئة"
msgstr[1] "أزل الحزمة التي في حالة سيئة"
msgstr[2] "أزل الحزمتين اللتين في حالة سيئة"
msgstr[3] "أزل الحزم التي في حالة سيئة"
msgstr[4] "أزل الحزم التي في حالة سيئة"
msgstr[5] "أزل الحزم التي في حالة سيئة"

#: ../DistUpgrade/DistUpgradeCache.py:154
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"حالة الحزمة '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. أتريد "
"إزالة هذه الحزمة الآن للمتابعة؟"
msgstr[1] ""
"حالة الحزمة '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. أتريد "
"إزالة هذه الحزمة الآن للمتابعة؟"
msgstr[2] ""
"حالة الحزمتين '%s' متضاربة وتحتاجان أن يعاد تثبيتهما، لكن لا أرشيف وجد لهما. "
"أتريد إزالة هذين الحزمتين الآن للمتابعة؟"
msgstr[3] ""
"حالة الحزم '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. أتريد "
"إزالة هذه الحزم الآن للمتابعة؟"
msgstr[4] ""
"حالة الحزم '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. أتريد "
"إزالة هذه الحزم الآن للمتابعة؟"
msgstr[5] ""
"حالة الحزم '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. أتريد "
"إزالة هذه الحزم الآن للمتابعة؟"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:255
msgid "The server may be overloaded"
msgstr "قد يكون الخادوم مثقلاً."

#: ../DistUpgrade/DistUpgradeCache.py:368
msgid "Broken packages"
msgstr "حزم معطوبة"

#: ../DistUpgrade/DistUpgradeCache.py:369
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"نظامك يحوي حزما مكسورة لا يمكن إصلاحها بهذه البرمجية. أصلحها مستخدما سينابتك "
"أو apt-get قبل المواصلة."

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:693
#, python-format
msgid ""
"An unresolvable problem occurred while calculating the upgrade:\n"
"%s\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""
"صودفت مشكلة غير قابلة للحل أثناء إحصاء الترقية:\n"
"%s\n"
"\n"
" قد يكون هذا ناتج عن:\n"
" * الترقية إلى نسخة ما قبل الإصدار من أبونتو\n"
" * تشغيل نسخة ما قبل الإصدار الحالية من أبونتو\n"
" * حزم برمجيات غير رسمية ليست مقدمة من أبونتو\n"
"\n"

#: ../DistUpgrade/DistUpgradeCache.py:703
msgid "This is most likely a transient problem, please try again later."
msgstr "هذا على الأغلب عطل عابر، من فضلك حاول لاحقا."

#: ../DistUpgrade/DistUpgradeCache.py:706
msgid ""
"If none of this applies, then please report this bug using the command "
"'ubuntu-bug update-manager' in a terminal."
msgstr ""
"إذا لم ينطبق أيًا من هذا، رجاءً أبلغ عن هذه العلة باستخدام الأمر 'ubuntu-bug "
"update-manager' في الطرفية."

#: ../DistUpgrade/DistUpgradeCache.py:711
#: ../UpdateManager/UpdateManager.py:1031
msgid "Could not calculate the upgrade"
msgstr "تعذّر حساب الترقية"

#: ../DistUpgrade/DistUpgradeCache.py:762
msgid "Error authenticating some packages"
msgstr "عطل في استيثاق بعض الحزم"

#: ../DistUpgrade/DistUpgradeCache.py:763
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"تعذّر استيثاق بعض الحزم. قد تكون هذه مشكلة عابرة في الشبكة، وقد تفلح المحاولة "
"مجددا لاحقا. طالع قائمة الحزم غير المستوثقة أدناه."

#: ../DistUpgrade/DistUpgradeCache.py:783
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr "الحزمة '%s' معلّمة للإزالة لكنها في قائمة الحذف السوداء."

#: ../DistUpgrade/DistUpgradeCache.py:787
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "الحزمة الأساسية '%s' معلّمة للإزالة."

#: ../DistUpgrade/DistUpgradeCache.py:796
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr "يحاول تثبيت نسخة في القائمة السوداء '%s'"

#: ../DistUpgrade/DistUpgradeCache.py:914
#, python-format
msgid "Can't install '%s'"
msgstr "تعذّر تثبيت '%s'"

#: ../DistUpgrade/DistUpgradeCache.py:915
msgid ""
"It was impossible to install a required package. Please report this as a bug "
"using 'ubuntu-bug update-manager' in a terminal."
msgstr ""
"لقد كان من المستحيل تثبيت الحزمة المطلوبة. رجاءً أبلغ عن هذا كعلّة باستخدام "
"الأمر 'ubuntu-bug update-manager' في الطرفية."

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:926
msgid "Can't guess meta-package"
msgstr "تعذّرت معرفة الحزمة الفوقية"

#: ../DistUpgrade/DistUpgradeCache.py:927
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"نظامك لا يحتوي أيا من الحزم ubuntu-desktop أو kubuntu-desktop أو xubuntu-"
"desktop أو edubuntu-desktop و لم يمكن الكشف عن نسخة أوبونتو التي تستعملها.\n"
" رجاءً ثبت إحدى الحزم المذكورة أعلاه باستخدام synaptic أو apt-get قبل "
"المواصلة."

#: ../DistUpgrade/DistUpgradeController.py:114
msgid "Reading cache"
msgstr "يقرأ المخبئية"

#: ../DistUpgrade/DistUpgradeController.py:223
msgid "Unable to get exclusive lock"
msgstr "تعذر الحصول على قفل حصري"

#: ../DistUpgrade/DistUpgradeController.py:224
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"يعني هذا عادة أن تطبيق إدارة حزم آخر (مثل apt-get أو aptitude) يعمل حالياً. "
"رجاء أغلق ذاك التطبيق أولاً."

#: ../DistUpgrade/DistUpgradeController.py:257
msgid "Upgrading over remote connection not supported"
msgstr "الترقية عبر اتصال بعيد غير مدعومة"

#: ../DistUpgrade/DistUpgradeController.py:258
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"لقد قمت بتشغيل الترقية عبر اتصال الغطاء الأمني عن بعد مع واجهة لا تدعم هذا. "
"الرجاء محاولة ترقية في وضع النص مع'do-release-upgrade'.\n"
"\n"
"سيتم الخروج من عملية الترقية الآن. الرجاء المحاولة بدون الغطاء الأمني."

#: ../DistUpgrade/DistUpgradeController.py:272
msgid "Continue running under SSH?"
msgstr "أتريد مواصلة العمل تحت SSH؟"

#: ../DistUpgrade/DistUpgradeController.py:273
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"يبدو أن هذه الجلسة تعمل خلال الغطاء الأمني. لا يوصَى بإجراء الترقية عبر "
"الغطاء الأمني حاليا لأنه في حال الفشل سيكون استرداده أصعب.\n"
"إذا استمررت، سيتم بدأ عفريت غطاء أمني إضافي على منفذ '%s'.\n"
"هل تريد الاستمرار؟"

#: ../DistUpgrade/DistUpgradeController.py:287
msgid "Starting additional sshd"
msgstr "يشغّل sshd إضافي"

#: ../DistUpgrade/DistUpgradeController.py:288
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"لتسهيل الإصلاح في حالة الفشل فإن sshd إضافيا سيُشغّل على المنفذ '%s'. إذا حدث "
"عطل في ssh المشتغل حاليا يمكنك الاتصال بالإضافي.\n"

#: ../DistUpgrade/DistUpgradeController.py:296
#, python-format
msgid ""
"If you run a firewall, you may need to temporarily open this port. As this "
"is potentially dangerous it's not done automatically. You can open the port "
"with e.g.:\n"
"'%s'"
msgstr ""
"إذا كان الجدار الناري يعمل، فربما تحتاج إلى فتح هذا المنفذ مؤقتاً. وحيث من "
"المحتمل أن يكون هذا خطراً لا يتم فتحه تقائياً. بإمكانك فتح المنفذ عن طريق:\n"
"'%s'"

#: ../DistUpgrade/DistUpgradeController.py:368
#: ../DistUpgrade/DistUpgradeController.py:413
msgid "Can not upgrade"
msgstr "تعذّرت الترقية"

#: ../DistUpgrade/DistUpgradeController.py:369
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr "ترقية من '%s' إلى '%s' غير مدعومة بهذه الأداة."

#: ../DistUpgrade/DistUpgradeController.py:378
msgid "Sandbox setup failed"
msgstr "فشل إعداد صندوق الرمل"

#: ../DistUpgrade/DistUpgradeController.py:379
msgid "It was not possible to create the sandbox environment."
msgstr "تعذّر إنشاء بيئة محاطة (صندوق رمل)"

#: ../DistUpgrade/DistUpgradeController.py:385
msgid "Sandbox mode"
msgstr "طور صندوق الرمل"

#: ../DistUpgrade/DistUpgradeController.py:386
#, python-format
msgid ""
"This upgrade is running in sandbox (test) mode. All changes are written to "
"'%s' and will be lost on the next reboot.\n"
"\n"
"*No* changes written to a system directory from now until the next reboot "
"are permanent."
msgstr ""
"هذه الترقية تعمل في نمط المرملة (الاختبار). جميع التغييرات تُكتب إلى '%s' "
"وستُفقد عند إعادة التشغيل التالي.\n"
"\n"
"*لن* تُكتب أي تغييرات إلى مجلد النظام من الآن حتى إعادة التشغيل التالي."

#: ../DistUpgrade/DistUpgradeController.py:414
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""
"تثبيتة python الحالية معطوبة. رجاءً أصلح الرابط الرمزي '/usr/bin/python'."

#: ../DistUpgrade/DistUpgradeController.py:440
msgid "Package 'debsig-verify' is installed"
msgstr "حزمة 'debsig-verify' مثبتة"

#: ../DistUpgrade/DistUpgradeController.py:441
msgid ""
"The upgrade can not continue with that package installed.\n"
"Please remove it with synaptic or 'apt-get remove debsig-verify' first and "
"run the upgrade again."
msgstr ""
"لا يمكن مواصة الترقية و تلك الحزمة مثبّتة.\n"
"أزلها باستخدام synaptic أو 'apt-get' ثم أجر الترقية مجددا."

#: ../DistUpgrade/DistUpgradeController.py:453
#, python-format
msgid "Can not write to '%s'"
msgstr "لا يمكن الكتابة إلى '%s'"

#: ../DistUpgrade/DistUpgradeController.py:454
#, python-format
msgid ""
"Its not possible to write to the system directory '%s' on your system. The "
"upgrade can not continue.\n"
"Please make sure that the system directory is writable."
msgstr ""
"لا يمكن الكتابة إلى مُجلد النظام '%s' على نظامك. لا يُمكن مُتابعة الترقية.\n"
"رجاءً تأكد أن مُجلد النظام قابل للكتابة."

#: ../DistUpgrade/DistUpgradeController.py:465
msgid "Include latest updates from the Internet?"
msgstr "أأضمن آخر التحديثات من الإنترنت؟"

#: ../DistUpgrade/DistUpgradeController.py:466
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""
"نظام الترقية يمكن أن يستخدم الإنرتنت للتنزيل التلقائي لآخر التحديثات ويثبتها "
"أثناء الترقية. إذا كنت تمتلك اتصال شبكة هذا موصى به بشدة.\n"
"\n"
"الترقية سوف تستغرق وقتا أطول، لكن عندما تكتمل، سيكون نظامك محدث تماما. "
"تستطيع اختيار عدم فعل ذلك، لكن يتعيّن عليك تثبيت آخر التحديثات بعد الترقية "
"مباشرة.\n"
"إذا كانت إجابتك 'لا' هنا، لن تستخدم الشبكة مطلقا."

#: ../DistUpgrade/DistUpgradeController.py:686
#, python-format
msgid "disabled on upgrade to %s"
msgstr "عُطّل عند الترقية إلى %s"

#: ../DistUpgrade/DistUpgradeController.py:713
msgid "No valid mirror found"
msgstr "لم يُعثر على مرآة صحيحة"

#: ../DistUpgrade/DistUpgradeController.py:714
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""
"تعذر إيجاد مرآة للترقية أثناء البحث في معلومات المستودعات في حاسوبك. قد يحدث "
"هذا إن استخدمت مرآة داخلية أو إن كانت معلومات المرآة قديمة.\n"
"\n"
"هل تود التعديل على ملف 'sources.list' لديك على أية حال؟ إن أجبت ﺑ'نعم' "
"فستُحدّث كل '%s' إلى '%s'. وإن أجبت ﺑ'ﻻ' فستُلغى عملية الترقية."

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:734
msgid "Generate default sources?"
msgstr "أأولد المصادر المبدئية؟"

#: ../DistUpgrade/DistUpgradeController.py:735
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"تعذر إيجاد مدخلة صالحة لـ'%s' أثناء البحث في ملف 'sources.list' في حاسوبك.\n"
"\n"
"هل تود إضافة المدخلات الافتراضية لـ'%s'؟ إن أجبت ﺑ'ﻻ' فستُلغى عملية الترقية."

#: ../DistUpgrade/DistUpgradeController.py:770
msgid "Repository information invalid"
msgstr "معلومات المستودع غير صحيحة"

#: ../DistUpgrade/DistUpgradeController.py:771
msgid ""
"Upgrading the repository information resulted in a invalid file so a bug "
"reporting process is being started."
msgstr ""
"ترقية معلومات المستودعات أسفرت عن ملف غير صالح، لذلك يجري بدء عملية للإبلاغ "
"عن العلّة."

#: ../DistUpgrade/DistUpgradeController.py:778
msgid "Third party sources disabled"
msgstr "مصادر الأطراف الخارجية عُطّلت"

#: ../DistUpgrade/DistUpgradeController.py:779
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"بعض مدخلات الأطراف الخارجية في sources.list قد عطلت. يمكنك إعادة تفعيلها بعد "
"الترقية، باستخدام أداة 'software-properties' في مدير الحزم."

#: ../DistUpgrade/DistUpgradeController.py:819
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "لا حزم في حالة غير متسقة"
msgstr[1] "حزمة واحدة في حالة غير متسقة"
msgstr[2] "حزمتان في حالة غير متسقة"
msgstr[3] "حزم في حالة غير متسقة"
msgstr[4] "حزم في حالة غير متسقة"
msgstr[5] "حزم في حالة غير متسقة"

#: ../DistUpgrade/DistUpgradeController.py:822
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"حالة الحزمة '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. من "
"فضلك أعد تثبيت الحزمة يدويا أو أزلها من النظام."
msgstr[1] ""
"حالة الحزمة '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. من "
"فضلك أعد تثبيت الحزمة يدويا أو أزلها من النظام."
msgstr[2] ""
"حالة الحزمتين '%s' متضاربة وتحتاجان أن يعاد تثبيتهما، لكن لا أرشيف وجد لهما. "
"من فضلك أعد تثبيت الحزمتين يدويا أو أزلهما من النظام."
msgstr[3] ""
"حالة الحزم '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. من "
"فضلك أعد تثبيت الحزم يدويا أو أزلها من النظام."
msgstr[4] ""
"حالة الحزم '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. من "
"فضلك أعد تثبيت الحزم يدويا أو أزلها من النظام."
msgstr[5] ""
"حالة الحزم '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. من "
"فضلك أعد تثبيت الحزم يدويا أو أزلها من النظام."

#: ../DistUpgrade/DistUpgradeController.py:870
msgid "Error during update"
msgstr "عطل أثناء التحديث"

#: ../DistUpgrade/DistUpgradeController.py:871
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"طرأت مشكلة أثناء التحديث. عادة ما يكون هذا نتيجة مشكلة ما في الشبكة، تحقق من "
"اتصالك الشبكي وحاول مجددا."

#. print("on_button_install_clicked")
#: ../DistUpgrade/DistUpgradeController.py:880
#: ../UpdateManager/UpdateManager.py:757
msgid "Not enough free disk space"
msgstr "لا توجد مساحة كافية على القرص"

#: ../DistUpgrade/DistUpgradeController.py:881
#, python-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of %s free space on disk "
"'%s'. Please free at least an additional %s of disk space on '%s'. Empty "
"your trash and remove temporary packages of former installations using 'sudo "
"apt-get clean'."
msgstr ""
"لقد أُجهضت الترقية. تحتاج الترقية إلى %s مساحة خالية على القرص '%s'. من فضلك "
"أفرغ %s على الأقل من مساحة القرص '%s'. أفرغ المهملات وأزل الحزم المؤقتة من "
"التثبيتات السابقة باستخدام 'sudo apt-get clean'."

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:910
#: ../DistUpgrade/DistUpgradeController.py:1692
msgid "Calculating the changes"
msgstr "يحسب التغيرات"

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:942
msgid "Do you want to start the upgrade?"
msgstr "أتريد بدء التحديث الآن؟"

#: ../DistUpgrade/DistUpgradeController.py:1008
msgid "Upgrade canceled"
msgstr "أُلغيت الترقية"

#: ../DistUpgrade/DistUpgradeController.py:1009
msgid ""
"The upgrade will cancel now and the original system state will be restored. "
"You can resume the upgrade at a later time."
msgstr ""
"الترقية ستلغى وسيتم استعادة الحالة الأصلية للنظام. بإمكانك استئناف الترقية "
"في وقت لاحق."

#: ../DistUpgrade/DistUpgradeController.py:1015
#: ../DistUpgrade/DistUpgradeController.py:1149
msgid "Could not download the upgrades"
msgstr "تعذّر تنزيل الترقيات"

#: ../DistUpgrade/DistUpgradeController.py:1016
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far have been kept."
msgstr ""
"تم إلغاء الترقية . من فضلك إفحص إتصالك بالإنترنت أو قرص التثبيت وحاول مرة "
"أخرى. جميع الملفات المنزلة تم حفظها."

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1100
#: ../DistUpgrade/DistUpgradeController.py:1137
#: ../DistUpgrade/DistUpgradeController.py:1242
msgid "Error during commit"
msgstr "عطل أثناء الإيداع"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1102
#: ../DistUpgrade/DistUpgradeController.py:1139
#: ../DistUpgrade/DistUpgradeController.py:1281
msgid "Restoring original system state"
msgstr "يسترجع الحالة الأصلية للنظام"

#: ../DistUpgrade/DistUpgradeController.py:1103
#: ../DistUpgrade/DistUpgradeController.py:1118
#: ../DistUpgrade/DistUpgradeController.py:1140
msgid "Could not install the upgrades"
msgstr "تعذّر تثبيت الترقيات"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1108
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"لقد أُجهضت الترقية. قد يصبح نظامك في خالة غير مستقرة. سيُشغل الاستعفاء الآن "
"(dpkg --configure -a)."

#: ../DistUpgrade/DistUpgradeController.py:1113
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug in a browser at http://bugs.launchpad.net/ubuntu/"
"+source/update-manager/+filebug and attach the files in /var/log/dist-"
"upgrade/ to the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"رجاءً أبلغ عن هذه العلّة من خلال المُتصفح على http://bugs.launchpad.net/ubuntu/"
"+source/update-manager/+filebug وأرفق الملفات الموجودة في /var/log/dist-"
"upgrade/ مع البلاغ.\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1150
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""
"لقد أُجهضت الترقية. راجع الاتصال بالإنترت أو وسيط التثبيت ثم أعد المحاولة. "

#: ../DistUpgrade/DistUpgradeController.py:1230
msgid "Remove obsolete packages?"
msgstr "أأزيل الحزم المبطلة؟"

#: ../DistUpgrade/DistUpgradeController.py:1231
#: ../DistUpgrade/DistUpgrade.ui.h:8
msgid "_Keep"
msgstr "ا_ستبق"

#: ../DistUpgrade/DistUpgradeController.py:1231
msgid "_Remove"
msgstr "أ_زل"

#: ../DistUpgrade/DistUpgradeController.py:1243
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr "طرأت مشكلة أثناء التنظيف. طالع الرسالة أدناه لمزيد من المعلومات. "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1319
msgid "Required depends is not installed"
msgstr "اعتمادات مطلوبة غير مثبتة"

#: ../DistUpgrade/DistUpgradeController.py:1320
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "الاعتمادية المطلوبة '%s' ليست مثبتة. "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1588
#: ../DistUpgrade/DistUpgradeController.py:1653
msgid "Checking package manager"
msgstr "يفحص مدير الحزم"

#: ../DistUpgrade/DistUpgradeController.py:1593
msgid "Preparing the upgrade failed"
msgstr "فشل تجهيز الترقية"

#: ../DistUpgrade/DistUpgradeController.py:1594
msgid ""
"Preparing the system for the upgrade failed so a bug reporting process is "
"being started."
msgstr "فشل تحضير النظام للترقية، لذلك يجري بدء عملية للإبلاغ عن العلّة."

#: ../DistUpgrade/DistUpgradeController.py:1608
msgid "Getting upgrade prerequisites failed"
msgstr "فشل جلب متطلبات الترقية"

#: ../DistUpgrade/DistUpgradeController.py:1609
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Additionally, a bug reporting process is being started."
msgstr ""
"النظام غير قادر على الحصول على المتطلبات الأساسية للترقية. ستُلغى الآن عملية "
"الترقية وسيُعاد النظام للحالة الأصلية.\n"
"\n"
"بالإضافة إلى ذلك، يجري بدء عملية للإبلاغ عن العلّة."

#: ../DistUpgrade/DistUpgradeController.py:1637
msgid "Updating repository information"
msgstr "يحدّث معلومات المستودعات"

#: ../DistUpgrade/DistUpgradeController.py:1644
msgid "Failed to add the cdrom"
msgstr "فشل في إضافة القرص المدمج"

#: ../DistUpgrade/DistUpgradeController.py:1645
msgid "Sorry, adding the cdrom was not successful."
msgstr "عفواً، لم يتم إضافة القرص المدمج بنجاح."

#: ../DistUpgrade/DistUpgradeController.py:1673
msgid "Invalid package information"
msgstr "معلومات حزم غير صحيحة"

#: ../DistUpgrade/DistUpgradeController.py:1674
msgid "After updating your package "
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1698
#: ../DistUpgrade/DistUpgradeController.py:1750
msgid "Fetching"
msgstr "يجلب"

#: ../DistUpgrade/DistUpgradeController.py:1704
#: ../DistUpgrade/DistUpgradeController.py:1754
msgid "Upgrading"
msgstr "تجري الترقية"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1709
#: ../DistUpgrade/DistUpgradeController.py:1756
#: ../DistUpgrade/DistUpgradeController.py:1763
#: ../DistUpgrade/DistUpgradeController.py:1774
msgid "Upgrade complete"
msgstr "انتهت الترقية"

#: ../DistUpgrade/DistUpgradeController.py:1710
#: ../DistUpgrade/DistUpgradeController.py:1757
#: ../DistUpgrade/DistUpgradeController.py:1764
msgid ""
"The upgrade has completed but there were errors during the upgrade process."
msgstr "الترقية اكتملت، ولكن كان هناك أخطاء أثناء عملية الترقية."

#: ../DistUpgrade/DistUpgradeController.py:1717
msgid "Searching for obsolete software"
msgstr "يبحث عن برمجيات قديمة"

#: ../DistUpgrade/DistUpgradeController.py:1726
msgid "System upgrade is complete."
msgstr "تمت ترقية النظام."

#: ../DistUpgrade/DistUpgradeController.py:1775
msgid "The partial upgrade was completed."
msgstr "انتهت الترقية الجزئية."

#: ../DistUpgrade/DistUpgradeQuirks.py:204
msgid "evms in use"
msgstr "evms قيد الاستخدام"

#: ../DistUpgrade/DistUpgradeQuirks.py:205
msgid ""
"Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
"software is no longer supported, please switch it off and run the upgrade "
"again when this is done."
msgstr ""
"يستخدم نظامك مدير الصوت 'evms' في /proc/mounts. برمجيات 'evms' لم تعد "
"مدعومة، من فضلك أغلقه ونفذ الترقية مجددا عندما ينتهي."

#: ../DistUpgrade/DistUpgradeQuirks.py:502
msgid "Your graphics hardware may not be fully supported in Ubuntu 12.04 LTS."
msgstr "قد يكون عتاد الرسوميات في جهازك غير مدعوم بالكامل في أوبنتو 12.04."

#: ../DistUpgrade/DistUpgradeQuirks.py:504
msgid ""
"The support in Ubuntu 12.04 LTS for your Intel graphics hardware is limited "
"and you may encounter problems after the upgrade. For more information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx Do you want to "
"continue with the upgrade?"
msgstr ""
"دعم أوبنتو 12.04 لعتاد الرسوميات في جهازك محدود وقد تواجه مشاكل بعد الترقية. "
"لمزيد من المعلومات انظر: https://wiki.ubuntu.com/X/Bugs/"
"UpdateManagerWarningForI8xx هل تود الاستمرار في الترقية؟"

#: ../DistUpgrade/DistUpgradeQuirks.py:526
#: ../DistUpgrade/DistUpgradeQuirks.py:554
#: ../DistUpgrade/DistUpgradeQuirks.py:581
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"قد تقلل الترقية من تأثيرات سطح المكتب، وأداء الألعاب وبرامج الرسوميات "
"المكثفة الأخرى."

#: ../DistUpgrade/DistUpgradeQuirks.py:530
#: ../DistUpgrade/DistUpgradeQuirks.py:558
msgid ""
"This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
"version of this driver is available that works with your video card in "
"Ubuntu 10.04 LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"يستخدم حاسوبك حاليا مشغل 'nvidia' لرسوميات NVIDIA. لا توجد نسخة من هذا "
"المشغل متوافقة مع عتادك في أوبونتو 10.04 LTS.\n"
"\n"
"أتريد المواصلة؟"

#: ../DistUpgrade/DistUpgradeQuirks.py:585
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"يستخدم حاسوبك حاليا مشغل 'fglrx' لرسوميات AMD. لا توجد نسخة من هذا المشغل "
"متوافقة مع عتادك في أوبونتو 10.04 LTS.\n"
"\n"
"أتريد المواصلة؟"

#: ../DistUpgrade/DistUpgradeQuirks.py:615
msgid "No i686 CPU"
msgstr "لا يوجد معالج i686"

#: ../DistUpgrade/DistUpgradeQuirks.py:616
msgid ""
"Your system uses an i586 CPU or a CPU that does not have the 'cmov' "
"extension. All packages were built with optimizations requiring i686 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"نظامك يستخدم وحدة معالجة مركزية من طراز i586 لا تملك ملحق cmov. تم بناء كل "
"الحزم متطلبةً لبنية i686 كحد أدنى. ليس من الممكن ترقية نظامك إلى إصدارة "
"أوبونتو الجديدة مع هذا العتاد."

#: ../DistUpgrade/DistUpgradeQuirks.py:652
msgid "No ARMv6 CPU"
msgstr "لا معالج ARMv6"

#: ../DistUpgrade/DistUpgradeQuirks.py:653
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"نظامك يستخدم معالج ARM أقدم من معمارية ARMv6. إن جميع الحزم في النسخة karmic "
"مبنية لتعمل على الطراز ARMv6 كحد أدنى. من غير الممكن ترقية نظامك إلى إصدارة "
"أوبونتو حديثة مع هذا العتاد."

#: ../DistUpgrade/DistUpgradeQuirks.py:673
msgid "No init available"
msgstr "لا يوجد عفريت مدير للعمليات"

#: ../DistUpgrade/DistUpgradeQuirks.py:674
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"يبدو أن نظامك يعمل في بيئة ظاهرية بدون عفريت بدأ، مثلاً Linux-VServer. لا "
"يستطيع أوبنتو 10.04 د.ط.أ (دعم طويل الأمد) العمل في هذا النوع من بيئات "
"العمل، يتطلب تحديثًا لإعدادات الألة الظاهرية أولاً.\n"
"\n"
"هل حقاً تريد الاستمرار؟"

#: ../DistUpgrade/DistUpgradeMain.py:65
msgid "Sandbox upgrade using aufs"
msgstr "ترقية في بيئة محكومة (صندوق رمل)"

#: ../DistUpgrade/DistUpgradeMain.py:67
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr "ابحث في المسار المعطى عن قرص مدمج يحوي حزم ترقية"

#: ../DistUpgrade/DistUpgradeMain.py:73
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"استخدم واجهة. المتاح حاليا:\n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKD"

#: ../DistUpgrade/DistUpgradeMain.py:76
msgid "*DEPRECATED* this option will be ignored"
msgstr "*مهجور* سيتم تجاهل هذا الخيار"

#: ../DistUpgrade/DistUpgradeMain.py:79
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr "قم بترقية جزئية فقط (لا كتابة فوق sources.list)"

#: ../DistUpgrade/DistUpgradeMain.py:82
msgid "Disable GNU screen support"
msgstr "عطل دعم شاشة جنو"

#: ../DistUpgrade/DistUpgradeMain.py:84
msgid "Set datadir"
msgstr "حدد مجلد البيانات"

#. print("mediaChange %s %s" % (medium, drive))
#: ../DistUpgrade/DistUpgradeViewGtk.py:114
#: ../DistUpgrade/DistUpgradeViewGtk3.py:117
#: ../DistUpgrade/DistUpgradeViewKDE.py:195
#: ../UpdateManager/DistUpgradeFetcherKDE.py:155
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "رجاء أدرج '%s' في محرك الأقراص '%s'"

#: ../DistUpgrade/DistUpgradeViewGtk.py:135
#: ../DistUpgrade/DistUpgradeViewGtk3.py:138
#: ../DistUpgrade/DistUpgradeViewKDE.py:209
msgid "Fetching is complete"
msgstr "تم الجلب"

#: ../DistUpgrade/DistUpgradeViewGtk.py:146
#: ../DistUpgrade/DistUpgradeViewGtk3.py:149
#: ../DistUpgrade/DistUpgradeViewKDE.py:222
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "يجلب الملف %li من %li بـ %sبايت/ثانية"

#: ../DistUpgrade/DistUpgradeViewGtk.py:149
#: ../DistUpgrade/DistUpgradeViewGtk.py:296
#: ../DistUpgrade/DistUpgradeViewGtk3.py:152
#: ../DistUpgrade/DistUpgradeViewGtk3.py:309
#: ../DistUpgrade/DistUpgradeViewKDE.py:223
#: ../DistUpgrade/DistUpgradeViewKDE.py:371
#, python-format
msgid "About %s remaining"
msgstr "بقي %s تقريبا"

#: ../DistUpgrade/DistUpgradeViewGtk.py:152
#: ../DistUpgrade/DistUpgradeViewGtk3.py:155
#: ../DistUpgrade/DistUpgradeViewKDE.py:225
#, python-format
msgid "Fetching file %li of %li"
msgstr "يجلب الملف %li من %li"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:183
#: ../DistUpgrade/DistUpgradeViewGtk3.py:186
#: ../DistUpgrade/DistUpgradeViewKDE.py:262
msgid "Applying changes"
msgstr "يطبّق التغييرات"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk.py:208
#: ../DistUpgrade/DistUpgradeViewGtk3.py:212
#: ../DistUpgrade/DistUpgradeViewKDE.py:275
msgid "dependency problems - leaving unconfigured"
msgstr "مشكلة اعتمادية - سأغادر بدون إعداد"

#: ../DistUpgrade/DistUpgradeViewGtk.py:213
#: ../DistUpgrade/DistUpgradeViewGtk3.py:217
#: ../DistUpgrade/DistUpgradeViewKDE.py:277
#, python-format
msgid "Could not install '%s'"
msgstr "تعذّر تثبيت '%s'"

#: ../DistUpgrade/DistUpgradeViewGtk.py:214
#: ../DistUpgrade/DistUpgradeViewGtk3.py:218
#: ../DistUpgrade/DistUpgradeViewKDE.py:278
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr "ستواصل الترقية لكن حزمة '%s' قد لا تعمل. من فضلك أبلغ عن هذه العلة."

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:231
#: ../DistUpgrade/DistUpgradeViewGtk3.py:235
#: ../DistUpgrade/DistUpgradeViewKDE.py:299
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"أأستبدل الملف المطوع\n"
"'%s'؟"

#: ../DistUpgrade/DistUpgradeViewGtk.py:232
#: ../DistUpgrade/DistUpgradeViewGtk3.py:236
#: ../DistUpgrade/DistUpgradeViewKDE.py:300
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"ستفقد أي تغيرات كنت قد أحدثتها في ملف التضبيطات هذا إن اخترت استبداله "
"بإصدارة أحدث."

#: ../DistUpgrade/DistUpgradeViewGtk.py:251
#: ../DistUpgrade/DistUpgradeViewGtk3.py:256
#: ../DistUpgrade/DistUpgradeViewKDE.py:323
msgid "The 'diff' command was not found"
msgstr "تعذّر العثور على أمر 'diff'"

#: ../DistUpgrade/DistUpgradeViewGtk.py:464
#: ../DistUpgrade/DistUpgradeViewGtk3.py:477
#: ../DistUpgrade/DistUpgradeViewText.py:92
msgid "A fatal error occurred"
msgstr "حدث خطأ فادح"

#: ../DistUpgrade/DistUpgradeViewGtk.py:465
#: ../DistUpgrade/DistUpgradeViewGtk3.py:478
msgid ""
"Please report this as a bug (if you haven't already) and include the files /"
"var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"رجاءً أبلغ عن هذا كعلّة (إذا لم تكن قد فعلت) و أرفق الملفان /var/log/dist-"
"upgrade/main.log و /var/log/dist-upgrade/apt.log في البلاغ. تم الخروج من "
"الترقية.\n"
"ملف sources.list الأصلي حُفِظَ في /etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewGtk.py:482
#: ../DistUpgrade/DistUpgradeViewGtk3.py:495
msgid "Ctrl-c pressed"
msgstr "ضُغط Ctrl-c"

#: ../DistUpgrade/DistUpgradeViewGtk.py:483
#: ../DistUpgrade/DistUpgradeViewGtk3.py:496
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"هذا سيجهض العملية وقد يترك النظام في حالة معطوبة. أمتأكد أنك تريد فعل ذلك؟"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:631
#: ../DistUpgrade/DistUpgradeViewGtk3.py:629
msgid "To prevent data loss close all open applications and documents."
msgstr "لتلافي فقد البيانات أغلق جميع التطبيقات والمستندات."

#: ../DistUpgrade/DistUpgradeViewGtk.py:645
#: ../DistUpgrade/DistUpgradeViewGtk3.py:643
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr "لم تعد كانونيكال تدعمها (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:646
#: ../DistUpgrade/DistUpgradeViewGtk3.py:644
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr "<b>إلى إصدارة أقدم (%s)</b>"

#: ../DistUpgrade/DistUpgradeViewGtk.py:647
#: ../DistUpgrade/DistUpgradeViewGtk3.py:645
#, python-format
msgid "Remove (%s)"
msgstr "أزل (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:648
#: ../DistUpgrade/DistUpgradeViewGtk3.py:646
#, python-format
msgid "No longer needed (%s)"
msgstr "لم تعد مطلوبة (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:649
#: ../DistUpgrade/DistUpgradeViewGtk3.py:647
#, python-format
msgid "Install (%s)"
msgstr "ثبّت (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:650
#: ../DistUpgrade/DistUpgradeViewGtk3.py:648
#, python-format
msgid "Upgrade (%s)"
msgstr "رقّ (%s)"

#. change = QMessageBox.question(None, _("Media Change"), msg, QMessageBox.Ok, QMessageBox.Cancel)
#: ../DistUpgrade/DistUpgradeViewKDE.py:196
#: ../UpdateManager/DistUpgradeFetcherKDE.py:157
msgid "Media Change"
msgstr "تغيير الوسائط"

#: ../DistUpgrade/DistUpgradeViewKDE.py:335
msgid "Show Difference >>>"
msgstr "أظهر الفرق >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:338
msgid "<<< Hide Difference"
msgstr "<<< أخف الفرق"

#: ../DistUpgrade/DistUpgradeViewKDE.py:554
msgid "Error"
msgstr "خطأ"

#: ../DistUpgrade/DistUpgradeViewKDE.py:568
msgid "&Cancel"
msgstr "أ&لغِ"

#: ../DistUpgrade/DistUpgradeViewKDE.py:572
#: ../DistUpgrade/DistUpgradeViewKDE.py:813
msgid "&Close"
msgstr "أ&غلق"

#: ../DistUpgrade/DistUpgradeViewKDE.py:618
msgid "Show Terminal >>>"
msgstr "أظهر الطرفية >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:621
msgid "<<< Hide Terminal"
msgstr "<<< أخف الطرفية"

#: ../DistUpgrade/DistUpgradeViewKDE.py:701
msgid "Information"
msgstr "معلومات"

#: ../DistUpgrade/DistUpgradeViewKDE.py:751
#: ../DistUpgrade/DistUpgradeViewKDE.py:796
#: ../DistUpgrade/DistUpgradeViewKDE.py:799 ../DistUpgrade/DistUpgrade.ui.h:7
msgid "Details"
msgstr "التّفاصيل"

#: ../DistUpgrade/DistUpgradeViewKDE.py:777
#, python-format
msgid "No longer supported %s"
msgstr "لم تعد مدعومة %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:779
#, python-format
msgid "Remove %s"
msgstr "أزل %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:781
#: ../DistUpgrade/DistUpgradeViewText.py:182
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "أزل %s (ثبّت تلقائيا)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:783
#, python-format
msgid "Install %s"
msgstr "ثبّت %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:785
#, python-format
msgid "Upgrade %s"
msgstr "رقِّ %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:809
#: ../DistUpgrade/DistUpgradeViewText.py:230
msgid "Restart required"
msgstr "إعادة التشغيل مطلوبة"

#: ../DistUpgrade/DistUpgradeViewKDE.py:809
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr "<b><big>أعد تشغيل النظام لإتمام الترقية</big><b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:812 ../DistUpgrade/DistUpgrade.ui.h:14
#: ../data/gtkbuilder/UpdateManager.ui.h:26
msgid "_Restart Now"
msgstr "أ_عد التشغيل الآن"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:830
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>أألغ الترقية الجارية ؟</big></b>\n"
"\n"
"قد يصبح النظام في حالة غير صالحة للاستعمال إذا ألغيت الترقية. ننصح بشدة "
"استئناف الترقية."

#: ../DistUpgrade/DistUpgradeViewKDE.py:834
msgid "Cancel Upgrade?"
msgstr "أألغي الترقية؟"

#: ../DistUpgrade/DistUpgradeView.py:61
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "لا أيام"
msgstr[1] "يوم واحد"
msgstr[2] "يومان"
msgstr[3] "%li أيام"
msgstr[4] "%li يوما"
msgstr[5] "%li يوم"

#: ../DistUpgrade/DistUpgradeView.py:63
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "لا ساعات"
msgstr[1] "ساعة واحدة"
msgstr[2] "ساعاتان"
msgstr[3] "%li ساعات"
msgstr[4] "%li ساعة"
msgstr[5] "%li ساعة"

#: ../DistUpgrade/DistUpgradeView.py:65
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "لا دقائق"
msgstr[1] "دقيقة واحدة"
msgstr[2] "دقيقتان"
msgstr[3] "%li دقائق"
msgstr[4] "%li دقيقة"
msgstr[5] "%li دقيقة"

#: ../DistUpgrade/DistUpgradeView.py:66
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "لا ثوان"
msgstr[1] "ثانية واحدة"
msgstr[2] "ثانيتان"
msgstr[3] "%li ثوان"
msgstr[4] "%li ثانية"
msgstr[5] "%li ثانية"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:82
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:100
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:151
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""
"سيأخذ التنزيل حوالي %s على اتصال بسرعة 1م.بايت، وحوالي %s على مودم 56ك."

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:155
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "سيستغرق التنزيل حوالي %s بسرعة اتصالك. "

#. Declare these translatable strings from the .ui files here so that
#. xgettext picks them up.
#: ../DistUpgrade/DistUpgradeView.py:259 ../DistUpgrade/DistUpgrade.ui.h:21
msgid "Preparing to upgrade"
msgstr "يحضّر للترقية"

#: ../DistUpgrade/DistUpgradeView.py:260
msgid "Getting new software channels"
msgstr "يجلب قنوات البرمجيات الجديدة"

#: ../DistUpgrade/DistUpgradeView.py:261 ../DistUpgrade/DistUpgrade.ui.h:23
msgid "Getting new packages"
msgstr "يجلب الحزم الجديدة"

#: ../DistUpgrade/DistUpgradeView.py:262 ../DistUpgrade/DistUpgrade.ui.h:26
msgid "Installing the upgrades"
msgstr "يثبّت الترقيات"

#: ../DistUpgrade/DistUpgradeView.py:263 ../DistUpgrade/DistUpgrade.ui.h:25
msgid "Cleaning up"
msgstr "ينظّف"

#: ../DistUpgrade/DistUpgradeView.py:348
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
"ليس أي من الحزم المثبتة لم تعد كانونيكال تدعمه. مازال بإمكانك الحصول على "
"الدعم من المجتمع."
msgstr[1] ""
"واحدة من الحزم المثبتة لم تعد كانونيكال تدعمه. مازال بإمكانك الحصول على "
"الدعم من المجتمع."
msgstr[2] ""
"اثنتان من الحزم المثبتة لم تعد كانونيكال تدعمه. مازال بإمكانك الحصول على "
"الدعم من المجتمع."
msgstr[3] ""
"%(amount)d حزم من المثبتة لم تعد كانونيكال تدعمه. مازال بإمكانك الحصول على "
"الدعم من المجتمع."
msgstr[4] ""
"%(amount)d حزمة من المثبتة لم تعد كانونيكال تدعمه. مازال بإمكانك الحصول على "
"الدعم من المجتمع."
msgstr[5] ""
"%(amount)d حزمة من المثبتة لم تعد كانونيكال تدعمه. مازال بإمكانك الحصول على "
"الدعم من المجتمع."

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:357
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "لن تزال أية حزمة."
msgstr[1] "ستزال حزمة واحدة."
msgstr[2] "ستزال حزمتان."
msgstr[3] "ستزال %d حزم."
msgstr[4] "ستزال %d حزمة."
msgstr[5] "ستزال %d حزمة."

#: ../DistUpgrade/DistUpgradeView.py:362
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "لن تثبت أي حزم جديدة."
msgstr[1] "ستثبت حزمة واحدة جديدة."
msgstr[2] "ستثبت حزمتان جديدتان."
msgstr[3] "ستثبت %d حزم جديدة."
msgstr[4] "ستثبت %d حزمة جديدة."
msgstr[5] "ستثبت %d حزمة جديدة."

#: ../DistUpgrade/DistUpgradeView.py:368
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "لن ترقى أي حزم جديدة."
msgstr[1] "سترقى حزمة واحدة جديدة."
msgstr[2] "سترقى حزمتان جديدتان."
msgstr[3] "سترقى %d حزم جديدة."
msgstr[4] "سترقى %d حزمة جديدة."
msgstr[5] "سترقى %d حزمة جديدة."

#: ../DistUpgrade/DistUpgradeView.py:373
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"تحتاج لتنزيل ما مجمله %s. "

#: ../DistUpgrade/DistUpgradeView.py:378
msgid ""
"Installing the upgrade can take several hours. Once the download has "
"finished, the process cannot be canceled."
msgstr ""
"تثبيت الترقية قد يأخذ بضع ساعات. حالما ينتهي التنزيل، فلا يمكن إلغاء العملية."

#: ../DistUpgrade/DistUpgradeView.py:382
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be canceled."
msgstr ""
"جلب وتثبيت الترقية قد يأخذ بضع ساعات. حالما ينتهي التنزيل، لا يمكن إلغاء "
"العملية."

#: ../DistUpgrade/DistUpgradeView.py:387
msgid "Removing the packages can take several hours. "
msgstr "إزالة الحزم قد يأخذ بضع ساعات. "

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:392 ../UpdateManager/UpdateManager.py:676
msgid "The software on this computer is up to date."
msgstr "البرمجيات على هذا الحاسوب مُحدّثة."

#: ../DistUpgrade/DistUpgradeView.py:393
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr "لا توجد أي ترقيات متوفرة لنظامك. ستلغى الترقية الآن."

#: ../DistUpgrade/DistUpgradeView.py:406
msgid "Reboot required"
msgstr "إعادة التشغيل مطلوبة"

#: ../DistUpgrade/DistUpgradeView.py:407
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr "لقد انتهت الترقية وإعادة التشغيل مطلوبة. هل تود القيام بذلك الآن؟"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:72
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:72
#, python-format
msgid "authenticate '%(file)s' against '%(signature)s' "
msgstr "توثيق '%(file)s' باستخدام البصمة '%(signature)s' "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:131
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:131
#, python-format
msgid "extracting '%s'"
msgstr "يستخرج '%s'"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:151
#: ../DistUpgrade/DistUpgradeFetcherCore.py:152
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:151
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:152
msgid "Could not run the upgrade tool"
msgstr "تعذّر تشغيل أداة الترقية"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:152
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:152
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug "
"using the command 'ubuntu-bug update-manager'."
msgstr ""
"على الأرجح هذه مشكلة في أداة الترقية. رجاءً أبلغ عنها كعلّة باستخدام الأمر "
"'ubuntu-bug update-manager' في الطرفية."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:227
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:227
msgid "Upgrade tool signature"
msgstr "توقيع أداة الترقية"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:234
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:234
msgid "Upgrade tool"
msgstr "أداة الترقية"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:268
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:268
msgid "Failed to fetch"
msgstr "فشل الجلب"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:269
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:269
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr "فشل جلب الترقية، قد تكون هناك مشكلة في الشبكة. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:273
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:273
msgid "Authentication failed"
msgstr "فشل الاستيثاق"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:274
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:274
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr "فشل استيثاق الترقية. قد توجد مشكلة في الشبكة أو في الخادوم. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:279
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:279
msgid "Failed to extract"
msgstr "فشل الاستخراج"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:280
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:280
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr "فشل استخلاص الترقية، قد تكون هناك مشكلة في الشبكة أو الخادوم. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:285
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:285
msgid "Verification failed"
msgstr "فشل التحقق"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:286
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:286
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr "فشل التحقق من الترقية. قد توجد مشكلة في الشبكة أو في الخادوم. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:300
#: ../DistUpgrade/DistUpgradeFetcherCore.py:306
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:300
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:306
msgid "Can not run the upgrade"
msgstr "لا يمكن اجراء الترقية"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:301
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:301
msgid ""
"This usually is caused by a system where /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"غالباً ما يحدث هذا إذا ما تم تحميل /tmp بإشارة nonexec. رجاءاً أعد التحميل "
"بدون nonexec ثم أعد تشغيل الترقية."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:307
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:307
#, python-format
msgid "The error message is '%s'."
msgstr "رسالة الخطأ هي '%s'."

#: ../DistUpgrade/DistUpgradeViewText.py:93
msgid ""
"Please report this as a bug and include the files /var/log/dist-upgrade/main."
"log and /var/log/dist-upgrade/apt.log in your report. The upgrade has "
"aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"رجاءً أبلغ عن هذا كعلّة وأرفق الملفان /var/log/dist-upgrade/main.log و /var/"
"log/dist-upgrade/apt.log في البلاغ. تم الخروج من الترقية.\n"
"ملف sources.list الأصلي حُفِظَ في /etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewText.py:117
msgid "Aborting"
msgstr "يُجهض"

#: ../DistUpgrade/DistUpgradeViewText.py:122
msgid "Demoted:\n"
msgstr "حطّت رتبته:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:129
msgid "To continue please press [ENTER]"
msgstr "للإستمرار اضغط على [Enter]"

#: ../DistUpgrade/DistUpgradeViewText.py:157
#: ../DistUpgrade/DistUpgradeViewText.py:196
#: ../DistUpgrade/DistUpgradeViewText.py:203
msgid "Continue [yN] "
msgstr "استمر [ن(ل)] "

#: ../DistUpgrade/DistUpgradeViewText.py:157
#: ../DistUpgrade/DistUpgradeViewText.py:196
msgid "Details [d]"
msgstr "التّفاصيل [ف]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:162
#: ../DistUpgrade/DistUpgradeViewText.py:206
msgid "y"
msgstr "ن"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:165
#: ../DistUpgrade/DistUpgradeViewText.py:213
msgid "n"
msgstr "ل"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:168
msgid "d"
msgstr "ف"

#: ../DistUpgrade/DistUpgradeViewText.py:173
#, python-format
msgid "No longer supported: %s\n"
msgstr "لم تعد مدعومة: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:178
#, python-format
msgid "Remove: %s\n"
msgstr "إزالة: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:188
#, python-format
msgid "Install: %s\n"
msgstr "تثبيت: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:193
#, python-format
msgid "Upgrade: %s\n"
msgstr "ترقية: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:210
msgid "Continue [Yn] "
msgstr "تابع [Yn] "

#: ../DistUpgrade/DistUpgradeViewText.py:231
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"لإتمام الترقية تنبغي إعادة تشغيل النظام.\n"
"إن اخترت 'ن' فإن النظام سيعاد تشغيله."

#: ../DistUpgrade/DistUpgrade.ui.h:1
msgid "_Cancel Upgrade"
msgstr "أ_لغ الترقية"

#: ../DistUpgrade/DistUpgrade.ui.h:2
msgid "_Resume Upgrade"
msgstr "أ_كمل التحديث"

#: ../DistUpgrade/DistUpgrade.ui.h:3
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>أألغي الترقية الجارية؟</big></b>\n"
"\n"
"إن ألغيت الترقية فقد يبقى نظامك في حالة غير صالحة للاستخدام. نحثك بشدة أن "
"تواصل الترقية."

#: ../DistUpgrade/DistUpgrade.ui.h:6
msgid "_Start Upgrade"
msgstr "اب_دأ الترقية"

#: ../DistUpgrade/DistUpgrade.ui.h:9
msgid "_Replace"
msgstr "_استبدل"

#: ../DistUpgrade/DistUpgrade.ui.h:10
msgid "Difference between the files"
msgstr "الفرق بين الملفات"

#: ../DistUpgrade/DistUpgrade.ui.h:11
msgid "_Report Bug"
msgstr "أ_بلغ عن علّة"

#: ../DistUpgrade/DistUpgrade.ui.h:12
msgid "_Continue"
msgstr "ا_ستمر"

#: ../DistUpgrade/DistUpgrade.ui.h:13
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>أأبدأ الترقية؟</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:15
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>أعد تشغيل النظام لإكمال عملية الترقية</big></b>\n"
"\n"
"من فضلك احفظ أي عمل كنت تقوم به أولا."

#: ../DistUpgrade/DistUpgrade.ui.h:18
msgid "Distribution Upgrade"
msgstr "ترقية التوزيعة"

#: ../DistUpgrade/DistUpgrade.ui.h:19
#, fuzzy
msgid "<b><big>Upgrading Ubuntu to version 12.10</big></b>"
msgstr "<b><big>ترقية أبونتو إلى الإصدارة 12.04</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:20
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.ui.h:22
msgid "Setting new software channels"
msgstr "يضبط قنوات البرمجيات الجديدة"

#: ../DistUpgrade/DistUpgrade.ui.h:24
msgid "Restarting the computer"
msgstr "يعيد تشغيل الحاسوب"

#: ../DistUpgrade/DistUpgrade.ui.h:27
msgid "Terminal"
msgstr "طرفية"

#: ../UpdateManager/backend/InstallBackendSynaptic.py:64
msgid "Please wait, this can take some time."
msgstr "رجاء انتظر، قد يستغرق هذا وقتا"

#: ../UpdateManager/backend/InstallBackendSynaptic.py:66
msgid "Update is complete"
msgstr "لقد انتهت عملية التحديث"

#: ../UpdateManager/DistUpgradeFetcher.py:114
#: ../UpdateManager/DistUpgradeFetcherKDE.py:109
msgid "Could not find the release notes"
msgstr "تعذّر العثور على ملاحظات الإصدارة"

#: ../UpdateManager/DistUpgradeFetcher.py:115
#: ../UpdateManager/DistUpgradeFetcherKDE.py:110
msgid "The server may be overloaded. "
msgstr "قد يكون الخادوم محملا فوق طاقته. "

#: ../UpdateManager/DistUpgradeFetcher.py:125
#: ../UpdateManager/DistUpgradeFetcherKDE.py:114
msgid "Could not download the release notes"
msgstr "تعذّر تنزيل ملاحظات الإصدارة"

#: ../UpdateManager/DistUpgradeFetcher.py:126
#: ../UpdateManager/DistUpgradeFetcherKDE.py:115
msgid "Please check your internet connection."
msgstr "رجاء تأكد من اتصالك بالإنترنت"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:68
#: ../UpdateManager/DistUpgradeFetcherKDE.py:91
msgid "Upgrade"
msgstr "رقّ"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:95
#: ../data/gtkbuilder/UpdateManager.ui.h:20
#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:2
msgid "Release Notes"
msgstr "ملاحظات الإصدار"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:134
#: ../UpdateManager/DistUpgradeFetcherKDE.py:148
#: ../UpdateManager/DistUpgradeFetcherKDE.py:150
msgid "Downloading additional package files..."
msgstr "تنزيل ملفات الحزم الإضافية..."

#: ../UpdateManager/DistUpgradeFetcherKDE.py:148
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "الملف %s من %s بسرعة %s ب/ث"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:150
#, python-format
msgid "File %s of %s"
msgstr "ملف %s من %s"

#: ../UpdateManager/ChangelogViewer.py:75
msgid "Open Link in Browser"
msgstr "افتح الرابط في المتصفح"

#: ../UpdateManager/ChangelogViewer.py:78
msgid "Copy Link to Clipboard"
msgstr "انسخ الرابط إلى الحافظة"

#: ../UpdateManager/GtkProgress.py:162
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "ينزّل الملف %(current)li من %(total)li بسرعة %(speed)s/ثانية"

#: ../UpdateManager/GtkProgress.py:167
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "ينزّل الملف %(current)li من %(total)li"

#: ../UpdateManager/UpdateManager.py:106 ../do-release-upgrade:100
msgid "Your Ubuntu release is not supported anymore."
msgstr "نسختك من أبونتو لم تعد مدعومة بعد الآن."

#: ../UpdateManager/UpdateManager.py:107
msgid ""
"You will not get any further security fixes or critical updates. Please "
"upgrade to a later version of Ubuntu."
msgstr ""
"لن تحصل على المزيد من الإصلاحات الأمنية أو التحديثات الحرجة. يرجى الترقية "
"إلى آخر نسخة من أبونتو."

#: ../UpdateManager/UpdateManager.py:115
msgid "Upgrade information"
msgstr "معلومات الترقية"

#: ../UpdateManager/UpdateManager.py:233
#: ../UpdateManagerText/UpdateManagerText.py:35
msgid "Install"
msgstr "ثبّت"

#: ../UpdateManager/UpdateManager.py:235
msgid "Name"
msgstr "الاسم"

#. upload_archive = version_match.group(2).strip()
#: ../UpdateManager/UpdateManager.py:395
#, python-format
msgid "Version %s: \n"
msgstr "الإصدار %s: \n"

#: ../UpdateManager/UpdateManager.py:453
msgid ""
"No network connection detected, you can not download changelog information."
msgstr "لا يوجد اتصال بالشبكة، لن تستطيع الحصول على معلومات التغيير."

#: ../UpdateManager/UpdateManager.py:463
msgid "Downloading list of changes..."
msgstr "ينزّل قائمة التغييرات..."

#: ../UpdateManager/UpdateManager.py:507
msgid "_Deselect All"
msgstr "أ_زِل التحديد عن الكل"

#: ../UpdateManager/UpdateManager.py:513
msgid "Select _All"
msgstr "حدّد ال_كل"

#: ../UpdateManager/UpdateManager.py:572
#, python-format
msgid "%s will be downloaded."
msgstr "سينزل %s"

#: ../UpdateManager/UpdateManager.py:584
#, fuzzy
msgid "The update has already been downloaded."
msgid_plural "The updates have already been downloaded."
msgstr[0] "تم تنزي التحديثات ولكن لم تُثبّت."
msgstr[1] "تم تنزيل تحديث واحد، ولكن لم يُثبّت."
msgstr[2] "تم تنزيل تحديثين، ولكن لم يُثبّتا."
msgstr[3] "تم تنزيل التحديثات، ولكن لم تُثبّت."
msgstr[4] "تم تنزيل التحديثات، ولكن لم تُثبّت."
msgstr[5] "تم تنزيل التحديثات، ولكن لم تُثبّت."

#: ../UpdateManager/UpdateManager.py:589
msgid "There are no updates to install."
msgstr "لا توجد تحديثات للتثبيت."

#: ../UpdateManager/UpdateManager.py:598
msgid "Unknown download size."
msgstr "حجم التنزيل مجهول"

#: ../UpdateManager/UpdateManager.py:624
msgid ""
"It is unknown when the package information was updated last. Please click "
"the 'Check' button to update the information."
msgstr ""
"غير معروف متى حُدِّثت معلومات الحزم آخر مرة. رجاءً انقر زر 'التمس' لتحديث "
"المعلومات."

#: ../UpdateManager/UpdateManager.py:630
#, python-format
msgid ""
"The package information was last updated %(days_ago)s days ago.\n"
"Press the 'Check' button below to check for new software updates."
msgstr ""
"حُدّثت معلومات الحزم آخر مرة قبل %(days_ago)s أيام/يوم.\n"
"اضغط زر 'التمس' لفحص التحديثات الجديدة للبرمجيات."

#: ../UpdateManager/UpdateManager.py:635
#, python-format
msgid "The package information was last updated %(days_ago)s day ago."
msgid_plural "The package information was last updated %(days_ago)s days ago."
msgstr[0] "حُدّثت معلومات الحزم آخر مرة اليوم."
msgstr[1] "حُدّثت معلومات الحزم آخر مرة منذ يوم واحد."
msgstr[2] "حُدّثت معلومات الحزم آخر مرة منذ يومين."
msgstr[3] "حُدّثت معلومات الحزم آخر مرة منذ %(days_ago)s أيام."
msgstr[4] "حُدّثت معلومات الحزم آخر مرة منذ %(days_ago)s يوما."
msgstr[5] "حُدّثت معلومات الحزم آخر مرة منذ %(days_ago)s يوم."

#: ../UpdateManager/UpdateManager.py:639
#, python-format
msgid "The package information was last updated %(hours_ago)s hour ago."
msgid_plural ""
"The package information was last updated %(hours_ago)s hours ago."
msgstr[0] "حُدّثت معلومات الحزم آخر مرة منذ أقل من ساعة."
msgstr[1] "حُدّثت معلومات الحزم آخر مرة منذ ساعة."
msgstr[2] "حُدّثت معلومات الحزم آخر مرة منذ ساعتين."
msgstr[3] "حُدّثت معلومات الحزم آخر مرة منذ %(hours_ago)s ساعات."
msgstr[4] "حُدّثت معلومات الحزم آخر مرة منذ %(hours_ago)s ساعة."
msgstr[5] "حُدّثت معلومات الحزم آخر مرة منذ %(hours_ago)s ساعة."

#. TRANSLATORS: only in plural form, as %s minutes ago is one of 15, 30, 45 minutes ago
#: ../UpdateManager/UpdateManager.py:644 ../UpdateManager/UpdateManager.py:646
#: ../UpdateManager/UpdateManager.py:648
#, python-format
msgid "The package information was last updated about %s minutes ago."
msgstr "حُدّثت معلومات الحزم آخر مرة منذ حوالي %s دقيقة."

#: ../UpdateManager/UpdateManager.py:650
msgid "The package information was just updated."
msgstr "حُدثت معلومات الحزم توًا."

#: ../UpdateManager/UpdateManager.py:689
msgid "Software updates may be available for your computer."
msgstr "قد تتوفر تحديثات برمجيات لحاسوبك."

#: ../UpdateManager/UpdateManager.py:697
#, python-format
msgid ""
"Updated software has been issued since %s was released. Do you want to "
"install it now?"
msgstr ""

#: ../UpdateManager/UpdateManager.py:700
msgid ""
"Updated software is available for this computer. Do you want to install it "
"now?"
msgstr ""

#: ../UpdateManager/UpdateManager.py:758
#, python-format
msgid ""
"The upgrade needs a total of %s free space on disk '%s'. Please free at "
"least an additional %s of disk space on '%s'. Empty your trash and remove "
"temporary packages of former installations using 'sudo apt-get clean'."
msgstr ""
"يحتاج التحديث مجموع %s مساحة فارغة على القرص '%s'. من فضلك حرّر على الأقل %s "
"إضافي من مساحة القرص على '%s'. أفرغ مهملاك وأزل الحزم المؤقتة للتثبيتات "
"السابقة باستخدام 'sudo apt-get clean'."

#: ../UpdateManager/UpdateManager.py:783
msgid ""
"The computer needs to restart to finish installing updates. Please save your "
"work before continuing."
msgstr ""
"يحتاج الحاسوب لإعادة التشغيل لتطبيق التحديثات. من فضلك احفظ عملك قبل "
"المواصلة."

#: ../UpdateManager/UpdateManager.py:847
msgid "Reading package information"
msgstr "يقرأ معلومات الحزم"

#: ../UpdateManager/UpdateManager.py:862
msgid "Connecting..."
msgstr "يتصل..."

#: ../UpdateManager/UpdateManager.py:879
msgid "You may not be able to check for updates or download new updates."
msgstr "قد لا تستطيع التماس التحديثات أو تنزيل تحديثات جديدة."

#: ../UpdateManager/UpdateManager.py:1002
msgid "Could not initialize the package information"
msgstr "تعذّر تمهيد معلومات الحزم"

#: ../UpdateManager/UpdateManager.py:1003
msgid ""
"An unresolvable problem occurred while initializing the package "
"information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""
"مشكلة غير قابلة للحل صودفت أثناء تمهيد معلومات الحزم.\n"
"\n"
"من فضلك أبلغ هذه العلة لحزمة 'update-manager' وضمّن رسالة الخطأ التالية:\n"

#: ../UpdateManager/UpdateManager.py:1032
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr ""
"مشكلة غير قابلة للحل صودفت أثناء إحصاء الترقية.\n"
"\n"
"من فضلك أبلغ هذه العلة للحزمة 'update-manager' وضمّن رسالة الخطأ التالية:"

#: ../UpdateManager/UpdateManager.py:1056
msgid " (New install)"
msgstr " (تثبيت جديد)"

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:1063
#, python-format
msgid "(Size: %s)"
msgstr "(الحجم: %s)"

#: ../UpdateManager/UpdateManager.py:1067
#, python-format
msgid "From version %(old_version)s to %(new_version)s"
msgstr "من الإصدارة %(old_version)s إلى %(new_version)s"

#: ../UpdateManager/UpdateManager.py:1071
#, python-format
msgid "Version %s"
msgstr "الإصدارة %s"

#: ../UpdateManager/UpdateManager.py:1104 ../do-release-upgrade:112
msgid "Release upgrade not possible right now"
msgstr "يتعذّر ترقية الإصدارة حاليا"

#: ../UpdateManager/UpdateManager.py:1105 ../do-release-upgrade:113
#, c-format, python-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr "تعذّر ترفية الإصدارة حاليا، أعد المحاولة لاحقا. رد الخادوم: '%s'"

#: ../UpdateManager/UpdateManager.py:1107 ../check-new-release-gtk:126
msgid "Downloading the release upgrade tool"
msgstr "ينزّل أداة الترقية"

#: ../UpdateManager/UpdateManager.py:1114
#, python-format
msgid "<b>New Ubuntu release '%s' is available</b>"
msgstr "<b>تتوفر إصدارة جديدة '%s' من أوبونتو</b>"

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:1153
msgid "Software index is broken"
msgstr "فهرس البرمجيات تالف"

#: ../UpdateManager/UpdateManager.py:1154
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""
"لا يمكن تثبيت أو إزالة أي برمجيات. استخدم مدير الحزم \"Synaptic\" أو شغل "
"\"sudo apt-get install -f\" في مرقاب لمحاولة إصلاح هذه المشكلة أولا."

#: ../UpdateManager/UnitySupport.py:57
msgid "Check for Updates"
msgstr "التمس تحديثات"

#: ../UpdateManager/UnitySupport.py:66
msgid "Install All Available Updates"
msgstr "ثبّت جميع التحديثات المتوفرة"

#: ../UpdateManagerText/UpdateManagerText.py:34
msgid "Cancel"
msgstr "ألغِ"

#: ../UpdateManagerText/UpdateManagerText.py:37
msgid "Changelog"
msgstr "سجل التغييرات"

#: ../UpdateManagerText/UpdateManagerText.py:40
msgid "Updates"
msgstr "تحديثات"

#: ../UpdateManagerText/UpdateManagerText.py:53
msgid "Building Updates List"
msgstr "يبني قائمة التحديثات"

#: ../UpdateManagerText/UpdateManagerText.py:56
msgid ""
"\n"
"A normal upgrade can not be calculated, please run: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""
"\n"
"لا يمكن إحصاء ترقية عادية، من فضلك نفّذ: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"قد يكون هذا ناتج عن:\n"
" * ترقية سابقة لم تكتمل\n"
" * مشاكل مع بعض البرمجيات المثبتة\n"
" * حزم برمجيات غير رسمية ليست مقدمة من أبونتو\n"
" * تغييرات عادية لنسخة ما قبل الإصدار من أبونتو."

#: ../UpdateManagerText/UpdateManagerText.py:125
msgid "Downloading changelog"
msgstr "تنزيل سجل التغييرات"

#: ../UpdateManager/Core/MyCache.py:147
#, python-format
msgid "Other updates (%s)"
msgstr "تحديثات أخرى (%s)"

#: ../UpdateManager/Core/MyCache.py:325
msgid "This update does not come from a source that supports changelogs."
msgstr "هذا التحديث لا يأتي من مصدر يدعم سجل التغييرات."

#: ../UpdateManager/Core/MyCache.py:331 ../UpdateManager/Core/MyCache.py:359
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""
"فشل تنزيل قائمة التغييرات.\n"
"افحص اتصالك بإنترنت."

#: ../UpdateManager/Core/MyCache.py:338
#, python-format
msgid ""
"Changes for the versions:\n"
"Installed version: %s\n"
"Available version: %s\n"
"\n"
msgstr ""
"التغييرات في الإصدارات:\n"
"الإصدارة المُثبّتة: %s\n"
"الإصدارة المُتوفرة: %s\n"
"\n"

#: ../UpdateManager/Core/MyCache.py:348
#, python-format
msgid ""
"The changelog does not contain any relevant changes.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"لا يحتوي سجل التغييرات أي تغييرات متعلقة.\n"
"\n"
"من فضلك استخدم http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"حتى تتوفر التغييرات أو حاول مجددا لاحقا."

#: ../UpdateManager/Core/MyCache.py:353
#, python-format
msgid ""
"The list of changes is not available yet.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"قائمة التغييرات ليست متاحة بعد.\n"
"\n"
"من فضلك استخدام http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"حتى تتوفر التغييرات أو حاول مجددا لاحقا."

#: ../UpdateManager/Core/UpdateList.py:51
msgid "Failed to detect distribution"
msgstr "فشل الكشف على التوزيع"

#: ../UpdateManager/Core/UpdateList.py:52
#, python-format
msgid "A error '%s' occurred while checking what system you are using."
msgstr "صودف خطأ '%s' أثناء التماس ما يستخدمه النظام."

#: ../UpdateManager/Core/UpdateList.py:63
msgid "Important security updates"
msgstr "تحديثات أمنية مهمّة"

#: ../UpdateManager/Core/UpdateList.py:64
msgid "Recommended updates"
msgstr "تحديثات منصوح بها"

#: ../UpdateManager/Core/UpdateList.py:65
msgid "Proposed updates"
msgstr "تحديثات مقترحة"

#: ../UpdateManager/Core/UpdateList.py:66
msgid "Backports"
msgstr "تحديثات رجوعية"

#: ../UpdateManager/Core/UpdateList.py:67
msgid "Distribution updates"
msgstr "تحديثات التوزيعة"

#: ../UpdateManager/Core/UpdateList.py:72
msgid "Other updates"
msgstr "تحديثات أخرى"

#: ../data/gtkbuilder/UpdateManager.ui.h:1
#, fuzzy
msgid "<big><b>Starting Software Updater</b></big>"
msgstr "<big><b>يبدأ مدير التحديثات</b></big>"

#: ../data/gtkbuilder/UpdateManager.ui.h:2
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr "تحديثات البرمجيات تصحّح الأخطاء وتسد الثغرات الأمنية وتوّفر ميزات جديدة."

#: ../data/gtkbuilder/UpdateManager.ui.h:3
msgid "_Partial Upgrade"
msgstr "ترقية _جزئية"

#: ../data/gtkbuilder/UpdateManager.ui.h:4
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr "<big><b>تعذّر تثبيت كل التحديثات</b></big>"

#: ../data/gtkbuilder/UpdateManager.ui.h:5
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""
"شغّل ترقية جزئية لتنزيل أكبر عدد ممكن من التحديثات. \n"
"\n"
"قد يكون هذا بسبب:\n"
" * ترقية سابقة لم تكتمل\n"
" * مشاكل مع بعض البرمجيات المثبتة\n"
" * حزم برمجيات غير رسمية ليست من أبونتو\n"
" * تغييرات عادية في نسخة ما قبل الإصدار من أبونتو"

#: ../data/gtkbuilder/UpdateManager.ui.h:12
msgid "Chec_k"
msgstr "الت_مس"

#: ../data/gtkbuilder/UpdateManager.ui.h:13
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Updates</i> tab."
msgstr ""
"<b><big>ينبغي لك التماس التحديثات يدويا</big></b>\n"
"\n"
"نظامك لا يلتمس التحديثات أوتوماتيا. يمكنك ضبط هذا السلوك في <i>مصادر "
"البرمجيات</i> في لسان <i>التحديثات</i>."

#: ../data/gtkbuilder/UpdateManager.ui.h:16
msgid "_Hide this information in the future"
msgstr "_أخفِ هذة المعلومات في المستقبل"

#: ../data/gtkbuilder/UpdateManager.ui.h:17
msgid "Co_ntinue"
msgstr "ا_ستمرّ"

#: ../data/gtkbuilder/UpdateManager.ui.h:18
msgid "<big><b>Running on battery</b></big>"
msgstr "<big><b>يعمل على البطارية</b></big>"

#: ../data/gtkbuilder/UpdateManager.ui.h:19
msgid "Your system is running on battery. Are you sure you want to continue?"
msgstr "يعمل نظامك على البطارية. أمتأكد أنك تريد المتابعة؟"

#: ../data/gtkbuilder/UpdateManager.ui.h:21
msgid "_Upgrade"
msgstr "تر_قية"

#: ../data/gtkbuilder/UpdateManager.ui.h:22
#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:8
msgid "Show progress of individual files"
msgstr "أظهر تقدّم الملفات المفردة"

#: ../data/gtkbuilder/UpdateManager.ui.h:23
#: ../data/update-manager.desktop.in.h:1
#, fuzzy
msgid "Software Updater"
msgstr "تحديثات البرمجيات"

#: ../data/gtkbuilder/UpdateManager.ui.h:24
#, fuzzy
msgid "Starting Software Updater"
msgstr "تحديثات البرمجيات"

#: ../data/gtkbuilder/UpdateManager.ui.h:25
msgid "U_pgrade"
msgstr "ت_رقية"

#: ../data/gtkbuilder/UpdateManager.ui.h:27
msgid "updates"
msgstr "تحديثات"

#: ../data/gtkbuilder/UpdateManager.ui.h:28
msgid "Changes"
msgstr "التغييرات"

#: ../data/gtkbuilder/UpdateManager.ui.h:29
msgid "Description"
msgstr "الوصف"

#: ../data/gtkbuilder/UpdateManager.ui.h:30
#, fuzzy
msgid "Details of updates"
msgstr "وصف التحديث"

#: ../data/gtkbuilder/UpdateManager.ui.h:31
msgid ""
"You are connected via roaming and may be charged for the data consumed by "
"this update."
msgstr ""
"أنت متصل عبر التجوال ومن الممكن أن تحاسب على البيانات المستهلكة خلال هذا "
"التحديث."

#: ../data/gtkbuilder/UpdateManager.ui.h:32
msgid ""
"You may want to wait until you’re not using a mobile broadband connection."
msgstr ""

#: ../data/gtkbuilder/UpdateManager.ui.h:33
msgid "It’s safer to connect the computer to AC power before updating."
msgstr "إنه أكثر أماناً إذا وصلت حاسوبك بمنفذ الطاقة قبل البدء في التحديث."

#: ../data/gtkbuilder/UpdateManager.ui.h:34
msgid "_Settings..."
msgstr "الإ_عدادات..."

#: ../data/gtkbuilder/UpdateManager.ui.h:35
#, fuzzy
msgid "_Install Now"
msgstr "ثبّت"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:1
msgid "<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr "<b>تتوفر إصدارة جديدة من أوبونتو، أترغب في الترقية؟</b>"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:3
msgid "Don't Upgrade"
msgstr "لا أرغب"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:4
msgid "Ask Me Later"
msgstr "اسألني لاحقا"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:5
msgid "Yes, Upgrade Now"
msgstr "نعم، رقِّ الآن"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:6
msgid "You have declined to upgrade to the new Ubuntu"
msgstr "لقد رفضت الترقية إلى أوبونتو الجديدة"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:7
#, fuzzy
msgid ""
"You can upgrade at a later time by opening Software Updater and click on "
"\"Upgrade\"."
msgstr "يمكنك الترقية لاحقا بفتح مدير التحديثات والنقر على \"رقِّ\""

#: ../data/update-manager.desktop.in.h:2
msgid "Software Updates"
msgstr "تحديثات البرمجيات"

#: ../data/update-manager.desktop.in.h:3
msgid "Show and install available updates"
msgstr "أظهر وثبت التحديثات المتوفرة"

#: ../update-manager:66 ../update-manager-text:55 ../do-release-upgrade:51
msgid "Show version and exit"
msgstr "اعرض الإصدارة واخرج"

#: ../update-manager:69
msgid "Directory that contains the data files"
msgstr "المجلد الذي يحتوي ملفات البيانات"

#: ../update-manager:72
msgid "Check if a new Ubuntu release is available"
msgstr "التمس وجود إصدارة جديدة من أوبونتو"

#: ../update-manager:75 ../do-release-upgrade:54 ../check-new-release-gtk:186
msgid "Check if upgrading to the latest devel release is possible"
msgstr "يفحص إن كانت الترقية ممكنة إلى أحدث إصدارة تطوير"

#: ../update-manager:79
msgid "Upgrade using the latest proposed version of the release upgrader"
msgstr "رقّ باستخدام آخر نسخة موصى بها لمرقي الإصدار"

#: ../update-manager:86
msgid "Do not focus on map when starting"
msgstr "لا تركز على الخريطة عند البدء"

#: ../update-manager:89
msgid "Try to run a dist-upgrade"
msgstr "حاول تشغيل dist-upgrade"

#: ../update-manager:92
msgid "Do not check for updates when starting"
msgstr "لا تلتمس التحديثات عند البدء"

#: ../update-manager:96 ../do-release-upgrade:70
msgid "Test upgrade with a sandbox aufs overlay"
msgstr "اختبر الترقية في بيئة محكومة (صندوق رمل)"

#: ../update-manager:116
msgid "Running partial upgrade"
msgstr "يُجري ترقية جزئية"

#: ../update-manager-text:59
msgid "Show description of the package instead of the changelog"
msgstr "اعرض وصف الحزمة بدلًا من سجل التغييرات"

#: ../do-release-upgrade:58 ../check-new-release-gtk:190
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr "حاول الترقية إلى أحدث إصدارة باستخدام المحدِّث من $distro-proposed"

#: ../do-release-upgrade:62
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"يعمل في طور ترقية خاص.\n"
"حاليا الطوران المدعومان هما 'desktop' للترقية الاعتيادية لنظام سطح مكتب، و "
"'server' لنظم الخواديم."

#: ../do-release-upgrade:68
msgid "Run the specified frontend"
msgstr "يشغل الواجهة المحددة"

#: ../do-release-upgrade:73
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""
"تحقق فقط إذا كان هناك إصدار جديد من التوزيعة متوفرا و أرسل تقريرا خلال كود "
"الخروج"

#: ../do-release-upgrade:87
msgid "Checking for a new Ubuntu release"
msgstr "يتحقق من وجود إصدارة جديدة من أبونتو"

#: ../do-release-upgrade:101
msgid ""
"For upgrade information, please visit:\n"
"%(url)s\n"
msgstr ""
"لمعلومات عن الترقية، رجاءً قم بزيارة:\n"
"%(url)s\n"

#: ../do-release-upgrade:107
msgid "No new release found"
msgstr "لا توجد إصدارات أحدث"

#: ../do-release-upgrade:119
#, c-format
msgid "New release '%s' available."
msgstr "لا تتوفر إصدارات '%s'"

#: ../do-release-upgrade:120
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "شغّل 'do-release-upgrade' للترقية إليه."

#: ../check-new-release-gtk:101
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "يتوفر ترقية إلى أوبونتو %(version)s"

#: ../check-new-release-gtk:143
#, c-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr "لقد رفضت الترقية إلى أوبونتو %s"

#: ../check-new-release-gtk:196
msgid "Add debug output"
msgstr "أضف مُخرَجات التنقيح"

#: ../ubuntu-support-status:91
msgid "Show unsupported packages on this machine"
msgstr "اعرض الحزم الغير مدعومة على هذا الجهاز"

#: ../ubuntu-support-status:94
msgid "Show supported packages on this machine"
msgstr "اعرض الحزم المدعومة على هذا الجهاز"

#: ../ubuntu-support-status:97
msgid "Show all packages with their status"
msgstr "اعرض كُل الحزم مع حالاتها"

#: ../ubuntu-support-status:100
msgid "Show all packages in a list"
msgstr "اعرض كُل الحزم في قائمة"

#: ../ubuntu-support-status:142
#, c-format
msgid "Support status summary of '%s':"
msgstr "مُلخص حالة الدعم لـ '%s':"

#: ../ubuntu-support-status:145
msgid "You have %(num)s packages (%(percent).1f%%) supported until %(time)s"
msgstr "لديك %(num)s حزمة (%(percent).1f%%) مدعومة حتى %(time)s"

#: ../ubuntu-support-status:151
msgid ""
"You have %(num)s packages (%(percent).1f%%) that can not/no-longer be "
"downloaded"
msgstr "لديك %(num)s حزمة (%(percent).1f%%) لم تعد قابلة للتنزيل"

#: ../ubuntu-support-status:154
msgid "You have %(num)s packages (%(percent).1f%%) that are unsupported"
msgstr "لديك %(num)s حزمة (%(percent).1f%%) غير مدعومة"

#: ../ubuntu-support-status:162
msgid ""
"Run with --show-unsupported, --show-supported or --show-all to see more "
"details"
msgstr ""
"شغّل باستخدام --show-unsupported أو --show-supported أو --show-all لرؤية مزيد "
"من التفاصيل"

#: ../ubuntu-support-status:166
msgid "No longer downloadable:"
msgstr "لم تعد قابلة للتنزيل:"

#: ../ubuntu-support-status:169
msgid "Unsupported: "
msgstr "غير مدعومة: "

#: ../ubuntu-support-status:174
#, c-format
msgid "Supported until %s:"
msgstr "مدعومة حتى %s:"

#: ../ubuntu-support-status:183
msgid "Unsupported"
msgstr "غير مدعومة"

#. Why do we use %s here instead of $strings or {} format placeholders?
#. It's because we don't want to break existing translations.
#: ../janitor/plugincore/exceptions.py:42
#, python-format
msgid "Unimplemented method: %s"
msgstr "طريقة غير مطبقة: %s"

#: ../janitor/plugincore/core/file_cruft.py:41
msgid "A file on disk"
msgstr "ملف على القرص"

#: ../janitor/plugincore/core/missing_package_cruft.py:39
msgid "Install missing package."
msgstr "ثبّت الحزم الناقصة"

#. 2012-06-08 BAW: i18n string; don't use {} or PEP 292.
#: ../janitor/plugincore/core/missing_package_cruft.py:49
#, python-format
msgid "Package %s should be installed."
msgstr "يجب تثبيت الحزمة %s"

#: ../janitor/plugincore/core/package_cruft.py:49
msgid ".deb package"
msgstr "حزمة .deb"

#: ../janitor/plugincore/plugins/langpack_manual_plugin.py:46
#, python-format
msgid "%s needs to be marked as manually installed."
msgstr "%s تحتاج لتأشيرها على أنها مُثبَّتة يدويا."

#: ../janitor/plugincore/plugins/kdelibs4to5_plugin.py:49
msgid ""
"When upgrading, if kdelibs4-dev is installed, kdelibs5-dev needs to be "
"installed. See bugs.launchpad.net, bug #279621 for details."
msgstr ""
"أثناء الترقية، إذا كانت kdelibs4-dev مثبّتة فستحتج تثبيت kdelibs5-dev. راجع "
"bugs.launchpad.net، علة رقم #279621 لمزيد من التفاصيل."

#: ../janitor/plugincore/plugins/dpkg_status_plugin.py:44
#, python-format
msgid "%i obsolete entries in the status file"
msgstr "%i مدخلات قديمة في ملف الحالة"

#: ../janitor/plugincore/plugins/dpkg_status_plugin.py:47
msgid "Obsolete entries in dpkg status"
msgstr "مدخلات قديمة في حالة dpkg"

#. pragma: no cover
#: ../janitor/plugincore/plugins/dpkg_status_plugin.py:50
msgid "Obsolete dpkg status entries"
msgstr "مدخلات قديمة في حالة dpkg"

#: ../janitor/plugincore/plugins/remove_lilo_plugin.py:42
msgid "Remove lilo since grub is also installed.(See bug #314004 for details.)"
msgstr "أزٍل lilo حيث أن grub مثبّت. (راجع العلة #314004 لمزيد من التفاصيل)"

#~ msgid ""
#~ "After your package information was updated the essential package '%s' can "
#~ "not be found anymore so a bug reporting process is being started."
#~ msgstr ""
#~ "بعد أن تم تحديث معلومات الحزم، فإن الحزمة الأساسية '%s' لا يمكن العثور "
#~ "عليها بعد الآن، لذلك يجري بدء عملية للإبلاغ عن العلّة."

#~ msgid "%(count)s update has been selected."
#~ msgid_plural "%(count)s updates have been selected."
#~ msgstr[0] "لم تحدد أي تحديثات"
#~ msgstr[1] "حُدد تحديث واحد"
#~ msgstr[2] "حُدد تحديثين"
#~ msgstr[3] "حُددت %(count)s تحديثات"
#~ msgstr[4] "حُدد %(count)s تحديثا"
#~ msgstr[5] "حُدد %(count)s تحديث"

#~ msgid "%(count_str)s %(download_str)s"
#~ msgstr "%(count_str)s %(download_str)s"

#~ msgid "Welcome to Ubuntu"
#~ msgstr "مرحبًا بك في أوبونتو"

#~ msgid ""
#~ "These software updates have been issued since this version of Ubuntu was "
#~ "released."
#~ msgstr "صدرت هذه التحديثات البرمجية منذ إطلاق هذه الإصدارة من أبونتو."

#~ msgid "Software updates are available for this computer."
#~ msgstr "تتوفر تحديثات برمجيات لهذا الحاسوب."

#~ msgid "Update Manager"
#~ msgstr "مدير التحديثات"

#~ msgid "Starting Update Manager"
#~ msgstr "يبدأ مدير التحديثات"

#~ msgid "You are connected via a wireless modem."
#~ msgstr "أنت متصل عبر مودم لاسلكي."

#~ msgid "_Install Updates"
#~ msgstr "_ثبت التحديثات"

#~ msgid "Checking for a new ubuntu release"
#~ msgstr "يجري التماس إصدارة أحدث من أوبونتو"

#~ msgid "Your system is up-to-date"
#~ msgstr "نظامك محدّث"

#~ msgid ""
#~ "Fetching and installing the upgrade can take several hours. Once the "
#~ "download has finished, the process cannot be cancelled."
#~ msgstr ""
#~ "يمكن أن يستغرق جلب و تثبيت الترقية عدة ساعات؛ و بمجرد تمام التنزيل فإن "
#~ "السيرورة لا يمكن إلغاؤها."

#~ msgid ""
#~ "This upgrade is running in sandbox (test) mode. All changes are written "
#~ "to '%s' and will be lost on the next reboot.\n"
#~ "\n"
#~ "*No* changes written to a systemdir from now until the next reboot are "
#~ "permanent."
#~ msgstr ""
#~ "تعمل الترقية في طور صندوق الرمل (للاختبار). كل التغييرات التي ستكتب في "
#~ "'%s' ستُفقد بعد إعادة التشغيل.\n"
#~ "*لن* تكتب أي تغييرات في مجلدات النظام من الآن وحتى إعادة التشغيل."

#~ msgid "Software updates are available for this computer"
#~ msgstr "تتوفر تحديثات برمجية لهذا الحاسوب"

#~ msgid ""
#~ "If you don't want to install them now, choose \"Update Manager\" from the "
#~ "Administration menu later."
#~ msgstr ""
#~ "إذا لم تُرِد تثبيتها الآن فاختر \"مدير التحديثات\" لاحقا من قائمة الإدارة."

#~ msgid "There are no updates to install"
#~ msgstr "لا تحديثات لتثبيتها"

#~ msgid "The update has already been downloaded, but not installed"
#~ msgid_plural "The updates have already been downloaded, but not installed"
#~ msgstr[0] "لم ينزل التحديث"
#~ msgstr[1] "نُزّل التحديث لكن لم يثبّت"
#~ msgstr[2] "نُزّل التحديثين لكن لم يثبّتا"
#~ msgstr[3] "نُزّل التحديثات لكن لم تثبّت"
#~ msgstr[4] "نُزّل التحديثات لكن لم تثبّت"
#~ msgstr[5] "نُزّل التحديثات لكن لم تثبّت"

#~ msgid ""
#~ "You will not get any further security fixes or critical updates. Please "
#~ "upgrade to a later version of Ubuntu Linux."
#~ msgstr ""
#~ "لن تحصل على المزيد من الإصلاحات الأمنية أو التحديثات الحرجة. الرجاء "
#~ "الترقية إلى نسخة لاحقة من لينكس أبونتو."

#~ msgid ""
#~ "These software updates have been issued since this version of Ubuntu was "
#~ "released. If you don't want to install them now, choose \"Update Manager"
#~ "\" from Applications later."
#~ msgstr ""
#~ "تحديثات البرمجيات هذه صدرت منذ إطلاق هذا الإصدار من أبونتو. إذا لم تكن "
#~ "ترغب في تثبيتها الآن، يمكنك تثبيتها لاحقًا باختيار \"مدير التحديثات\" من "
#~ "التطبيقات."

#~ msgid ""
#~ "These software updates have been issued since this version of Ubuntu was "
#~ "released. If you don't want to install them now, choose \"Update Manager"
#~ "\" from the Administration Menu later."
#~ msgstr ""
#~ "تحديثات البرمجيات هذه صدرت منذ إطلاق هذا الإصدار من أبونتو. إذا لم تكن "
#~ "ترغب في تثبيتها الآن، يمكنك تثبيتها لاحقًا باختيار \"مدير التحديثات\" من "
#~ "قائمة الإدارة."

#~ msgid ""
#~ "If you don't want to install them now, choose \"Update Manager\" from "
#~ "Applications later."
#~ msgstr ""
#~ "إذا لم تكن ترغب في تثبيتها الآن، يمكنك تثبيتها لاحقًا باختيار \"مدير "
#~ "التحديثات\" من التطبيقات."

#~ msgid ""
#~ "The support in Ubuntu 11.04 for your intel graphics hardware is limited "
#~ "and you may encounter problems after the upgrade. Do you want to continue "
#~ "with the upgrade?"
#~ msgstr ""
#~ "دعم أوبنتو 11.04 لعتاد الرسوميات في جهازك محدود وقد تواجه مشاكل بعد "
#~ "الترقية. هل تود الاستمرار في الترقية؟"

#~ msgid "Your graphics hardware may not be fully supported in Ubuntu 11.04."
#~ msgstr "قد يكون عتاد الرسوميات في جهازك غير مدعوم بالكامل في أوبنتو 11.04."
