# translation of update-manager to Spanish
# This file is distributed under the same license as the update-manager package.
#  Copyright (c) 2004 Canonical
#                2004 Michiel Sikkes
# Jorge Bernal <koke@amedias.org>, 2005.
# Jorge Bernal <koke@sindominio.net>, 2005.
# Paco Molinero <paco@byasl.com>, 2011.
#
msgid ""
msgstr ""
"Project-Id-Version: es\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2012-06-14 00:53+0100\n"
"PO-Revision-Date: 2012-03-20 20:23+0000\n"
"Last-Translator: Fitoschido <fitoschido@gmail.com>\n"
"Language-Team: Spanish <traductores@gnome.org>\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Launchpad-Export-Date: 2012-04-17 13:41+0000\n"
"X-Generator: Launchpad (build 15099)\n"

#. TRANSLATORS: download size of small updates, e.g. "250 kB"
#: ../DistUpgrade/utils.py:433 ../UpdateManager/Core/utils.py:433
#, python-format
msgid "%(size).0f kB"
msgid_plural "%(size).0f kB"
msgstr[0] "%(size).0f kB"
msgstr[1] "%(size).0f kB"

#. TRANSLATORS: download size of updates, e.g. "2.3 MB"
#: ../DistUpgrade/utils.py:436 ../UpdateManager/Core/utils.py:436
#, python-format
msgid "%.1f MB"
msgstr "%.1f MB"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:206 ../DistUpgrade/distro.py:436
#, python-format
msgid "Server for %s"
msgstr "Servidor para %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:224 ../DistUpgrade/distro.py:230
#: ../DistUpgrade/distro.py:246
msgid "Main server"
msgstr "Servidor principal"

#: ../DistUpgrade/distro.py:250
msgid "Custom servers"
msgstr "Servidores personalizados"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:142
msgid "Could not calculate sources.list entry"
msgstr "No se puede calcular la entrada en sources.list"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:251
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr ""
"No se pudo localizar ningún paquete, quizá no es un disco de Ubuntu o no es "
"la arquitectura correcta."

#: ../DistUpgrade/DistUpgradeAptCdrom.py:294
msgid "Failed to add the CD"
msgstr "Error al añadir el CD"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:295
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"Ha habido un error al añadir el CD; se ha interrumpido la actualización. Por "
"favor, informe de esto como un fallo si este es un CD válido de Ubuntu.\n"
"\n"
"El mensaje de error fue:\n"
"«%s»"

#: ../DistUpgrade/DistUpgradeCache.py:151
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "Desinstalar paquete en mal estado"
msgstr[1] "Desinstalar paquetes en mal estado"

#: ../DistUpgrade/DistUpgradeCache.py:154
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"El paquete «%s» está en un estado inconsistente y debe reinstalarse, pero no "
"se encuentra en ningún repositorio. ¿Quiere desinstalar este paquete ahora "
"para continuar?"
msgstr[1] ""
"Los paquetes «%s» están en un estado inconsistente y deben reinstalarse, "
"pero no se encuentran en ningún repositorio. ¿Quiere desinstalar estos "
"paquetes ahora para continuar?"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:255
msgid "The server may be overloaded"
msgstr "El servidor puede estar sobrecargado"

#: ../DistUpgrade/DistUpgradeCache.py:368
msgid "Broken packages"
msgstr "Paquetes rotos"

#: ../DistUpgrade/DistUpgradeCache.py:369
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"Su sistema contiene paquetes rotos que no pueden ser arreglados con este "
"software. Por favor, arréglelos primero usando Synaptic o apt-get antes de "
"continuar."

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:693
#, python-format
msgid ""
"An unresolvable problem occurred while calculating the upgrade:\n"
"%s\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""
"Ha ocurrido un error irresoluble mientras se calculaba la actualización:\n"
"%s\n"
"\n"
" Esto puede deberse a:\n"
" * Que se está actualizando a una versión de Ubuntu aún no publicada\n"
" * Que se está usando la actual versión aún no publicada de Ubuntu\n"
" * Paquetes de software no oficiales, no suministrados por Ubuntu\n"
"\n"

#: ../DistUpgrade/DistUpgradeCache.py:703
msgid "This is most likely a transient problem, please try again later."
msgstr ""
"Probablemente sea un problema transitorio, inténtelo de nuevo más tarde."

#: ../DistUpgrade/DistUpgradeCache.py:706
msgid ""
"If none of this applies, then please report this bug using the command "
"'ubuntu-bug update-manager' in a terminal."
msgstr ""
"Si ninguna de estas aplica, entonces informe de este fallo usando la orden "
"«ubuntu-bug update-manager» en una terminal."

#: ../DistUpgrade/DistUpgradeCache.py:711
#: ../UpdateManager/UpdateManager.py:1031
msgid "Could not calculate the upgrade"
msgstr "No se ha podido calcular la actualización"

#: ../DistUpgrade/DistUpgradeCache.py:762
msgid "Error authenticating some packages"
msgstr "Error al autenticar algunos paquetes"

#: ../DistUpgrade/DistUpgradeCache.py:763
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"No ha sido posible autenticar algunos paquetes. Esto puede ser debido a un "
"problema transitorio en la red. Pruebe de nuevo más tarde. Vea abajo una "
"lista de los paquetes no autenticados."

#: ../DistUpgrade/DistUpgradeCache.py:783
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""
"El paquete «%s» está marcado para desinstalarse pero está en la lista negra "
"de desinstalación."

#: ../DistUpgrade/DistUpgradeCache.py:787
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "El paquete esencial «%s» ha sido marcado para su desinstalación."

#: ../DistUpgrade/DistUpgradeCache.py:796
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr "Intentando instalar la versión prohibida «%s»"

#: ../DistUpgrade/DistUpgradeCache.py:914
#, python-format
msgid "Can't install '%s'"
msgstr "No se ha podido instalar «%s»"

#: ../DistUpgrade/DistUpgradeCache.py:915
msgid ""
"It was impossible to install a required package. Please report this as a bug "
"using 'ubuntu-bug update-manager' in a terminal."
msgstr ""
"Fue imposible instalar el paquete requerido. Informe de este fallo usando "
"«ubuntu-bug update-manager» en una terminal."

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:926
msgid "Can't guess meta-package"
msgstr "No se ha podido determinar el metapaquete"

#: ../DistUpgrade/DistUpgradeCache.py:927
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"Su sistema no contiene el paquete ubuntu-desktop,  kubuntu-desktop, xubuntu-"
"desktop o edubuntu-desktop, y no ha sido posible detectar qué versión de "
"Ubuntu está ejecutando.\n"
" Por favor, instale uno de los paquetes anteriores usando Synaptic o apt-get "
"antes de proceder."

#: ../DistUpgrade/DistUpgradeController.py:114
msgid "Reading cache"
msgstr "Leyendo caché"

#: ../DistUpgrade/DistUpgradeController.py:223
msgid "Unable to get exclusive lock"
msgstr "No se ha podido obtener un bloqueo exclusivo"

#: ../DistUpgrade/DistUpgradeController.py:224
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"Esto normalmente significa que ya se está ejecutando otra aplicación de "
"gestión de paquetes (como apt-get o aptitude). Por favor, cierre esa "
"aplicación primero."

#: ../DistUpgrade/DistUpgradeController.py:257
msgid "Upgrading over remote connection not supported"
msgstr "Actualizando sobre conexión remota no soportada"

#: ../DistUpgrade/DistUpgradeController.py:258
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"Está ejecutando la actualización sobre una conexión ssh remota con una "
"interfaz de usuario que no lo permite. Intente actualizar en modo texto con "
"«do-release-upgrade».\n"
"\n"
"La actualización se detendrá ahora. Intente sin ssh."

#: ../DistUpgrade/DistUpgradeController.py:272
msgid "Continue running under SSH?"
msgstr "¿Continuar la ejecución bajo SSH?"

#: ../DistUpgrade/DistUpgradeController.py:273
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"Esta sesión parece estar ejecutándose bajo ssh. No es recomendable hacer una "
"actualización sobre ssh actualmente, porque en caso de fallo es muy difícil "
"recuperarla.\n"
"\n"
"Si continua, se iniciará un demonio ssh adicional en el puerto «%s».\n"
"¿Quiere continuar?"

#: ../DistUpgrade/DistUpgradeController.py:287
msgid "Starting additional sshd"
msgstr "Iniciando sshd adicional"

#: ../DistUpgrade/DistUpgradeController.py:288
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"Para facilitar la recuperación en caso de fallo, se iniciará un sshd "
"adicional en el puerto «%s». Si algo va mal con el ssh en ejecución, aún "
"podrá conectarse al adicional.\n"

#: ../DistUpgrade/DistUpgradeController.py:296
#, python-format
msgid ""
"If you run a firewall, you may need to temporarily open this port. As this "
"is potentially dangerous it's not done automatically. You can open the port "
"with e.g.:\n"
"'%s'"
msgstr ""
"Si ejecuta un cortafuegos, puede necesitar abrir este puerto temporalmente. "
"Como esto es potencialmente peligroso, no se hace automáticamente. Puede "
"abrir el puerto con:\n"
"«%s»"

#: ../DistUpgrade/DistUpgradeController.py:368
#: ../DistUpgrade/DistUpgradeController.py:413
msgid "Can not upgrade"
msgstr "No se puede actualizar"

#: ../DistUpgrade/DistUpgradeController.py:369
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr "Esta herramienta no permite actualizaciones de «%s» a «%s»."

#: ../DistUpgrade/DistUpgradeController.py:378
msgid "Sandbox setup failed"
msgstr "Falló la configuración de la caja de arena"

#: ../DistUpgrade/DistUpgradeController.py:379
msgid "It was not possible to create the sandbox environment."
msgstr "No ha sido posible crear un entorno de caja de arena."

#: ../DistUpgrade/DistUpgradeController.py:385
msgid "Sandbox mode"
msgstr "Modo caja de arena"

#: ../DistUpgrade/DistUpgradeController.py:386
#, python-format
msgid ""
"This upgrade is running in sandbox (test) mode. All changes are written to "
"'%s' and will be lost on the next reboot.\n"
"\n"
"*No* changes written to a system directory from now until the next reboot "
"are permanent."
msgstr ""
"Esta actualización se esta realizando en el modo (prueba) «sandbox». Todos "
"los cambios se escriben en «%s» y se perderán en el siguiente arranque.\n"
"\n"
"*Ninguno* de los cambios escritos en el directorio de sistema desde ahora "
"hasta el siguiente arranque son permanentes."

#: ../DistUpgrade/DistUpgradeController.py:414
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""
"Su instalación de python está dañada. Por favor, repare el enlace simbólico "
"«/usr/bin/python»."

#: ../DistUpgrade/DistUpgradeController.py:440
msgid "Package 'debsig-verify' is installed"
msgstr "El paquete «debsig-verify» esta instalado"

#: ../DistUpgrade/DistUpgradeController.py:441
msgid ""
"The upgrade can not continue with that package installed.\n"
"Please remove it with synaptic or 'apt-get remove debsig-verify' first and "
"run the upgrade again."
msgstr ""
"La actualización no puede continuar con ese paquete instalado.\n"
"Desinstálelo con synaptic o «apt-get remove debsig-verify» primero y luego "
"intente actualizar nuevamente."

#: ../DistUpgrade/DistUpgradeController.py:453
#, python-format
msgid "Can not write to '%s'"
msgstr "No se puede escribir en «%s»"

#: ../DistUpgrade/DistUpgradeController.py:454
#, python-format
msgid ""
"Its not possible to write to the system directory '%s' on your system. The "
"upgrade can not continue.\n"
"Please make sure that the system directory is writable."
msgstr ""
"No es posible escribir el directorio de sistema «%s» en su sistema. La "
"actualización no puede continuar.\n"
"Asegúrese de que el directorio de sistema permite escribir."

#: ../DistUpgrade/DistUpgradeController.py:465
msgid "Include latest updates from the Internet?"
msgstr "¿Incluir las últimas actualizaciones desde Internet?"

#: ../DistUpgrade/DistUpgradeController.py:466
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""
"El sistema de actualización a una nueva versión puede usar Internet para "
"descargar automáticamente las actualizaciones más recientes e instalarlas "
"durante el proceso. Si dispone de una conexión a la red, esto es muy "
"recomendable.\n"
"\n"
"La actualización llevará más tiempo, pero una vez terminada, el sistema "
"estará completamente actualizado. Puede elegir no hacerlo, pero deberá "
"instalar las nuevas actualizaciones inmediatamente después de pasar a la "
"nueva versión.\n"
"Si responde «no» ahora, la red no se usará para nada."

#: ../DistUpgrade/DistUpgradeController.py:686
#, python-format
msgid "disabled on upgrade to %s"
msgstr "(desactivado en la actualización a %s)"

#: ../DistUpgrade/DistUpgradeController.py:713
msgid "No valid mirror found"
msgstr "No se ha encontrado un servidor espejo válido"

#: ../DistUpgrade/DistUpgradeController.py:714
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""
"Mientras se exploraba la información de su repositorio, no se encontró "
"ninguna entrada para la réplica de la actualización. Esto puede ocurrir si "
"corre una réplica interna o si la información de la réplica es antigua.\n"
"\n"
"¿Quiere reescribir su archivo «sources.list» de todos modos? Si elige «Sí» "
"se actualizarán todas las entradas «%s» a «%s».\n"
"Si selecciona «No» la actualización se cancelará."

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:734
msgid "Generate default sources?"
msgstr "¿Generar orígenes predeterminados?"

#: ../DistUpgrade/DistUpgradeController.py:735
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"Después de explorar su «sources.list» no se encontraron entradas válidas "
"para «%s».\n"
"\n"
"¿Se deben añadir entradas predeterminadas para «%s»? Si selecciona «No», la "
"actualización se cancelará."

#: ../DistUpgrade/DistUpgradeController.py:770
msgid "Repository information invalid"
msgstr "Información de repositorio no válida"

#: ../DistUpgrade/DistUpgradeController.py:771
msgid ""
"Upgrading the repository information resulted in a invalid file so a bug "
"reporting process is being started."
msgstr ""
"La actualización de la información del repositorio dio como resultado un "
"archivo inválido por lo que se está iniciando un proceso de notificación de "
"errores."

#: ../DistUpgrade/DistUpgradeController.py:778
msgid "Third party sources disabled"
msgstr "Desactivados los orígenes de terceros"

#: ../DistUpgrade/DistUpgradeController.py:779
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"Se han desactivado algunas entradas de otros proveedores en su «sources."
"list». Puede volver a activarlas tras la actualización con la herramienta "
"«Orígenes del software», o con su gestor de paquetes."

#: ../DistUpgrade/DistUpgradeController.py:819
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "Paquete en un estado inconsistente"
msgstr[1] "Paquetes en un estado inconsistente"

#: ../DistUpgrade/DistUpgradeController.py:822
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"El paquete «%s» está en un estado inconsistente y debe reinstalarse, pero no "
"se encuentra en ningún repositorio. Por favor, reinstale el paquete "
"manualmente o desinstálelo del sistema."
msgstr[1] ""
"Los paquetes «%s» están en un estado inconsistente y deben reinstalarse, "
"pero no se encuentran en ningún repositorio. Por favor, reinstale los "
"paquetes manualmente o desinstálelos del sistema."

#: ../DistUpgrade/DistUpgradeController.py:870
msgid "Error during update"
msgstr "Error durante la actualización"

#: ../DistUpgrade/DistUpgradeController.py:871
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"Ocurrió un problema durante la actualización. Normalmente es debido a algún "
"tipo de problema en la red, por lo que le recomendamos que compruebe su "
"conexión de red y vuelva a intentarlo."

#. print("on_button_install_clicked")
#: ../DistUpgrade/DistUpgradeController.py:880
#: ../UpdateManager/UpdateManager.py:757
msgid "Not enough free disk space"
msgstr "No hay espacio suficiente en el disco"

#: ../DistUpgrade/DistUpgradeController.py:881
#, python-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of %s free space on disk "
"'%s'. Please free at least an additional %s of disk space on '%s'. Empty "
"your trash and remove temporary packages of former installations using 'sudo "
"apt-get clean'."
msgstr ""
"La actualización se canceló. La actualización necesita un total de %s de "
"espacio libre en el disco «%s». Libere al menos %s de espacio en el disco "
"«%s». Pruebe vaciando su papelera y borrando paquetes temporales de antiguas "
"instalaciones usando la orden «sudo apt-get clean»."

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:910
#: ../DistUpgrade/DistUpgradeController.py:1692
msgid "Calculating the changes"
msgstr "Calculando los cambios"

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:942
msgid "Do you want to start the upgrade?"
msgstr "¿Quiere comenzar la actualización?"

#: ../DistUpgrade/DistUpgradeController.py:1008
msgid "Upgrade canceled"
msgstr "Actualización cancelada"

#: ../DistUpgrade/DistUpgradeController.py:1009
msgid ""
"The upgrade will cancel now and the original system state will be restored. "
"You can resume the upgrade at a later time."
msgstr ""
"La actualización se cancelará ahora y el sistema volverá a su estado "
"original. Puede reanudar la actualización posteriormente."

#: ../DistUpgrade/DistUpgradeController.py:1015
#: ../DistUpgrade/DistUpgradeController.py:1149
msgid "Could not download the upgrades"
msgstr "No se han podido descargar las actualizaciones"

#: ../DistUpgrade/DistUpgradeController.py:1016
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far have been kept."
msgstr ""
"La actualización se ha anulado. Compruebe su conexión a Internet o los "
"medios de instalación y vuelva a intentarlo. Todos los archivos descargados "
"hasta el momento se han mantenido."

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1100
#: ../DistUpgrade/DistUpgradeController.py:1137
#: ../DistUpgrade/DistUpgradeController.py:1242
msgid "Error during commit"
msgstr "Error durante la confirmación"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1102
#: ../DistUpgrade/DistUpgradeController.py:1139
#: ../DistUpgrade/DistUpgradeController.py:1281
msgid "Restoring original system state"
msgstr "Restaurando el estado original del sistema"

#: ../DistUpgrade/DistUpgradeController.py:1103
#: ../DistUpgrade/DistUpgradeController.py:1118
#: ../DistUpgrade/DistUpgradeController.py:1140
msgid "Could not install the upgrades"
msgstr "No se han podido instalar las actualizaciones"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1108
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"La actualización ha sido cancelada. Su sistema podría haber quedado en un "
"estado no utilizable. Ahora se llevará a cabo una recuperación (dpkg --"
"configure -a)."

#: ../DistUpgrade/DistUpgradeController.py:1113
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug in a browser at http://bugs.launchpad.net/ubuntu/"
"+source/update-manager/+filebug and attach the files in /var/log/dist-"
"upgrade/ to the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"Informe de este error en un navegador en http://bugs.launchpad.net/ubuntu/"
"+source/update-manager/+filebug y adjunte los archivos en /var/log/dist-"
"upgrade al informe de error.\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1150
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""
"La actualización ha sido cancelada. Por favor, compruebe su conexión a "
"Internet o el soporte de instalación y vuelva a intentarlo. "

#: ../DistUpgrade/DistUpgradeController.py:1230
msgid "Remove obsolete packages?"
msgstr "¿Desinstalar los paquetes obsoletos?"

#: ../DistUpgrade/DistUpgradeController.py:1231
#: ../DistUpgrade/DistUpgrade.ui.h:8
msgid "_Keep"
msgstr "_Conservar"

#: ../DistUpgrade/DistUpgradeController.py:1231
msgid "_Remove"
msgstr "_Eliminar"

#: ../DistUpgrade/DistUpgradeController.py:1243
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr ""
"Ha ocurrido algún problema durante el limpiado. Por favor, lea el mensaje "
"siguiente para más información. "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1319
msgid "Required depends is not installed"
msgstr "La dependencia requerida no está instalada"

#: ../DistUpgrade/DistUpgradeController.py:1320
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "La dependencia requerida «%s» no está instalada. "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1588
#: ../DistUpgrade/DistUpgradeController.py:1653
msgid "Checking package manager"
msgstr "Comprobando el gestor de paquetes"

#: ../DistUpgrade/DistUpgradeController.py:1593
msgid "Preparing the upgrade failed"
msgstr "Falló la preparación de la actualización"

#: ../DistUpgrade/DistUpgradeController.py:1594
msgid ""
"Preparing the system for the upgrade failed so a bug reporting process is "
"being started."
msgstr ""
"Falló la preparación del sistema para actualizarse, de manera que se ha "
"iniciado el proceso de informe de errores."

#: ../DistUpgrade/DistUpgradeController.py:1608
msgid "Getting upgrade prerequisites failed"
msgstr "Ha fallado la obtención de los requisitos previos de la actualización"

#: ../DistUpgrade/DistUpgradeController.py:1609
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Additionally, a bug reporting process is being started."
msgstr ""
"El sistema fue incapaz de obtener los requisitos previos para la "
"actualización. La actualización se interrumpirá ahora y se restaurará el "
"estado original del sistema.\n"
"\n"
"Adicionalmente, se está iniciando un proceso de notificación de errores."

#: ../DistUpgrade/DistUpgradeController.py:1637
msgid "Updating repository information"
msgstr "Actualizando la información del repositorio"

#: ../DistUpgrade/DistUpgradeController.py:1644
msgid "Failed to add the cdrom"
msgstr "Fallo al añadir el CDROM"

#: ../DistUpgrade/DistUpgradeController.py:1645
msgid "Sorry, adding the cdrom was not successful."
msgstr "Lo sentimos, no se pudo añadir el CDROM"

#: ../DistUpgrade/DistUpgradeController.py:1673
msgid "Invalid package information"
msgstr "Información sobre los paquetes no válida"

#: ../DistUpgrade/DistUpgradeController.py:1674
msgid "After updating your package "
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1698
#: ../DistUpgrade/DistUpgradeController.py:1750
msgid "Fetching"
msgstr "Descargando"

#: ../DistUpgrade/DistUpgradeController.py:1704
#: ../DistUpgrade/DistUpgradeController.py:1754
msgid "Upgrading"
msgstr "Actualizando"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1709
#: ../DistUpgrade/DistUpgradeController.py:1756
#: ../DistUpgrade/DistUpgradeController.py:1763
#: ../DistUpgrade/DistUpgradeController.py:1774
msgid "Upgrade complete"
msgstr "Actualización completada"

#: ../DistUpgrade/DistUpgradeController.py:1710
#: ../DistUpgrade/DistUpgradeController.py:1757
#: ../DistUpgrade/DistUpgradeController.py:1764
msgid ""
"The upgrade has completed but there were errors during the upgrade process."
msgstr "La actualización se completó pero hubo errores durante el proceso."

#: ../DistUpgrade/DistUpgradeController.py:1717
msgid "Searching for obsolete software"
msgstr "Buscando paquetes obsoletos"

#: ../DistUpgrade/DistUpgradeController.py:1726
msgid "System upgrade is complete."
msgstr "La actualización del sistema se ha completado."

#: ../DistUpgrade/DistUpgradeController.py:1775
msgid "The partial upgrade was completed."
msgstr "La actualización parcial se ha completado."

#: ../DistUpgrade/DistUpgradeQuirks.py:204
msgid "evms in use"
msgstr "Se está usando «evms»"

#: ../DistUpgrade/DistUpgradeQuirks.py:205
msgid ""
"Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
"software is no longer supported, please switch it off and run the upgrade "
"again when this is done."
msgstr ""
"Su sistema está usando el gestor de volúmenes «evms» en /proc/mounts. El "
"software «evms» ya no está soportado; por favor, desactívelo y vuelva a "
"ejecutar de nuevo la actualización."

#: ../DistUpgrade/DistUpgradeQuirks.py:502
msgid "Your graphics hardware may not be fully supported in Ubuntu 12.04 LTS."
msgstr ""
"Su hardware de gráficos no es plenamente compatible con Ubuntu 12.04 LTS."

#: ../DistUpgrade/DistUpgradeQuirks.py:504
msgid ""
"The support in Ubuntu 12.04 LTS for your Intel graphics hardware is limited "
"and you may encounter problems after the upgrade. For more information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx Do you want to "
"continue with the upgrade?"
msgstr ""
"La compatibilidad en Ubuntu 12.04 LTS para su hardware de gráficos Intel "
"está limitada y puede encontrar problemas tras la actualización. Para tener "
"más información vea https://wiki.ubuntu.com/X/Bugs/"
"UpdateManagerWarningForI8xx ¿Quiere continuar con la actualización?"

#: ../DistUpgrade/DistUpgradeQuirks.py:526
#: ../DistUpgrade/DistUpgradeQuirks.py:554
#: ../DistUpgrade/DistUpgradeQuirks.py:581
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"La actualización puede reducir los efectos de escritorio, así como el "
"rendimiento de los juegos y otros programas que usen gráficos de forma "
"intensiva."

#: ../DistUpgrade/DistUpgradeQuirks.py:530
#: ../DistUpgrade/DistUpgradeQuirks.py:558
msgid ""
"This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
"version of this driver is available that works with your video card in "
"Ubuntu 10.04 LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"Este equipo está usando el controlador gráfico  «nvidia» de NVIDIA. No se "
"encuentra disponible en Ubuntu 10.04 LTS una versión de este controlador que "
"funcione con su hardware.\n"
"\n"
"¿Quiere continuar?"

#: ../DistUpgrade/DistUpgradeQuirks.py:585
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"Este equipo está usando el controlador gráfico  «fglrx» de AMD. No se "
"encuentra disponible en Ubuntu 10.04 LTS una versión de este controlador que "
"funcione con su hardware.\n"
"\n"
"¿Quiere continuar?"

#: ../DistUpgrade/DistUpgradeQuirks.py:615
msgid "No i686 CPU"
msgstr "Sin CPU i686"

#: ../DistUpgrade/DistUpgradeQuirks.py:616
msgid ""
"Your system uses an i586 CPU or a CPU that does not have the 'cmov' "
"extension. All packages were built with optimizations requiring i686 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"Su sistema usa una CPU i586 CPU o  una CPU que no tiene la extensión «cmov». "
"Todos los paquetes se han construido con optimizaciones que requieren i686 "
"como arquitectura mínima. No es posible actualizar su sistema a la nueva "
"versión de Ubuntu con este hardware."

#: ../DistUpgrade/DistUpgradeQuirks.py:652
msgid "No ARMv6 CPU"
msgstr "No hay CPU ARMv6"

#: ../DistUpgrade/DistUpgradeQuirks.py:653
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"Su sistema usa una CPU ARM que es más antigua que la arquitectura ARMv6. "
"Todos los paquetes en karmic han sido construidos con optimizaciones que "
"requieren ARMv6 como arquitectura mínima. No es posible actualizar sus "
"sistema a la nueva versión de Ubuntu con este hardware."

#: ../DistUpgrade/DistUpgradeQuirks.py:673
msgid "No init available"
msgstr "El demonio init no está disponible"

#: ../DistUpgrade/DistUpgradeQuirks.py:674
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"Parece que su sistema es un entorno virtualizado sin un demonio init (un "
"Linux-VServer, p.ej.). Ubuntu 10.04 LTS no puede funcionar en este tipo de "
"entorno, por lo que primero se requiere una actualización de la "
"configuración de su máquina virtual.\n"
"\n"
"¿Está seguro de que quiere continuar?"

#: ../DistUpgrade/DistUpgradeMain.py:65
msgid "Sandbox upgrade using aufs"
msgstr "Actualización de prueba usando aufs"

#: ../DistUpgrade/DistUpgradeMain.py:67
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr "Usar la ruta dada para buscar un CD-ROM con paquetes actualizables"

#: ../DistUpgrade/DistUpgradeMain.py:73
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"Usar interfaz de usuario. Actualmente disponibles: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:76
msgid "*DEPRECATED* this option will be ignored"
msgstr "*OBSOLETO* esta opción se ignorará"

#: ../DistUpgrade/DistUpgradeMain.py:79
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr ""
"Realizar solo una actualización parcial (no se reescribirá el «sources.list»)"

#: ../DistUpgrade/DistUpgradeMain.py:82
msgid "Disable GNU screen support"
msgstr "Desactive el soporte de pantalla GNU"

#: ../DistUpgrade/DistUpgradeMain.py:84
msgid "Set datadir"
msgstr "Establecer datadir"

#. print("mediaChange %s %s" % (medium, drive))
#: ../DistUpgrade/DistUpgradeViewGtk.py:114
#: ../DistUpgrade/DistUpgradeViewGtk3.py:117
#: ../DistUpgrade/DistUpgradeViewKDE.py:195
#: ../UpdateManager/DistUpgradeFetcherKDE.py:155
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "Inserte «%s» en la unidad «%s»"

#: ../DistUpgrade/DistUpgradeViewGtk.py:135
#: ../DistUpgrade/DistUpgradeViewGtk3.py:138
#: ../DistUpgrade/DistUpgradeViewKDE.py:209
msgid "Fetching is complete"
msgstr "La descarga se ha completado"

#: ../DistUpgrade/DistUpgradeViewGtk.py:146
#: ../DistUpgrade/DistUpgradeViewGtk3.py:149
#: ../DistUpgrade/DistUpgradeViewKDE.py:222
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "Descargando archivo %li de %li a %sB/s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:149
#: ../DistUpgrade/DistUpgradeViewGtk.py:296
#: ../DistUpgrade/DistUpgradeViewGtk3.py:152
#: ../DistUpgrade/DistUpgradeViewGtk3.py:309
#: ../DistUpgrade/DistUpgradeViewKDE.py:223
#: ../DistUpgrade/DistUpgradeViewKDE.py:371
#, python-format
msgid "About %s remaining"
msgstr "Faltan alrededor de %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:152
#: ../DistUpgrade/DistUpgradeViewGtk3.py:155
#: ../DistUpgrade/DistUpgradeViewKDE.py:225
#, python-format
msgid "Fetching file %li of %li"
msgstr "Descargando archivo %li de %li"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:183
#: ../DistUpgrade/DistUpgradeViewGtk3.py:186
#: ../DistUpgrade/DistUpgradeViewKDE.py:262
msgid "Applying changes"
msgstr "Aplicando los cambios"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk.py:208
#: ../DistUpgrade/DistUpgradeViewGtk3.py:212
#: ../DistUpgrade/DistUpgradeViewKDE.py:275
msgid "dependency problems - leaving unconfigured"
msgstr "problemas de dependencias - se deja sin configurar"

#: ../DistUpgrade/DistUpgradeViewGtk.py:213
#: ../DistUpgrade/DistUpgradeViewGtk3.py:217
#: ../DistUpgrade/DistUpgradeViewKDE.py:277
#, python-format
msgid "Could not install '%s'"
msgstr "No se ha podido instalar «%s»"

#: ../DistUpgrade/DistUpgradeViewGtk.py:214
#: ../DistUpgrade/DistUpgradeViewGtk3.py:218
#: ../DistUpgrade/DistUpgradeViewKDE.py:278
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""
"La actualización continuará, pero es posible que el paquete «%s» no se "
"encuentre en un estado funcional. Considere la posibilidad de enviar un "
"informe de error acerca de esto."

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:231
#: ../DistUpgrade/DistUpgradeViewGtk3.py:235
#: ../DistUpgrade/DistUpgradeViewKDE.py:299
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"¿Quiere sustituir el archivo de configuración modificado\n"
"«%s»?"

#: ../DistUpgrade/DistUpgradeViewGtk.py:232
#: ../DistUpgrade/DistUpgradeViewGtk3.py:236
#: ../DistUpgrade/DistUpgradeViewKDE.py:300
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"Perderá todos los cambios que haya realizado en este archivo de "
"configuración si decide sustituirlo por una nueva versión."

#: ../DistUpgrade/DistUpgradeViewGtk.py:251
#: ../DistUpgrade/DistUpgradeViewGtk3.py:256
#: ../DistUpgrade/DistUpgradeViewKDE.py:323
msgid "The 'diff' command was not found"
msgstr "No se ha encontrado la orden «diff»"

#: ../DistUpgrade/DistUpgradeViewGtk.py:464
#: ../DistUpgrade/DistUpgradeViewGtk3.py:477
#: ../DistUpgrade/DistUpgradeViewText.py:92
msgid "A fatal error occurred"
msgstr "Ha ocurrido un error fatal"

#: ../DistUpgrade/DistUpgradeViewGtk.py:465
#: ../DistUpgrade/DistUpgradeViewGtk3.py:478
msgid ""
"Please report this as a bug (if you haven't already) and include the files /"
"var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Informe de este fallo (si todavía no lo ha hecho) e incluya los archivos /"
"var/log/dist-upgrade/main.log y /var/log/dist-upgrade/apt.log en el informe. "
"La actualización ha sido cancelada.\n"
"Su archivo sources.list original se guardó en /etc/apt/sources.list."
"distUpgrade."

#: ../DistUpgrade/DistUpgradeViewGtk.py:482
#: ../DistUpgrade/DistUpgradeViewGtk3.py:495
msgid "Ctrl-c pressed"
msgstr "Se ha pulsado Ctrl-C"

#: ../DistUpgrade/DistUpgradeViewGtk.py:483
#: ../DistUpgrade/DistUpgradeViewGtk3.py:496
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"Esto cancelará la operación y puede dejar al sistema en un estado "
"defectuoso. ¿Seguro que desea hacer eso?"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:631
#: ../DistUpgrade/DistUpgradeViewGtk3.py:629
msgid "To prevent data loss close all open applications and documents."
msgstr ""
"Para prevenir la pérdida de datos, cierre todas las aplicaciones y "
"documentos."

#: ../DistUpgrade/DistUpgradeViewGtk.py:645
#: ../DistUpgrade/DistUpgradeViewGtk3.py:643
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr "Ya no está soportado por Canonical (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:646
#: ../DistUpgrade/DistUpgradeViewGtk3.py:644
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr "<b>Desactualizar (%s)</b>"

#: ../DistUpgrade/DistUpgradeViewGtk.py:647
#: ../DistUpgrade/DistUpgradeViewGtk3.py:645
#, python-format
msgid "Remove (%s)"
msgstr "Eliminar (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:648
#: ../DistUpgrade/DistUpgradeViewGtk3.py:646
#, python-format
msgid "No longer needed (%s)"
msgstr "Ya no es necesario (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:649
#: ../DistUpgrade/DistUpgradeViewGtk3.py:647
#, python-format
msgid "Install (%s)"
msgstr "Instalar (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:650
#: ../DistUpgrade/DistUpgradeViewGtk3.py:648
#, python-format
msgid "Upgrade (%s)"
msgstr "Actualizar (%s)"

#. change = QMessageBox.question(None, _("Media Change"), msg, QMessageBox.Ok, QMessageBox.Cancel)
#: ../DistUpgrade/DistUpgradeViewKDE.py:196
#: ../UpdateManager/DistUpgradeFetcherKDE.py:157
msgid "Media Change"
msgstr "Cambio de soporte"

#: ../DistUpgrade/DistUpgradeViewKDE.py:335
msgid "Show Difference >>>"
msgstr "Mostrar diferencias >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:338
msgid "<<< Hide Difference"
msgstr "<<< Ocultar diferencias"

#: ../DistUpgrade/DistUpgradeViewKDE.py:554
msgid "Error"
msgstr "Error"

#: ../DistUpgrade/DistUpgradeViewKDE.py:568
msgid "&Cancel"
msgstr "&Cancelar"

#: ../DistUpgrade/DistUpgradeViewKDE.py:572
#: ../DistUpgrade/DistUpgradeViewKDE.py:813
msgid "&Close"
msgstr "&Cerrar"

#: ../DistUpgrade/DistUpgradeViewKDE.py:618
msgid "Show Terminal >>>"
msgstr "Mostrar terminal >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:621
msgid "<<< Hide Terminal"
msgstr "<<< Ocultar terminal"

#: ../DistUpgrade/DistUpgradeViewKDE.py:701
msgid "Information"
msgstr "Información"

#: ../DistUpgrade/DistUpgradeViewKDE.py:751
#: ../DistUpgrade/DistUpgradeViewKDE.py:796
#: ../DistUpgrade/DistUpgradeViewKDE.py:799 ../DistUpgrade/DistUpgrade.ui.h:7
msgid "Details"
msgstr "Detalles"

#: ../DistUpgrade/DistUpgradeViewKDE.py:777
#, python-format
msgid "No longer supported %s"
msgstr "Ya no está soportado %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:779
#, python-format
msgid "Remove %s"
msgstr "Eliminar %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:781
#: ../DistUpgrade/DistUpgradeViewText.py:182
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "Eliminar (fue autoinstalado) %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:783
#, python-format
msgid "Install %s"
msgstr "Instalar %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:785
#, python-format
msgid "Upgrade %s"
msgstr "Actualizar %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:809
#: ../DistUpgrade/DistUpgradeViewText.py:230
msgid "Restart required"
msgstr "Se requiere reiniciar"

#: ../DistUpgrade/DistUpgradeViewKDE.py:809
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr "<b><big>Reinicie el sistema para completar la actualización</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:812 ../DistUpgrade/DistUpgrade.ui.h:14
#: ../data/gtkbuilder/UpdateManager.ui.h:26
msgid "_Restart Now"
msgstr "_Reiniciar ahora"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:830
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>¿Cancelar la actualización en curso?</big></b>\n"
"\n"
"El sistema podría quedar en un estado no utilizable si cancela la "
"actualización. Le recomendamos encarecidamente que continúe la actualización."

#: ../DistUpgrade/DistUpgradeViewKDE.py:834
msgid "Cancel Upgrade?"
msgstr "¿Cancelar la actualización?"

#: ../DistUpgrade/DistUpgradeView.py:61
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li día"
msgstr[1] "%li días"

#: ../DistUpgrade/DistUpgradeView.py:63
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li hora"
msgstr[1] "%li horas"

#: ../DistUpgrade/DistUpgradeView.py:65
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li minuto"
msgstr[1] "%li minutos"

#: ../DistUpgrade/DistUpgradeView.py:66
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li segundo"
msgstr[1] "%li segundos"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:82
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:100
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:151
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""
"Esta descarga tardará %s aproximadamente con una conexión DSL de 1Mbit y %s "
"aproximadamente con un módem de 56k."

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:155
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "Esta descarga tardará aproximadamente %s con su conexión actual. "

#. Declare these translatable strings from the .ui files here so that
#. xgettext picks them up.
#: ../DistUpgrade/DistUpgradeView.py:259 ../DistUpgrade/DistUpgrade.ui.h:21
msgid "Preparing to upgrade"
msgstr "Preparando la actualización"

#: ../DistUpgrade/DistUpgradeView.py:260
msgid "Getting new software channels"
msgstr "Obteniendo nuevos canales de software"

#: ../DistUpgrade/DistUpgradeView.py:261 ../DistUpgrade/DistUpgrade.ui.h:23
msgid "Getting new packages"
msgstr "Obteniendo paquetes nuevos"

#: ../DistUpgrade/DistUpgradeView.py:262 ../DistUpgrade/DistUpgrade.ui.h:26
msgid "Installing the upgrades"
msgstr "Instalando las actualizaciones"

#: ../DistUpgrade/DistUpgradeView.py:263 ../DistUpgrade/DistUpgrade.ui.h:25
msgid "Cleaning up"
msgstr "Limpiando"

#: ../DistUpgrade/DistUpgradeView.py:348
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
"%(amount)d paquete instalado ya no está soportado por Canonical. Puede "
"seguir obteniendo soporte de la comunidad."
msgstr[1] ""
"%(amount)d paquetes instalados ya no están soportados por Canonical. Puede "
"seguir obteniendo soporte de la comunidad."

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:357
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "Se va a desinstalar %d paquete."
msgstr[1] "Se van a desinstalar %d paquetes."

#: ../DistUpgrade/DistUpgradeView.py:362
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "Se va a instalar %d paquete nuevo."
msgstr[1] "Se van a instalar %d paquetes nuevos."

#: ../DistUpgrade/DistUpgradeView.py:368
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "Se va a actualizar %d paquete."
msgstr[1] "Se van a actualizar %d paquetes."

#: ../DistUpgrade/DistUpgradeView.py:373
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"Debe descargar un total de %s. "

#: ../DistUpgrade/DistUpgradeView.py:378
msgid ""
"Installing the upgrade can take several hours. Once the download has "
"finished, the process cannot be canceled."
msgstr ""
"Esta actualización puede tardar varias horas. Una vez finalice la descarga, "
"el proceso no podrá ser cancelado."

#: ../DistUpgrade/DistUpgradeView.py:382
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be canceled."
msgstr ""
"Recoger e instalar la actualización puede llevar varias horas. Una vez que "
"la descarga haya terminado, el proceso no se puede cancelar."

#: ../DistUpgrade/DistUpgradeView.py:387
msgid "Removing the packages can take several hours. "
msgstr "La desinstalación de los paquetes puede tardar varias horas. "

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:392 ../UpdateManager/UpdateManager.py:676
msgid "The software on this computer is up to date."
msgstr "El software de este equipo está actualizado."

#: ../DistUpgrade/DistUpgradeView.py:393
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"No hay actualizaciones disponibles para su sistema. Se ha cancelado la "
"actualización."

#: ../DistUpgrade/DistUpgradeView.py:406
msgid "Reboot required"
msgstr "Se requiere reiniciar el equipo"

#: ../DistUpgrade/DistUpgradeView.py:407
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"La actualización ha finalizado y se necesita reiniciar el equipo. ¿Quiere "
"hacerlo ahora?"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:72
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:72
#, python-format
msgid "authenticate '%(file)s' against '%(signature)s' "
msgstr "autentificar «%(file)s» contra «%(signature)s» "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:131
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:131
#, python-format
msgid "extracting '%s'"
msgstr "extrayendo «%s»"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:151
#: ../DistUpgrade/DistUpgradeFetcherCore.py:152
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:151
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:152
msgid "Could not run the upgrade tool"
msgstr "No se ha podido ejecutar la herramienta de actualización"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:152
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:152
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug "
"using the command 'ubuntu-bug update-manager'."
msgstr ""
"Esto parece ser un fallo en la herramienta de actualización. Informe de este "
"fallo usando la orden «ubuntu-bug update-manager»."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:227
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:227
msgid "Upgrade tool signature"
msgstr "Firma de la herramienta de actualización"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:234
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:234
msgid "Upgrade tool"
msgstr "Herramienta de actualización"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:268
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:268
msgid "Failed to fetch"
msgstr "Error al descargar"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:269
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:269
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""
"Ha fallado la descarga de la actualización. Puede haber un problema con la "
"red. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:273
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:273
msgid "Authentication failed"
msgstr "Error de autenticación"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:274
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:274
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"Ha fallado la autenticación de la actualización. Es posible que exista un "
"problema con la red o el servidor. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:279
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:279
msgid "Failed to extract"
msgstr "Error al extraer"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:280
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:280
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"Ha fallado la extracción de la actualización. Puede haber un problema con la "
"red o el servidor. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:285
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:285
msgid "Verification failed"
msgstr "Falló la verificación"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:286
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:286
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"Ha fallado la verificación de la actualización. Puede haber un problema con "
"la red o con el servidor. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:300
#: ../DistUpgrade/DistUpgradeFetcherCore.py:306
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:300
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:306
msgid "Can not run the upgrade"
msgstr "No se ha podido ejecutar la actualización"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:301
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:301
msgid ""
"This usually is caused by a system where /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"Esto normalmente está causado por un sistema donde /tmp se ha montado como "
"no ejecutable. Vuelva a montarlo sin «noexec» y ejecute de nuevo la "
"actualización."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:307
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:307
#, python-format
msgid "The error message is '%s'."
msgstr "El mensaje de error es «%s»"

#: ../DistUpgrade/DistUpgradeViewText.py:93
msgid ""
"Please report this as a bug and include the files /var/log/dist-upgrade/main."
"log and /var/log/dist-upgrade/apt.log in your report. The upgrade has "
"aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Informe de este fallo e incluya los archivos /var/log/dist-upgrade/main.log "
"y /var/log/dist-upgrade/apt.log en el informe. La actualización ha sido "
"cancelada.\n"
"Su archivo sources.list original se guardó en /etc/apt/sources.list."
"distUpgrade."

#: ../DistUpgrade/DistUpgradeViewText.py:117
msgid "Aborting"
msgstr "Cancelando"

#: ../DistUpgrade/DistUpgradeViewText.py:122
msgid "Demoted:\n"
msgstr "Para quitar:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:129
msgid "To continue please press [ENTER]"
msgstr "Para continuar, pulse Intro"

#: ../DistUpgrade/DistUpgradeViewText.py:157
#: ../DistUpgrade/DistUpgradeViewText.py:196
#: ../DistUpgrade/DistUpgradeViewText.py:203
msgid "Continue [yN] "
msgstr "Continuar [sN] "

#: ../DistUpgrade/DistUpgradeViewText.py:157
#: ../DistUpgrade/DistUpgradeViewText.py:196
msgid "Details [d]"
msgstr "Detalles [d]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:162
#: ../DistUpgrade/DistUpgradeViewText.py:206
msgid "y"
msgstr "s"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:165
#: ../DistUpgrade/DistUpgradeViewText.py:213
msgid "n"
msgstr "n"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:168
msgid "d"
msgstr "d"

#: ../DistUpgrade/DistUpgradeViewText.py:173
#, python-format
msgid "No longer supported: %s\n"
msgstr "Ya no está soportado: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:178
#, python-format
msgid "Remove: %s\n"
msgstr "Desinstalar: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:188
#, python-format
msgid "Install: %s\n"
msgstr "Instalar: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:193
#, python-format
msgid "Upgrade: %s\n"
msgstr "Actualizar: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:210
msgid "Continue [Yn] "
msgstr "Continuar [Sn] "

#: ../DistUpgrade/DistUpgradeViewText.py:231
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"Para finalizar la actualización se necesita reiniciar.\n"
"Si selecciona «s» el sistema reiniciará."

#: ../DistUpgrade/DistUpgrade.ui.h:1
msgid "_Cancel Upgrade"
msgstr "_Cancelar la actualización"

#: ../DistUpgrade/DistUpgrade.ui.h:2
msgid "_Resume Upgrade"
msgstr "_Continuar la actualización"

#: ../DistUpgrade/DistUpgrade.ui.h:3
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>¿Cancelar la actualización en curso?</big></b>\n"
"\n"
"El sistema podría quedar en un estado no utilizable si cancela la "
"actualización. Le recomendamos encarecidamente que continúe la actualización."

#: ../DistUpgrade/DistUpgrade.ui.h:6
msgid "_Start Upgrade"
msgstr "_Iniciar la actualización"

#: ../DistUpgrade/DistUpgrade.ui.h:9
msgid "_Replace"
msgstr "_Sustituir"

#: ../DistUpgrade/DistUpgrade.ui.h:10
msgid "Difference between the files"
msgstr "Diferencia entre los archivos"

#: ../DistUpgrade/DistUpgrade.ui.h:11
msgid "_Report Bug"
msgstr "_Informar de un error"

#: ../DistUpgrade/DistUpgrade.ui.h:12
msgid "_Continue"
msgstr "_Continuar"

#: ../DistUpgrade/DistUpgrade.ui.h:13
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>¿Comenzar la actualización?</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:15
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>Reinicie el sistema para completar la actualización</big></b>\n"
"\n"
"Por favor, guarde su trabajo antes de continuar."

#: ../DistUpgrade/DistUpgrade.ui.h:18
msgid "Distribution Upgrade"
msgstr "Actualización completa de la distribución"

#: ../DistUpgrade/DistUpgrade.ui.h:19
#, fuzzy
msgid "<b><big>Upgrading Ubuntu to version 12.10</big></b>"
msgstr "<b><big>Actualizar Ubuntu a la versión 11.10</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:20
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.ui.h:22
msgid "Setting new software channels"
msgstr "Configurando nuevos canales de software"

#: ../DistUpgrade/DistUpgrade.ui.h:24
msgid "Restarting the computer"
msgstr "Reiniciando el equipo"

#: ../DistUpgrade/DistUpgrade.ui.h:27
msgid "Terminal"
msgstr "Terminal"

#: ../UpdateManager/backend/InstallBackendSynaptic.py:64
msgid "Please wait, this can take some time."
msgstr "Por favor, espere; esto puede tardar un poco."

#: ../UpdateManager/backend/InstallBackendSynaptic.py:66
msgid "Update is complete"
msgstr "La actualización se ha completado"

#: ../UpdateManager/DistUpgradeFetcher.py:114
#: ../UpdateManager/DistUpgradeFetcherKDE.py:109
msgid "Could not find the release notes"
msgstr "No se han podido encontrar las notas de publicación"

#: ../UpdateManager/DistUpgradeFetcher.py:115
#: ../UpdateManager/DistUpgradeFetcherKDE.py:110
msgid "The server may be overloaded. "
msgstr "Puede que el servidor esté sobrecargado. "

#: ../UpdateManager/DistUpgradeFetcher.py:125
#: ../UpdateManager/DistUpgradeFetcherKDE.py:114
msgid "Could not download the release notes"
msgstr "No se han podido descargar las notas de publicación"

#: ../UpdateManager/DistUpgradeFetcher.py:126
#: ../UpdateManager/DistUpgradeFetcherKDE.py:115
msgid "Please check your internet connection."
msgstr "Por favor, compruebe su conexión a Internet."

#: ../UpdateManager/DistUpgradeFetcherKDE.py:68
#: ../UpdateManager/DistUpgradeFetcherKDE.py:91
msgid "Upgrade"
msgstr "Actualizar"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:95
#: ../data/gtkbuilder/UpdateManager.ui.h:20
#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:2
msgid "Release Notes"
msgstr "Notas de la versión"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:134
#: ../UpdateManager/DistUpgradeFetcherKDE.py:148
#: ../UpdateManager/DistUpgradeFetcherKDE.py:150
msgid "Downloading additional package files..."
msgstr "Descargando archivos de paquetes adicionales..."

#: ../UpdateManager/DistUpgradeFetcherKDE.py:148
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "Archivo %s de %s a %sB/s"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:150
#, python-format
msgid "File %s of %s"
msgstr "Archivo %s de %s"

#: ../UpdateManager/ChangelogViewer.py:75
msgid "Open Link in Browser"
msgstr "Abrir vínculo en el navegador"

#: ../UpdateManager/ChangelogViewer.py:78
msgid "Copy Link to Clipboard"
msgstr "Copiar vínculo en el portapapeles"

#: ../UpdateManager/GtkProgress.py:162
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "Descargando archivo %(current)li de %(total)li a %(speed)s/s"

#: ../UpdateManager/GtkProgress.py:167
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "Descargando archivo %(current)li de %(total)li"

#: ../UpdateManager/UpdateManager.py:106 ../do-release-upgrade:100
msgid "Your Ubuntu release is not supported anymore."
msgstr "Su versión de Ubuntu ya no tiene soporte."

#: ../UpdateManager/UpdateManager.py:107
msgid ""
"You will not get any further security fixes or critical updates. Please "
"upgrade to a later version of Ubuntu."
msgstr ""
"No recibirá más correcciones de seguridad o actualizaciones críticas. "
"Actualice a una versión posterior de Ubuntu."

#: ../UpdateManager/UpdateManager.py:115
msgid "Upgrade information"
msgstr "Información de actualización"

#: ../UpdateManager/UpdateManager.py:233
#: ../UpdateManagerText/UpdateManagerText.py:35
msgid "Install"
msgstr "Instalar"

#: ../UpdateManager/UpdateManager.py:235
msgid "Name"
msgstr "Nombre"

#. upload_archive = version_match.group(2).strip()
#: ../UpdateManager/UpdateManager.py:395
#, python-format
msgid "Version %s: \n"
msgstr "Versión %s: \n"

#: ../UpdateManager/UpdateManager.py:453
msgid ""
"No network connection detected, you can not download changelog information."
msgstr ""
"No se han detectado conexiones de red, no puede descargar la información del "
"registro de cambios."

#: ../UpdateManager/UpdateManager.py:463
msgid "Downloading list of changes..."
msgstr "Descargando la lista de cambios..."

#: ../UpdateManager/UpdateManager.py:507
msgid "_Deselect All"
msgstr "_Deseleccionar todo"

#: ../UpdateManager/UpdateManager.py:513
msgid "Select _All"
msgstr "Seleccionar _todo"

#: ../UpdateManager/UpdateManager.py:572
#, python-format
msgid "%s will be downloaded."
msgstr "Se descargarán %s."

#: ../UpdateManager/UpdateManager.py:584
#, fuzzy
msgid "The update has already been downloaded."
msgid_plural "The updates have already been downloaded."
msgstr[0] "La actualización ya ha sido descargada, pero no instalada."
msgstr[1] "Las actualizaciones ya han sido descargadas, pero no instaladas."

#: ../UpdateManager/UpdateManager.py:589
msgid "There are no updates to install."
msgstr "No hay actualizaciones para instalar."

#: ../UpdateManager/UpdateManager.py:598
msgid "Unknown download size."
msgstr "Tamaño de la descarga desconocido."

#: ../UpdateManager/UpdateManager.py:624
msgid ""
"It is unknown when the package information was updated last. Please click "
"the 'Check' button to update the information."
msgstr ""
"No se sabe cuando se ha actualizado por última vez la información del "
"paquete. Pulse el botón «Comprobar» para actualizar la información."

#: ../UpdateManager/UpdateManager.py:630
#, python-format
msgid ""
"The package information was last updated %(days_ago)s days ago.\n"
"Press the 'Check' button below to check for new software updates."
msgstr ""
"La información de los paquetes ha sido actualizada por última vez hace "
"%(days_ago)s días.\n"
"Pulse el botón «Comprobar» más abajo para buscar nuevas actualizaciones de "
"software."

#: ../UpdateManager/UpdateManager.py:635
#, python-format
msgid "The package information was last updated %(days_ago)s day ago."
msgid_plural "The package information was last updated %(days_ago)s days ago."
msgstr[0] "La información del paquete fue actualizada hace %(days_ago)s día."
msgstr[1] "La información del paquete fue actualizada hace %(days_ago)s días."

#: ../UpdateManager/UpdateManager.py:639
#, python-format
msgid "The package information was last updated %(hours_ago)s hour ago."
msgid_plural ""
"The package information was last updated %(hours_ago)s hours ago."
msgstr[0] ""
"La información de los paquetes se actualizó por última vez hace "
"%(hours_ago)s hora."
msgstr[1] ""
"La información de los paquetes se actualizó por última vez hace "
"%(hours_ago)s horas."

#. TRANSLATORS: only in plural form, as %s minutes ago is one of 15, 30, 45 minutes ago
#: ../UpdateManager/UpdateManager.py:644 ../UpdateManager/UpdateManager.py:646
#: ../UpdateManager/UpdateManager.py:648
#, python-format
msgid "The package information was last updated about %s minutes ago."
msgstr "La información de los paquetes se actualizó hace %s minutos."

#: ../UpdateManager/UpdateManager.py:650
msgid "The package information was just updated."
msgstr "La información de los paquetes se acaba de actualizar."

#: ../UpdateManager/UpdateManager.py:689
msgid "Software updates may be available for your computer."
msgstr "Puede haber actualizaciones disponibles para su equipo."

#: ../UpdateManager/UpdateManager.py:697
#, python-format
msgid ""
"Updated software has been issued since %s was released. Do you want to "
"install it now?"
msgstr ""

#: ../UpdateManager/UpdateManager.py:700
msgid ""
"Updated software is available for this computer. Do you want to install it "
"now?"
msgstr ""

#: ../UpdateManager/UpdateManager.py:758
#, python-format
msgid ""
"The upgrade needs a total of %s free space on disk '%s'. Please free at "
"least an additional %s of disk space on '%s'. Empty your trash and remove "
"temporary packages of former installations using 'sudo apt-get clean'."
msgstr ""
"La actualización necesita un total de %s de espacio libre en el disco «%s». "
"Libere al menos %s adicionales de espacio de disco en «%s». Vacíe su "
"papelera y elimine paquetes temporales de instalaciones anteriores usando "
"«sudo apt-get clean»."

#: ../UpdateManager/UpdateManager.py:783
msgid ""
"The computer needs to restart to finish installing updates. Please save your "
"work before continuing."
msgstr ""
"El equipo necesita reiniciarse para finalizar la actualización. Guarde su "
"trabajo antes de continuar."

#: ../UpdateManager/UpdateManager.py:847
msgid "Reading package information"
msgstr "Leyendo la información de paquetes"

#: ../UpdateManager/UpdateManager.py:862
msgid "Connecting..."
msgstr "Conectando…"

#: ../UpdateManager/UpdateManager.py:879
msgid "You may not be able to check for updates or download new updates."
msgstr ""
"Puede que no sea capaz de comprobar actualizaciones o de descargar nuevas "
"actualizaciones."

#: ../UpdateManager/UpdateManager.py:1002
msgid "Could not initialize the package information"
msgstr "No se ha podido inicializar la información de los paquetes"

#: ../UpdateManager/UpdateManager.py:1003
msgid ""
"An unresolvable problem occurred while initializing the package "
"information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""
"Ha ocurrido un problema imposible de corregir cuando se inicializaba la "
"información de los paquetes.\n"
"\n"
"Por favor, informe de esto como un fallo en el paquete «update-manager» e "
"incluya el siguiente mensaje de error:\n"

#: ../UpdateManager/UpdateManager.py:1032
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr ""
"Ha ocurrido un problema imposible de corregir cuando se calculaba la "
"actualización.\n"
"\n"
"Por favor, informe de esto como un fallo en el paquete «update-manager» e "
"incluya el siguiente mensaje de error:"

#: ../UpdateManager/UpdateManager.py:1056
msgid " (New install)"
msgstr " (Instalación nueva)"

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:1063
#, python-format
msgid "(Size: %s)"
msgstr "(Tamaño: %s)"

#: ../UpdateManager/UpdateManager.py:1067
#, python-format
msgid "From version %(old_version)s to %(new_version)s"
msgstr "De la versión %(old_version)s a la %(new_version)s"

#: ../UpdateManager/UpdateManager.py:1071
#, python-format
msgid "Version %s"
msgstr "Versión %s"

#: ../UpdateManager/UpdateManager.py:1104 ../do-release-upgrade:112
msgid "Release upgrade not possible right now"
msgstr "La actualización de versión no es posible en este momento"

#: ../UpdateManager/UpdateManager.py:1105 ../do-release-upgrade:113
#, c-format, python-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr ""
"La actualización de versión no se puede realizar en este momento, inténtelo "
"de nuevo después. El servidor informó: «%s»"

#: ../UpdateManager/UpdateManager.py:1107 ../check-new-release-gtk:126
msgid "Downloading the release upgrade tool"
msgstr "Descargando la herramienta de actualización de la versión"

#: ../UpdateManager/UpdateManager.py:1114
#, python-format
msgid "<b>New Ubuntu release '%s' is available</b>"
msgstr "<b>Está disponible la nueva versión «%s» de Ubuntu</b>"

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:1153
msgid "Software index is broken"
msgstr "El índice de software está dañado"

#: ../UpdateManager/UpdateManager.py:1154
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""
"Es imposible instalar o desinstalar ningún programa. Use primero el gestor "
"de paquetes «Synaptic» (o ejecute «sudo apt-get install -f» en una "
"terminal), para corregir este problema."

#: ../UpdateManager/UnitySupport.py:57
msgid "Check for Updates"
msgstr "Comprobar actualizaciones"

#: ../UpdateManager/UnitySupport.py:66
msgid "Install All Available Updates"
msgstr "Instalar todas las actualizaciones disponibles"

#: ../UpdateManagerText/UpdateManagerText.py:34
msgid "Cancel"
msgstr "Cancelar"

#: ../UpdateManagerText/UpdateManagerText.py:37
msgid "Changelog"
msgstr "Lista de cambios"

#: ../UpdateManagerText/UpdateManagerText.py:40
msgid "Updates"
msgstr "Actualizaciones"

#: ../UpdateManagerText/UpdateManagerText.py:53
msgid "Building Updates List"
msgstr "Construyendo la lista de actualizaciones"

#: ../UpdateManagerText/UpdateManagerText.py:56
msgid ""
"\n"
"A normal upgrade can not be calculated, please run: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""
"\n"
"No se puede llevar a cabo una actualización normal, ejecute: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"Esto puede estar provocado por:\n"
" * Una actualización anterior incompleta\n"
" * Problemas con algún software instalado\n"
" * Paquetes no oficiales de software, no provistos por Ubuntu\n"
" * Cambios normales en una versión aún no publicada de Ubuntu"

#: ../UpdateManagerText/UpdateManagerText.py:125
msgid "Downloading changelog"
msgstr "Descargando el informe de cambios"

#: ../UpdateManager/Core/MyCache.py:147
#, python-format
msgid "Other updates (%s)"
msgstr "Otras actualizaciones (%s)"

#: ../UpdateManager/Core/MyCache.py:325
msgid "This update does not come from a source that supports changelogs."
msgstr ""
"Esta actualización no procede de una fuente que soporte registro de cambios."

#: ../UpdateManager/Core/MyCache.py:331 ../UpdateManager/Core/MyCache.py:359
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""
"Hubo un fallo al descargar la lista de cambios. \n"
"Compruebe su conexión a Internet."

#: ../UpdateManager/Core/MyCache.py:338
#, python-format
msgid ""
"Changes for the versions:\n"
"Installed version: %s\n"
"Available version: %s\n"
"\n"
msgstr ""
"Cambios de las versiones:\n"
"Versión instalada: %s\n"
"Versión disponible: %s\n"
"\n"

#: ../UpdateManager/Core/MyCache.py:348
#, python-format
msgid ""
"The changelog does not contain any relevant changes.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"El registro de cambios no contiene ningún cambio relevante.\n"
"\n"
"Por favor, use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"hasta que los cambios estén disponibles, o pruebe de nuevo más tarde."

#: ../UpdateManager/Core/MyCache.py:353
#, python-format
msgid ""
"The list of changes is not available yet.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"La lista de cambios no está disponible todavía.\n"
"\n"
"Por favor, use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"hasta que los cambios estén disponibles, o inténtelo más tarde."

#: ../UpdateManager/Core/UpdateList.py:51
msgid "Failed to detect distribution"
msgstr "Error al detectar la distribución"

#: ../UpdateManager/Core/UpdateList.py:52
#, python-format
msgid "A error '%s' occurred while checking what system you are using."
msgstr ""
"Ha ocurrido un error «%s» mientras se comprobaba qué sistema está usando."

#: ../UpdateManager/Core/UpdateList.py:63
msgid "Important security updates"
msgstr "Actualizaciones importantes de seguridad"

#: ../UpdateManager/Core/UpdateList.py:64
msgid "Recommended updates"
msgstr "Actualizaciones recomendadas"

#: ../UpdateManager/Core/UpdateList.py:65
msgid "Proposed updates"
msgstr "Actualizaciones propuestas"

#: ../UpdateManager/Core/UpdateList.py:66
msgid "Backports"
msgstr "«Backports»"

#: ../UpdateManager/Core/UpdateList.py:67
msgid "Distribution updates"
msgstr "Actualizaciones de la distribución"

#: ../UpdateManager/Core/UpdateList.py:72
msgid "Other updates"
msgstr "Otras actualizaciones"

#: ../data/gtkbuilder/UpdateManager.ui.h:1
#, fuzzy
msgid "<big><b>Starting Software Updater</b></big>"
msgstr "<big><b>Iniciando el gestor de actualizaciones</b></big>"

#: ../data/gtkbuilder/UpdateManager.ui.h:2
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr ""
"Las actualizaciones de software corrigen errores, eliminan fallos de "
"seguridad y proporcionan nuevas funcionalidades."

#: ../data/gtkbuilder/UpdateManager.ui.h:3
msgid "_Partial Upgrade"
msgstr "_Actualización parcial"

#: ../data/gtkbuilder/UpdateManager.ui.h:4
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr "<big><b>No se pueden instalar todas las actualizaciones</b></big>"

#: ../data/gtkbuilder/UpdateManager.ui.h:5
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""
"Ejecutar una actualización parcial, para instalar tantas actualizaciones "
"como sea posible. \n"
"\n"
"Esto puede ser debido a:\n"
" * Una actualización anterior que no se ha completado\n"
" * Problemas con algunos de los programas instalados\n"
" * Paquetes de software no oficiales ni distribuidos por Ubuntu\n"
" * Los cambios normales de una versión preliminar de Ubuntu"

#: ../data/gtkbuilder/UpdateManager.ui.h:12
msgid "Chec_k"
msgstr "C_omprobar"

#: ../data/gtkbuilder/UpdateManager.ui.h:13
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Updates</i> tab."
msgstr ""
"<b><big>Debe comprobar las actualizaciones manualmente</big></b>\n"
"\n"
"Su sistema no comprueba automáticamente si existen actualizaciones. Puede "
"configurar este comportamiento en <i>Orígenes del software</i>, en la solapa "
"<i>Actualizaciones</i>."

#: ../data/gtkbuilder/UpdateManager.ui.h:16
msgid "_Hide this information in the future"
msgstr "_Ocultar esta información en el futuro"

#: ../data/gtkbuilder/UpdateManager.ui.h:17
msgid "Co_ntinue"
msgstr "Co_ntinuar"

#: ../data/gtkbuilder/UpdateManager.ui.h:18
msgid "<big><b>Running on battery</b></big>"
msgstr "<big><b>Alimentado por baterías</b></big>"

#: ../data/gtkbuilder/UpdateManager.ui.h:19
msgid "Your system is running on battery. Are you sure you want to continue?"
msgstr ""
"Su sistema está ejecutándose con baterías. ¿Está seguro de que quiere "
"continuar?"

#: ../data/gtkbuilder/UpdateManager.ui.h:21
msgid "_Upgrade"
msgstr "_Actualizar"

#: ../data/gtkbuilder/UpdateManager.ui.h:22
#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:8
msgid "Show progress of individual files"
msgstr "Mostrar el progreso de cada archivo individual"

#: ../data/gtkbuilder/UpdateManager.ui.h:23
#: ../data/update-manager.desktop.in.h:1
#, fuzzy
msgid "Software Updater"
msgstr "Actualizaciones de software"

#: ../data/gtkbuilder/UpdateManager.ui.h:24
#, fuzzy
msgid "Starting Software Updater"
msgstr "Actualizaciones de software"

#: ../data/gtkbuilder/UpdateManager.ui.h:25
msgid "U_pgrade"
msgstr "_Actualizar"

#: ../data/gtkbuilder/UpdateManager.ui.h:27
msgid "updates"
msgstr "actualizaciones"

#: ../data/gtkbuilder/UpdateManager.ui.h:28
msgid "Changes"
msgstr "Cambios"

#: ../data/gtkbuilder/UpdateManager.ui.h:29
msgid "Description"
msgstr "Descripción"

#: ../data/gtkbuilder/UpdateManager.ui.h:30
#, fuzzy
msgid "Details of updates"
msgstr "Descripción de la actualización"

#: ../data/gtkbuilder/UpdateManager.ui.h:31
msgid ""
"You are connected via roaming and may be charged for the data consumed by "
"this update."
msgstr ""
"Ahora está conectado en itinerancia y puede tener cargos por los datos "
"consumidos en esta actualización."

#: ../data/gtkbuilder/UpdateManager.ui.h:32
msgid ""
"You may want to wait until you’re not using a mobile broadband connection."
msgstr ""

#: ../data/gtkbuilder/UpdateManager.ui.h:33
msgid "It’s safer to connect the computer to AC power before updating."
msgstr ""
"Es más seguro enchufar el equipo a la toma de corriente antes de actualizar."

#: ../data/gtkbuilder/UpdateManager.ui.h:34
msgid "_Settings..."
msgstr "_Configuración..."

#: ../data/gtkbuilder/UpdateManager.ui.h:35
#, fuzzy
msgid "_Install Now"
msgstr "Instalar"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:1
msgid "<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr ""
"<b>Está disponible una nueva versión de Ubuntu. ¿Le gustaría actualizar?</b>"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:3
msgid "Don't Upgrade"
msgstr "No actualizar"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:4
msgid "Ask Me Later"
msgstr "Preguntar más tarde"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:5
msgid "Yes, Upgrade Now"
msgstr "Sí, actualizar ahora"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:6
msgid "You have declined to upgrade to the new Ubuntu"
msgstr "Ha decidido no actualizarse a la nueva versión de Ubuntu"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:7
#, fuzzy
msgid ""
"You can upgrade at a later time by opening Software Updater and click on "
"\"Upgrade\"."
msgstr ""
"Puede actualizar más adelante abriendo el Gestor de actualizaciones y "
"pulsando en «Actualizar»."

#: ../data/update-manager.desktop.in.h:2
msgid "Software Updates"
msgstr "Actualizaciones de software"

#: ../data/update-manager.desktop.in.h:3
msgid "Show and install available updates"
msgstr "Mostrar e instalar las actualizaciones disponibles"

#: ../update-manager:66 ../update-manager-text:55 ../do-release-upgrade:51
msgid "Show version and exit"
msgstr "Mostrar la versión y salir"

#: ../update-manager:69
msgid "Directory that contains the data files"
msgstr "Directorio que contiene los archivos de datos"

#: ../update-manager:72
msgid "Check if a new Ubuntu release is available"
msgstr "Verificar si hay una nueva versión de Ubuntu disponible"

#: ../update-manager:75 ../do-release-upgrade:54 ../check-new-release-gtk:186
msgid "Check if upgrading to the latest devel release is possible"
msgstr "Comprobar si es posible actualizar a la última versión de desarrollo"

#: ../update-manager:79
msgid "Upgrade using the latest proposed version of the release upgrader"
msgstr ""
"Actualizar usando la versión más reciente propuesta por el actualizador"

#: ../update-manager:86
msgid "Do not focus on map when starting"
msgstr "No poner el foco sobre el mapa cuando se inicie"

#: ../update-manager:89
msgid "Try to run a dist-upgrade"
msgstr "Intente ejecutar dist-upgrade"

#: ../update-manager:92
msgid "Do not check for updates when starting"
msgstr "No comprobar actualizaciones al iniciar"

#: ../update-manager:96 ../do-release-upgrade:70
msgid "Test upgrade with a sandbox aufs overlay"
msgstr "Comprobar la actualización en una capa aufs de caja de arena"

#: ../update-manager:116
msgid "Running partial upgrade"
msgstr "Ejecutando una actualización parcial"

#: ../update-manager-text:59
msgid "Show description of the package instead of the changelog"
msgstr "Mostrar la descripción del paquete en lugar de la lista de cambios"

#: ../do-release-upgrade:58 ../check-new-release-gtk:190
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""
"Intente actualizar a la última versión usando el actualizador de $distro-"
"proposed"

#: ../do-release-upgrade:62
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"Ejecutar en un modo especial de actualización.\n"
"Actualmente se soportan los modos «desktop» (para actualizaciones normales "
"de un sistema de escritorio) y «server» (para servidores)."

#: ../do-release-upgrade:68
msgid "Run the specified frontend"
msgstr "Ejecutar la interfaz especificada"

#: ../do-release-upgrade:73
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""
"Comprueba únicamente si está disponible una nueva versión de la distribución "
"e informa del resultado mediante un código de salida"

#: ../do-release-upgrade:87
msgid "Checking for a new Ubuntu release"
msgstr "Comprobar si hay una nueva versión de Ubuntu"

#: ../do-release-upgrade:101
msgid ""
"For upgrade information, please visit:\n"
"%(url)s\n"
msgstr ""
"Para saber más sobre esta actualización,visite:\n"
"%(url)s\n"

#: ../do-release-upgrade:107
msgid "No new release found"
msgstr "No se ha encontrado ninguna edición nueva"

#: ../do-release-upgrade:119
#, c-format
msgid "New release '%s' available."
msgstr "Está disponible la nueva versión «%s»."

#: ../do-release-upgrade:120
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "Ejecute «do-release-upgrade» para actualizarse a ella."

#: ../check-new-release-gtk:101
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "Está disponible la actualización a Ubuntu %(version)s"

#: ../check-new-release-gtk:143
#, c-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr "Ha decidido no actualizarse a Ubuntu %s"

#: ../check-new-release-gtk:196
msgid "Add debug output"
msgstr "Añadir resultado de la depuración"

#: ../ubuntu-support-status:91
msgid "Show unsupported packages on this machine"
msgstr "Mostrar paquetes sin soporte en esta máquina"

#: ../ubuntu-support-status:94
msgid "Show supported packages on this machine"
msgstr "Mostrar paquetes con soporte en esta máquina"

#: ../ubuntu-support-status:97
msgid "Show all packages with their status"
msgstr "Mostrar todos los paquetes con sus estados"

#: ../ubuntu-support-status:100
msgid "Show all packages in a list"
msgstr "Mostrar todos los paquetes en una lista"

#: ../ubuntu-support-status:142
#, c-format
msgid "Support status summary of '%s':"
msgstr "Resumen de estado de soporte de «%s»:"

#: ../ubuntu-support-status:145
msgid "You have %(num)s packages (%(percent).1f%%) supported until %(time)s"
msgstr "Tiene %(num)s paquetes (%(percent).1f%%) con soporte hasta %(time)s"

#: ../ubuntu-support-status:151
msgid ""
"You have %(num)s packages (%(percent).1f%%) that can not/no-longer be "
"downloaded"
msgstr "Tiene %(num)s paquetes (%(percent).1f%%) que no pueden descargarse más"

#: ../ubuntu-support-status:154
msgid "You have %(num)s packages (%(percent).1f%%) that are unsupported"
msgstr "Tiene %(num)s paquetes (%(percent).1f%%) sin soporte"

#: ../ubuntu-support-status:162
msgid ""
"Run with --show-unsupported, --show-supported or --show-all to see more "
"details"
msgstr ""
"Ejecute con --show-unsupported, --show-supported o --show-all para ver más "
"detalles"

#: ../ubuntu-support-status:166
msgid "No longer downloadable:"
msgstr "No se pueden descargar más:"

#: ../ubuntu-support-status:169
msgid "Unsupported: "
msgstr "Sin soporte: "

#: ../ubuntu-support-status:174
#, c-format
msgid "Supported until %s:"
msgstr "Con soporte hasta %s:"

#: ../ubuntu-support-status:183
msgid "Unsupported"
msgstr "Sin soporte"

#. Why do we use %s here instead of $strings or {} format placeholders?
#. It's because we don't want to break existing translations.
#: ../janitor/plugincore/exceptions.py:42
#, python-format
msgid "Unimplemented method: %s"
msgstr "Método no implementado: %s"

#: ../janitor/plugincore/core/file_cruft.py:41
msgid "A file on disk"
msgstr "Un archivo en disco"

#: ../janitor/plugincore/core/missing_package_cruft.py:39
msgid "Install missing package."
msgstr "Instalar paquete que falta."

#. 2012-06-08 BAW: i18n string; don't use {} or PEP 292.
#: ../janitor/plugincore/core/missing_package_cruft.py:49
#, python-format
msgid "Package %s should be installed."
msgstr "Debe instalarse el paquete %s"

#: ../janitor/plugincore/core/package_cruft.py:49
msgid ".deb package"
msgstr "Paquete .deb"

#: ../janitor/plugincore/plugins/langpack_manual_plugin.py:46
#, python-format
msgid "%s needs to be marked as manually installed."
msgstr "Se debe marcar %s como instalado manualmente."

#: ../janitor/plugincore/plugins/kdelibs4to5_plugin.py:49
msgid ""
"When upgrading, if kdelibs4-dev is installed, kdelibs5-dev needs to be "
"installed. See bugs.launchpad.net, bug #279621 for details."
msgstr ""
"Al actualizar. Sí  kdelibs4-dev esta instalado hay que instalar kdelibs5-"
"dev. Vea bugs.launchpad.net , bug #279621 para más detalles"

#: ../janitor/plugincore/plugins/dpkg_status_plugin.py:44
#, python-format
msgid "%i obsolete entries in the status file"
msgstr "%i entradas obsoletas en el archivo de estado"

#: ../janitor/plugincore/plugins/dpkg_status_plugin.py:47
msgid "Obsolete entries in dpkg status"
msgstr "Entradas obsoletas en estado de dpkg"

#. pragma: no cover
#: ../janitor/plugincore/plugins/dpkg_status_plugin.py:50
msgid "Obsolete dpkg status entries"
msgstr "Entradas de estado dpkg obsoletas"

#: ../janitor/plugincore/plugins/remove_lilo_plugin.py:42
msgid "Remove lilo since grub is also installed.(See bug #314004 for details.)"
msgstr ""
"Se elimina LILO ya que GRUB también está instalado (Consulte el bug #314004 "
"para más información.)"

#~ msgid ""
#~ "After your package information was updated the essential package '%s' can "
#~ "not be found anymore so a bug reporting process is being started."
#~ msgstr ""
#~ "Después de que su información del paquete fuese actualizada el paquete "
#~ "esencial «%s» no se encuentra, por lo que se está iniciando un proceso de "
#~ "notificación de errores."

#~ msgid "<b><big>Upgrading Ubuntu to version 12.04</big></b>"
#~ msgstr "<b><big>Actualizando Ubuntu a la versión 12.04</big></b>"

#~ msgid "%(count)s update has been selected."
#~ msgid_plural "%(count)s updates have been selected."
#~ msgstr[0] "Se ha seleccionado %(count)s actualización."
#~ msgstr[1] "Se han seleccionado %(count)s actualizaciones."

#~ msgid "%(count_str)s %(download_str)s"
#~ msgstr "%(count_str)s %(download_str)s"

#~ msgid "Welcome to Ubuntu"
#~ msgstr "Bienvenido/a a Ubuntu"

#~ msgid ""
#~ "These software updates have been issued since this version of Ubuntu was "
#~ "released."
#~ msgstr ""
#~ "Estas actualizaciones de software se publicaron desde el lanzamiento de "
#~ "esta versión de Ubuntu."

#~ msgid "Software updates are available for this computer."
#~ msgstr "Hay actualizaciones disponibles para este equipo."

#~ msgid "Update Manager"
#~ msgstr "Gestor de actualizaciones"

#~ msgid "Starting Update Manager"
#~ msgstr "Iniciando el Gestor de actualizaciones"

#~ msgid "You are connected via a wireless modem."
#~ msgstr "Está conectado vía módem inalámbico."

#~ msgid "_Install Updates"
#~ msgstr "_Instalar actualizaciones"

#~ msgid "Checking for a new ubuntu release"
#~ msgstr "Comprobar si existe un nueva versión de Ubuntu"

#~ msgid "Your system is up-to-date"
#~ msgstr "Su sistema está actualizado"

#~ msgid ""
#~ "This upgrade is running in sandbox (test) mode. All changes are written "
#~ "to '%s' and will be lost on the next reboot.\n"
#~ "\n"
#~ "*No* changes written to a systemdir from now until the next reboot are "
#~ "permanent."
#~ msgstr ""
#~ "Esta actualización está ejecutándose en un modo caja de arena (test). "
#~ "Todos los cambios se escriben en «%s» y se perderán en el próximo "
#~ "reinicio.\n"
#~ "\n"
#~ "*No* se escribirán cambios permanentes a una carpeta de sistema desde "
#~ "ahora hasta el próximo reinicio."

#~ msgid ""
#~ "If you don't want to install them now, choose \"Update Manager\" from the "
#~ "Administration menu later."
#~ msgstr ""
#~ "Si no desea instalarlas ahora, hágalo luego usando el «Gestor de "
#~ "actualizaciones» del menú Administración."

#~ msgid "Software updates are available for this computer"
#~ msgstr "Hay actualizaciones disponibles para este equipo"

#~ msgid ""
#~ "Fetching and installing the upgrade can take several hours. Once the "
#~ "download has finished, the process cannot be cancelled."
#~ msgstr ""
#~ "Descargar e instalar la actualización puede llevar varias horas. Una vez "
#~ "finalizada la descarga, el proceso no podrá cancelarse."

#~ msgid "There are no updates to install"
#~ msgstr "No hay actualizaciones para instalar"

#~ msgid "The update has already been downloaded, but not installed"
#~ msgid_plural "The updates have already been downloaded, but not installed"
#~ msgstr[0] "La actualización ya se descargó, pero no se instaló"
#~ msgstr[1] "Las actualizaciones ya se descargaron, pero no se instalaron"

#~ msgid ""
#~ "You will not get any further security fixes or critical updates. Please "
#~ "upgrade to a later version of Ubuntu Linux."
#~ msgstr ""
#~ "No obtendrá más actualizaciones de seguridad o actualizaciones críticas. "
#~ "Actualice a una versión más reciente de Ubuntu Linux."

#~ msgid ""
#~ "If you don't want to install them now, choose \"Update Manager\" from "
#~ "Applications later."
#~ msgstr ""
#~ "Si no desea instalarlas ahora, seleccione más tarde el «Gestor de "
#~ "actualizaciones» en el menú Aplicaciones."

#~ msgid "Your graphics hardware may not be fully supported in Ubuntu 11.04."
#~ msgstr ""
#~ "Parece que su hardware gráfico no tiene soporte completo en Ubuntu 11.04."

#~ msgid ""
#~ "The support in Ubuntu 11.04 for your intel graphics hardware is limited "
#~ "and you may encounter problems after the upgrade. Do you want to continue "
#~ "with the upgrade?"
#~ msgstr ""
#~ "El soporte en Ubuntu 11.04. para su hardaware gráfico de intel es "
#~ "limitado y es posible que sucedan errores después de la actualización. "
#~ "¿Quiere continuar con la actualización?"

#~ msgid ""
#~ "Preparing the system for the upgrade failed. Please report this using the "
#~ "command 'ubuntu-bug update-manager' in a terminal and include the files "
#~ "in /var/log/dist-upgrade/ in the bug report."
#~ msgstr ""
#~ "La preparación del sistema para la actualización falló. Informe de este "
#~ "fallo usando la orden «'ubuntu-bug update-manager» en una terminal e "
#~ "incluya los archivos presentes en /var/log/dist-upgrade/ en su informe de "
#~ "fallos."

#~ msgid ""
#~ "Upgrading the repository information resulted in a invalid file. Please "
#~ "report this as a bug using the command 'ubuntu-bug update-manager' in a "
#~ "terminal."
#~ msgstr ""
#~ "La actualización de la información del repositorio dio como resultado un "
#~ "archivo inválido. Informe de este fallo usando la orden «ubuntu-bug "
#~ "update-manager» en una terminal."

#~ msgid ""
#~ "\n"
#~ "\n"
#~ "Please report this bug using the command 'ubuntu-bug update-manager' in a "
#~ "terminal and include the files in /var/log/dist-upgrade/ in the bug "
#~ "report.\n"
#~ "%s"
#~ msgstr ""
#~ "\n"
#~ "\n"
#~ "Informe de este error mediante la orden «ubuntu-bug update-manager» en "
#~ "una terminal e incluya los archivos de /var/log/dist-upgrade/ en el "
#~ "informe de error.\n"
#~ "%s"

#~ msgid ""
#~ "The system was unable to get the prerequisites for the upgrade. The "
#~ "upgrade will abort now and restore the original system state.\n"
#~ "\n"
#~ "Please report this as a bug using the command 'ubuntu-bug update-manager' "
#~ "in a terminal and include the files in /var/log/dist-upgrade/ in the bug "
#~ "report."
#~ msgstr ""
#~ "El sistema fue incapaz de conseguir las condiciones necesarias para la "
#~ "actualización. La actualización se interrumpirá ahora y restaurar el "
#~ "estado original del sistema.\n"
#~ "\n"
#~ "Informe de este error mediante la orden «ubuntu-bug update-manager» en "
#~ "una terminal e incluya los archivos de /var/log/dist-upgrade/ en el "
#~ "informe de error."

#~ msgid ""
#~ "After your package information was updated the essential package '%s' can "
#~ "not be found anymore.\n"
#~ "This indicates a serious error, please report this bug using the command "
#~ "'ubuntu-bug update-manager' in a terminal and include the files in /var/"
#~ "log/dist-upgrade/ in the bug report."
#~ msgstr ""
#~ "Después de que la información de su paquete se actualice el paquete "
#~ "esencial «%s» ya no se encuentra.\n"
#~ "Esto indica un error grave, informe de esto usando la orden «ubuntu-bug "
#~ "update-manager» en una terminal e incluya los archivos de /var/log/dist-"
#~ "upgrade/ en el informe de error."

#~ msgid "1 kB"
#~ msgstr "1 kB"

#~ msgid "0 kB"
#~ msgstr "0 kB"

#~ msgid "%.0f kB"
#~ msgstr "%.0f kB"

#~ msgid ""
#~ "These software updates have been issued since this version of Ubuntu was "
#~ "released. If you don't want to install them now, choose \"Update Manager"
#~ "\" from Applications later."
#~ msgstr ""
#~ "Estas actualizaciones de software se publicaron después del lanzamiento "
#~ "de esta versión de Ubuntu. Si no quiere instalarlas ahora, abra más tarde "
#~ "el Gestor de actualizaciones desde Aplicaciones."

#~ msgid ""
#~ "These software updates have been issued since this version of Ubuntu was "
#~ "released. If you don't want to install them now, choose \"Update Manager"
#~ "\" from the Administration Menu later."
#~ msgstr ""
#~ "Estas actualizaciones de software se publicaron después del lanzamiento "
#~ "de esta versión de Ubuntu. Si no quiere instalarlas ahora, abra más tarde "
#~ "el Gestor de actualizaciones desde el menú Administración."
