# translation of gl.po to galician
# translation of update-manager-gl.po to galician
# This file is distributed under the same license as the update-manager package.
#  Copyright (c) 2004 Canonical
#                2004 Michiel Sikkes
# Mar Castro <mariamarcp@gmail.com>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: gl\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2012-06-14 00:53+0100\n"
"PO-Revision-Date: 2012-03-21 11:11+0000\n"
"Last-Translator: Fran Diéguez <Unknown>\n"
"Language-Team: galician\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Launchpad-Export-Date: 2012-04-17 13:41+0000\n"
"X-Generator: Launchpad (build 15099)\n"

#. TRANSLATORS: download size of small updates, e.g. "250 kB"
#: ../DistUpgrade/utils.py:433 ../UpdateManager/Core/utils.py:433
#, python-format
msgid "%(size).0f kB"
msgid_plural "%(size).0f kB"
msgstr[0] "%(size).0f kB"
msgstr[1] "%(size).0f kB"

#. TRANSLATORS: download size of updates, e.g. "2.3 MB"
#: ../DistUpgrade/utils.py:436 ../UpdateManager/Core/utils.py:436
#, python-format
msgid "%.1f MB"
msgstr "%.1f MB"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:206 ../DistUpgrade/distro.py:436
#, python-format
msgid "Server for %s"
msgstr "Servidor desde %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:224 ../DistUpgrade/distro.py:230
#: ../DistUpgrade/distro.py:246
msgid "Main server"
msgstr "Servidor principal"

#: ../DistUpgrade/distro.py:250
msgid "Custom servers"
msgstr "Servidores personalizados"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:142
msgid "Could not calculate sources.list entry"
msgstr "Non e posíbel calcular a entrada do sources.list"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:251
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr ""
"Non é posíbel localizar ningún ficheiro de paquete; se cadra este non é un "
"disco de Ubuntu ou a arquitectura non é a correcta."

#: ../DistUpgrade/DistUpgradeAptCdrom.py:294
msgid "Failed to add the CD"
msgstr "Non foi posíbel engadir o CD"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:295
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"Produciuse un erro ao engadir o CD e hai que cancelar a anovación. Informe "
"deste erro se se trata dun CD correcto de Ubuntu.\n"
"\n"
"A mensaxe de erro foi:\n"
"«%s»"

#: ../DistUpgrade/DistUpgradeCache.py:151
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "Retirar o paquete en mal estado"
msgstr[1] "Retirar os paquetes en mal estado"

#: ../DistUpgrade/DistUpgradeCache.py:154
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"O paquete «%s» ten un estado inconsistente e precisa ser reinstalado pero "
"non se atopa ningún ficheiro para facelo. Quere eliminar este paquete e "
"continuar?"
msgstr[1] ""
"Os paquetes «%s» teñen un estado inconsistente e precisan ser reinstalados "
"pero non se atopa ningún ficheiro para facelo. Quere eliminar estes paquetes "
"e continuar?"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:255
msgid "The server may be overloaded"
msgstr "O servidor quizais estea saturado"

#: ../DistUpgrade/DistUpgradeCache.py:368
msgid "Broken packages"
msgstr "Paquetes rotos"

#: ../DistUpgrade/DistUpgradeCache.py:369
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"O seu sistema contén paquetes rotos que non poden ser arranxados con este "
"software. Por favor, arránxeos primeiro usando Synaptic ou apt-get antes de "
"continuar."

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:693
#, python-format
msgid ""
"An unresolvable problem occurred while calculating the upgrade:\n"
"%s\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""
"Un problema irresolúbel ocorreu mentres se calculaba a anovación:\n"
"%s\n"
" Isto pode ser causado por:\n"
" * Anovar desde unha versión de prelanzamento de Ubuntu\n"
" * Executar a versión actual de prelanzamento de Ubuntu\n"
" * Paquetes de software non oficiais non fornecidos por Ubuntu\n"
"\n"

#: ../DistUpgrade/DistUpgradeCache.py:703
msgid "This is most likely a transient problem, please try again later."
msgstr "Trátase, o máis seguro, dun problema temporal. Ténteo máis tarde."

#: ../DistUpgrade/DistUpgradeCache.py:706
msgid ""
"If none of this applies, then please report this bug using the command "
"'ubuntu-bug update-manager' in a terminal."
msgstr ""
"Se non se aplica ningunha opción,  informe de este erro usando a orde "
"«ubuntu-bug update-manager» desde o seu terminal."

#: ../DistUpgrade/DistUpgradeCache.py:711
#: ../UpdateManager/UpdateManager.py:1031
msgid "Could not calculate the upgrade"
msgstr "Non foi posíbel calcular a anovación"

#: ../DistUpgrade/DistUpgradeCache.py:762
msgid "Error authenticating some packages"
msgstr "Produciuse un erro ao autenticar algúns paquetes"

#: ../DistUpgrade/DistUpgradeCache.py:763
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"Non foi posíbel autenticar algúns paquetes. Isto pode ser debido a un "
"problema transitorio na rede. Probe de novo máis tarde. Vexa abaixo unha "
"lista dos paquetes non autenticados."

#: ../DistUpgrade/DistUpgradeCache.py:783
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""
"O paquete «%s» está marcado para a súa eliminación pero está na lista negra "
"de paquetes eliminábeis."

#: ../DistUpgrade/DistUpgradeCache.py:787
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "O paquete esencial «%s» está marcado para a súa eliminación"

#: ../DistUpgrade/DistUpgradeCache.py:796
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr "Tentando instalar a versión da lista negra «%s»"

#: ../DistUpgrade/DistUpgradeCache.py:914
#, python-format
msgid "Can't install '%s'"
msgstr "Non foi posíbel instalar «%s»"

#: ../DistUpgrade/DistUpgradeCache.py:915
msgid ""
"It was impossible to install a required package. Please report this as a bug "
"using 'ubuntu-bug update-manager' in a terminal."
msgstr ""
"Foi imposíbel instalar o paquete requirido. Informe de este erro usando a "
"orde «ubuntu-bug update-manager» desde o seu terminal."

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:926
msgid "Can't guess meta-package"
msgstr "Non foi posíbel determinar o meta-paquete"

#: ../DistUpgrade/DistUpgradeCache.py:927
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"O seu sistema non contén os paquetes ubuntu-desktop, kubuntu-desktop ou "
"edubuntu-desktop e non foi posíbel detectar cal é a versión de ubuntu que se "
"está a executar.\n"
" Instale un dos paquetes mencionados usando synaptic ou apt-get antes de "
"continuar."

#: ../DistUpgrade/DistUpgradeController.py:114
msgid "Reading cache"
msgstr "Lendo a caché"

#: ../DistUpgrade/DistUpgradeController.py:223
msgid "Unable to get exclusive lock"
msgstr "Foi imposíbel obter un bloqueo exclusivo"

#: ../DistUpgrade/DistUpgradeController.py:224
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"Isto normalmente significa que outro xestor de paquetes (como apt-get ou "
"aptitude) xa se está executando. Peche este aplicativo antes de continuar."

#: ../DistUpgrade/DistUpgradeController.py:257
msgid "Upgrading over remote connection not supported"
msgstr "A actualización mediante unha conexión remota non é posíbel"

#: ../DistUpgrade/DistUpgradeController.py:258
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"Está executando a anovación a través dunha conexión SSH cunha interface que "
"non é compatíbel con esta. Por favor, tente unha anovación en modo de texto "
"con «do-release-upgrade».\n"
"\n"
"A anovación vai ser cancelada agora. Por favor, ténteo sen ssh."

#: ../DistUpgrade/DistUpgradeController.py:272
msgid "Continue running under SSH?"
msgstr "Continuar a execución con SSH?"

#: ../DistUpgrade/DistUpgradeController.py:273
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"Esta sesión semella estar executandose baixo SSH. Na actualidade non se "
"recomenda facer unha anovación a través de ssh porque no caso de fracaso, é "
"máis difícil de recuperar.\n"
"\n"
"Se continúa, iniciarase un daemon ssh adicional no porto «%s».\n"
"Desexa continuar?"

#: ../DistUpgrade/DistUpgradeController.py:287
msgid "Starting additional sshd"
msgstr "Iniciando un sshd adicional"

#: ../DistUpgrade/DistUpgradeController.py:288
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"Para que resulte máis doada a recuperación no caso de fallo, iniciarase un "
"sshd adicional no porto «%s». Se algo sae mal co ssh en execución, aínda "
"poderá conectarse co adicional.\n"

#: ../DistUpgrade/DistUpgradeController.py:296
#, python-format
msgid ""
"If you run a firewall, you may need to temporarily open this port. As this "
"is potentially dangerous it's not done automatically. You can open the port "
"with e.g.:\n"
"'%s'"
msgstr ""
"Se executa unha devasa, pode necesitar abrir este porto temporalmente. Como "
"isto é potencialmente perigoso, non se fai automaticamente. Pode abrir o "
"porto con, p.ex.:\n"
"«%s»"

#: ../DistUpgrade/DistUpgradeController.py:368
#: ../DistUpgrade/DistUpgradeController.py:413
msgid "Can not upgrade"
msgstr "Non é posíbel anovar"

#: ../DistUpgrade/DistUpgradeController.py:369
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr "Con esta ferramenta non se pode anovar de «%s» a «%s»"

#: ../DistUpgrade/DistUpgradeController.py:378
msgid "Sandbox setup failed"
msgstr "A configuración da zona de probas fallou"

#: ../DistUpgrade/DistUpgradeController.py:379
msgid "It was not possible to create the sandbox environment."
msgstr "Non foi posíbel crear o contorno da zona de probas."

#: ../DistUpgrade/DistUpgradeController.py:385
msgid "Sandbox mode"
msgstr "Modo zona de probas"

#: ../DistUpgrade/DistUpgradeController.py:386
#, python-format
msgid ""
"This upgrade is running in sandbox (test) mode. All changes are written to "
"'%s' and will be lost on the next reboot.\n"
"\n"
"*No* changes written to a system directory from now until the next reboot "
"are permanent."
msgstr ""
"Esta anovación está executándose en modo «caixa de area» (proba). Todos os "
"cambios escribiránse en «%s» e perderanse no seguinte \n"
"\n"
"Os cambios no sistema de ficheiros serán permanentes ate que reinicie."

#: ../DistUpgrade/DistUpgradeController.py:414
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""
"A súa instalación de Python é defectuosa. Arranxe a ligazón simbólica «/usr/"
"bin/python»."

#: ../DistUpgrade/DistUpgradeController.py:440
msgid "Package 'debsig-verify' is installed"
msgstr "O paquete «debsig-verify» está instalado"

#: ../DistUpgrade/DistUpgradeController.py:441
msgid ""
"The upgrade can not continue with that package installed.\n"
"Please remove it with synaptic or 'apt-get remove debsig-verify' first and "
"run the upgrade again."
msgstr ""
"A anovación non pode continuar con ese paquete instalado.\n"
"Retíreo  con synaptic ou «apt-get remove debsig-verify» primeiro e faga a "
"anovación de novo."

#: ../DistUpgrade/DistUpgradeController.py:453
#, python-format
msgid "Can not write to '%s'"
msgstr "Non é posíbel escribir en «%s»"

#: ../DistUpgrade/DistUpgradeController.py:454
#, python-format
msgid ""
"Its not possible to write to the system directory '%s' on your system. The "
"upgrade can not continue.\n"
"Please make sure that the system directory is writable."
msgstr ""
"Non é posíbel escribir no directorio do sistema «%s» deste sistema. A "
"actualización non pode continuar.\n"
"Comprobe que se pode escribir no directorio do sistema."

#: ../DistUpgrade/DistUpgradeController.py:465
msgid "Include latest updates from the Internet?"
msgstr "Incluír as actualizacións máis recentes desde a Internet?"

#: ../DistUpgrade/DistUpgradeController.py:466
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""
"O sistema de anovación pode descargar automaticamente as actualizacións máis "
"recentes da Internet e instalalas durante a anovación. Se ten unha conexión "
"de banda larga, isto é moi recomendábel.\n"
"\n"
"A anovación levará máis tempo, mais unha vez rematada, o seu sistema estará "
"completamente actualizado. Pode escoller non facelo, mais debería instalar "
"as actualizacións máis recentes antes de actualizar o sistema.\n"
"Se dis que «non» aquí, non se usará a conexión para nada."

#: ../DistUpgrade/DistUpgradeController.py:686
#, python-format
msgid "disabled on upgrade to %s"
msgstr "desactivado na anovación a %s"

#: ../DistUpgrade/DistUpgradeController.py:713
msgid "No valid mirror found"
msgstr "Non se atopou ningunha réplica correcta"

#: ../DistUpgrade/DistUpgradeController.py:714
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""
"Non se atopou unha entrada na réplica para a anovación ao examinar a "
"información do repositorio. Isto pode acontecer se se executa unha réplica "
"interna ou se a información da réplica estivera anticuada.\n"
"\n"
"Quere substituír «sources.list» igual? Se escoller «Si» aquí, actualizaranse "
"todas as entradas «%s» a «%s».\n"
"Se seleccionar «Non», cancelarase a actualización."

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:734
msgid "Generate default sources?"
msgstr "Xerar as fontes predeterminadas?"

#: ../DistUpgrade/DistUpgradeController.py:735
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"Unha vez examinado «sources.list», non se atopou ningunha entrada correcta "
"para «%s».\n"
"\n"
"Deberíanse engadir as entradas por omisión de «%s»? Se escolle «Non», "
"anularase a anovación."

#: ../DistUpgrade/DistUpgradeController.py:770
msgid "Repository information invalid"
msgstr "A información do repositorio non é correcta"

#: ../DistUpgrade/DistUpgradeController.py:771
msgid ""
"Upgrading the repository information resulted in a invalid file so a bug "
"reporting process is being started."
msgstr ""
"A anovación da información do respositoriu produciu un ficheiro erróneo, "
"polo que se está a iniciar un proceso de informe de erros."

#: ../DistUpgrade/DistUpgradeController.py:778
msgid "Third party sources disabled"
msgstr "Orixes de terceiros desactivadas"

#: ../DistUpgrade/DistUpgradeController.py:779
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"Desactiváronse algunhas entradas de terceiras partes no seu sources.list. "
"Pódeas volver a activar coa ferramenta «software-properties» ou co xestor de "
"paquetes."

#: ../DistUpgrade/DistUpgradeController.py:819
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "Paquete en estado inconsistente"
msgstr[1] "Paquetes en estado inconsistente"

#: ../DistUpgrade/DistUpgradeController.py:822
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"O paquete «%s» ten un estado inconsistente e precisa ser reinstalado pero "
"non se atopa ningún ficheiro para facelo. Reinstale o paquete manualmente ou "
"elimíneo do sistema."
msgstr[1] ""
"Os paquetes «%s» teñen un estado inconsistente e precisan ser reinstalados "
"pero non se atopa ningún ficheiro para facelo. Reinstale os paquete "
"manualmente ou elimíneos do sistema."

#: ../DistUpgrade/DistUpgradeController.py:870
msgid "Error during update"
msgstr "Produciuse un erro durante a actualización"

#: ../DistUpgrade/DistUpgradeController.py:871
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"Ocorreu un problema durante a actualización. Normalmente é debido a algún "
"tipo de problema na rede. Por favor, comprobe a súa conexión de rede e "
"vólvao a intentar."

#. print("on_button_install_clicked")
#: ../DistUpgrade/DistUpgradeController.py:880
#: ../UpdateManager/UpdateManager.py:757
msgid "Not enough free disk space"
msgstr "Non hai espazo abondo no disco"

#: ../DistUpgrade/DistUpgradeController.py:881
#, python-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of %s free space on disk "
"'%s'. Please free at least an additional %s of disk space on '%s'. Empty "
"your trash and remove temporary packages of former installations using 'sudo "
"apt-get clean'."
msgstr ""
"Cancelouse a anovación. A anovación precisa un total de %s de espazo libre "
"no disco «%s». Libere cando menos %s de espazo on disco «%s». Libere o lixo "
"e elimine os paquetes temporais das instalacións anterioers usando «sudo apt-"
"get clean»."

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:910
#: ../DistUpgrade/DistUpgradeController.py:1692
msgid "Calculating the changes"
msgstr "Calculando os cambios"

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:942
msgid "Do you want to start the upgrade?"
msgstr "Desexa comezar a anovación?"

#: ../DistUpgrade/DistUpgradeController.py:1008
msgid "Upgrade canceled"
msgstr "Anulouse a anovación"

#: ../DistUpgrade/DistUpgradeController.py:1009
msgid ""
"The upgrade will cancel now and the original system state will be restored. "
"You can resume the upgrade at a later time."
msgstr ""
"Agora vaise cancelar a anovación e o sistema volverá ao seu estado orixinal. "
"Pode retomar a actualización máis adiante."

#: ../DistUpgrade/DistUpgradeController.py:1015
#: ../DistUpgrade/DistUpgradeController.py:1149
msgid "Could not download the upgrades"
msgstr "Non se puideron descargar as anovacións"

#: ../DistUpgrade/DistUpgradeController.py:1016
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far have been kept."
msgstr ""
"Abortouse a actualización. Comprobe a súa conexión a Internet ou medio de "
"instalación e ténteo de novo. Tódolos ficheiros descargados serán mantidos."

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1100
#: ../DistUpgrade/DistUpgradeController.py:1137
#: ../DistUpgrade/DistUpgradeController.py:1242
msgid "Error during commit"
msgstr "Produciuse un erro durante a remisión"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1102
#: ../DistUpgrade/DistUpgradeController.py:1139
#: ../DistUpgrade/DistUpgradeController.py:1281
msgid "Restoring original system state"
msgstr "Restaurando o estado orixinal do sistema"

#: ../DistUpgrade/DistUpgradeController.py:1103
#: ../DistUpgrade/DistUpgradeController.py:1118
#: ../DistUpgrade/DistUpgradeController.py:1140
msgid "Could not install the upgrades"
msgstr "Non se puideron instalar as anovacións"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1108
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"Abortouse a anovación. O seu sistema pode estar nun estado non usábel. Vaise "
"executar agora a recuperación (dpkg --configure -a)."

#: ../DistUpgrade/DistUpgradeController.py:1113
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug in a browser at http://bugs.launchpad.net/ubuntu/"
"+source/update-manager/+filebug and attach the files in /var/log/dist-"
"upgrade/ to the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"Faga o favor de informar deste erro nun navegador en http://bugs.launchpad."
"net/ubuntu/+source/update-manager/+filebug e anexe os ficheiros que hai en /"
"var/log/dist-upgrade/ ao informe de erros.\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1150
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""
"Cancelouse a actualización. Comprobe a súa conexión a Internet ou o "
"dispositivo de instalación e volva a tentalo. "

#: ../DistUpgrade/DistUpgradeController.py:1230
msgid "Remove obsolete packages?"
msgstr "Retirar os paquetes obsoletos?"

#: ../DistUpgrade/DistUpgradeController.py:1231
#: ../DistUpgrade/DistUpgrade.ui.h:8
msgid "_Keep"
msgstr "_Conservar"

#: ../DistUpgrade/DistUpgradeController.py:1231
msgid "_Remove"
msgstr "_Retirar"

#: ../DistUpgrade/DistUpgradeController.py:1243
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr ""
"Ocorreu algún problema durante a limpeza. Por favor, vexa a mensaxe inferior "
"para obter máis información. "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1319
msgid "Required depends is not installed"
msgstr "Non está instalado depends, que é necesario"

#: ../DistUpgrade/DistUpgradeController.py:1320
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "A dependencia requirida «%s» non está instalada. "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1588
#: ../DistUpgrade/DistUpgradeController.py:1653
msgid "Checking package manager"
msgstr "Comprobando o xestor de paquetes"

#: ../DistUpgrade/DistUpgradeController.py:1593
msgid "Preparing the upgrade failed"
msgstr "Fallou a preparación da anovación"

#: ../DistUpgrade/DistUpgradeController.py:1594
msgid ""
"Preparing the system for the upgrade failed so a bug reporting process is "
"being started."
msgstr ""
"Produciuse un fallo ao preparar o sistema para a anovación polo que estase "
"iniciando un proceso de informe de erro."

#: ../DistUpgrade/DistUpgradeController.py:1608
msgid "Getting upgrade prerequisites failed"
msgstr "Fallou a preparación da anovación"

#: ../DistUpgrade/DistUpgradeController.py:1609
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Additionally, a bug reporting process is being started."
msgstr ""
"O sistema non cumpre os prerequisitos para a súa anovación. A anovación "
"cancelarase agora e restaurarase o estado orixinal do sistema.\n"
"\n"
"Ademais, estase iniciando un proceso de informe de erro."

#: ../DistUpgrade/DistUpgradeController.py:1637
msgid "Updating repository information"
msgstr "Actualizando a información do repositorio"

#: ../DistUpgrade/DistUpgradeController.py:1644
msgid "Failed to add the cdrom"
msgstr "Produciuse un fallo ao engadir o CDROM"

#: ../DistUpgrade/DistUpgradeController.py:1645
msgid "Sorry, adding the cdrom was not successful."
msgstr "Sentímolo, non foi posíbel engadir o CDROM"

#: ../DistUpgrade/DistUpgradeController.py:1673
msgid "Invalid package information"
msgstr "Información de paquete incorrecta"

#: ../DistUpgrade/DistUpgradeController.py:1674
msgid "After updating your package "
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1698
#: ../DistUpgrade/DistUpgradeController.py:1750
msgid "Fetching"
msgstr "Obtendo"

#: ../DistUpgrade/DistUpgradeController.py:1704
#: ../DistUpgrade/DistUpgradeController.py:1754
msgid "Upgrading"
msgstr "Anovando"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1709
#: ../DistUpgrade/DistUpgradeController.py:1756
#: ../DistUpgrade/DistUpgradeController.py:1763
#: ../DistUpgrade/DistUpgradeController.py:1774
msgid "Upgrade complete"
msgstr "Completouse a anovación"

#: ../DistUpgrade/DistUpgradeController.py:1710
#: ../DistUpgrade/DistUpgradeController.py:1757
#: ../DistUpgrade/DistUpgradeController.py:1764
msgid ""
"The upgrade has completed but there were errors during the upgrade process."
msgstr "A actualización completouse mais producíronse erros durante o proceso."

#: ../DistUpgrade/DistUpgradeController.py:1717
msgid "Searching for obsolete software"
msgstr "Buscando paquetes obsoletos"

#: ../DistUpgrade/DistUpgradeController.py:1726
msgid "System upgrade is complete."
msgstr "Completouse a anovación do sistema."

#: ../DistUpgrade/DistUpgradeController.py:1775
msgid "The partial upgrade was completed."
msgstr "Completouse a anovación parcial do sistema."

#: ../DistUpgrade/DistUpgradeQuirks.py:204
msgid "evms in use"
msgstr "evms en uso"

#: ../DistUpgrade/DistUpgradeQuirks.py:205
msgid ""
"Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
"software is no longer supported, please switch it off and run the upgrade "
"again when this is done."
msgstr ""
"O sistema emprega o xestor de volumes «evms» en /proc/mounts. O software "
"«evms» non ten asistencia; apágueo e execute de novo a anovación ao rematar."

#: ../DistUpgrade/DistUpgradeQuirks.py:502
msgid "Your graphics hardware may not be fully supported in Ubuntu 12.04 LTS."
msgstr ""
"O seu hardware de gráficos non é completamente compatíbel con Ubuntu 12.04 "
"LTS."

#: ../DistUpgrade/DistUpgradeQuirks.py:504
msgid ""
"The support in Ubuntu 12.04 LTS for your Intel graphics hardware is limited "
"and you may encounter problems after the upgrade. For more information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx Do you want to "
"continue with the upgrade?"
msgstr ""
"A compatibilidade en Ubuntu 12.04 LTS para o seu hardware de gráficos Intel "
"está limitada e pode atopar problemas trala actualización. Para ter máis "
"información vexa https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx "
"¿Desexa continuar coa anovación?"

#: ../DistUpgrade/DistUpgradeQuirks.py:526
#: ../DistUpgrade/DistUpgradeQuirks.py:554
#: ../DistUpgrade/DistUpgradeQuirks.py:581
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"A anovación pode reducir os efectos do escritorio, o rendemento nos xogos e "
"noutros programas que fagan un emprego intensivo dos gráficos."

#: ../DistUpgrade/DistUpgradeQuirks.py:530
#: ../DistUpgrade/DistUpgradeQuirks.py:558
msgid ""
"This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
"version of this driver is available that works with your video card in "
"Ubuntu 10.04 LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"Este computador emprega o controlador gráfico «nvidia» de NVIDIA. Non se "
"conta cun controlador que funcione co seu hardware en Ubuntu 10.04 LTS.\n"
"\n"
"Está seguro de que desexa continuar?"

#: ../DistUpgrade/DistUpgradeQuirks.py:585
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"Este computador emprega o controlador gráfico «fglrx» de AMD. Non se conta "
"cun controlador que funcione co seu hardware en Ubuntu 10.04 LTS.\n"
"\n"
"Está seguro de que desexa continuar?"

#: ../DistUpgrade/DistUpgradeQuirks.py:615
msgid "No i686 CPU"
msgstr "Non é unha CPU i686"

#: ../DistUpgrade/DistUpgradeQuirks.py:616
msgid ""
"Your system uses an i586 CPU or a CPU that does not have the 'cmov' "
"extension. All packages were built with optimizations requiring i686 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"O seu sistema usa unha CPU i586 ou unha CPU que non ten a extensión «cmov». "
"Todos os paquetes foron construídos con optimizacións que requiren i686 como "
"arquitectura mínima. Non é posíbel actualizar o seu sistema á nova versión "
"de Ubuntu con este hardware."

#: ../DistUpgrade/DistUpgradeQuirks.py:652
msgid "No ARMv6 CPU"
msgstr "Non é unha CPU ARMv6"

#: ../DistUpgrade/DistUpgradeQuirks.py:653
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"O seu sistema emprega unha CPU ARM que é máis antiga que a arquitectura "
"ARMv6. Todos os paquetes en karmic foron construídos coas optimizacións que "
"require ARMv6 como arquitectura mínima. Non é posíbel anovar o seu sistema a "
"unha versión de Ubuntu con esta arquitectura."

#: ../DistUpgrade/DistUpgradeQuirks.py:673
msgid "No init available"
msgstr "O «daemon» init non está dispoñíbel"

#: ../DistUpgrade/DistUpgradeQuirks.py:674
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"Semella que o seu sistema é un contorno virtualizado sen un daemon init (un "
"Linux-VServer, p.ex.). Ubuntu 10.04 LTS non pode funcionar neste tipo de "
"contorno, polo que require unha actualización da configuración da súa "
"máquina virtual.\n"
"\n"
"Está seguro de que desexa continuar?"

#: ../DistUpgrade/DistUpgradeMain.py:65
msgid "Sandbox upgrade using aufs"
msgstr "Anovación da área de probas usando aufs"

#: ../DistUpgrade/DistUpgradeMain.py:67
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr "Usar a ruta dada para buscar un CD-ROM con paquetes de actualización"

#: ../DistUpgrade/DistUpgradeMain.py:73
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"Usar a interface gráfica. Dispoñíbeis neste momento: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:76
msgid "*DEPRECATED* this option will be ignored"
msgstr "*OBSOLETO* esta opción será ignorada"

#: ../DistUpgrade/DistUpgradeMain.py:79
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr "Realizar só unha anovación parcial (sen reescribir o sources.list)"

#: ../DistUpgrade/DistUpgradeMain.py:82
msgid "Disable GNU screen support"
msgstr "Desactivar a compatibilidade de pantalla GNU"

#: ../DistUpgrade/DistUpgradeMain.py:84
msgid "Set datadir"
msgstr "Estabelecer datadir"

#. print("mediaChange %s %s" % (medium, drive))
#: ../DistUpgrade/DistUpgradeViewGtk.py:114
#: ../DistUpgrade/DistUpgradeViewGtk3.py:117
#: ../DistUpgrade/DistUpgradeViewKDE.py:195
#: ../UpdateManager/DistUpgradeFetcherKDE.py:155
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "Por favor, introduza «%s» na unidade «%s»"

#: ../DistUpgrade/DistUpgradeViewGtk.py:135
#: ../DistUpgrade/DistUpgradeViewGtk3.py:138
#: ../DistUpgrade/DistUpgradeViewKDE.py:209
msgid "Fetching is complete"
msgstr "Rematou a obtención"

#: ../DistUpgrade/DistUpgradeViewGtk.py:146
#: ../DistUpgrade/DistUpgradeViewGtk3.py:149
#: ../DistUpgrade/DistUpgradeViewKDE.py:222
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "Obtendo o ficheiro %li de %li a %sB/s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:149
#: ../DistUpgrade/DistUpgradeViewGtk.py:296
#: ../DistUpgrade/DistUpgradeViewGtk3.py:152
#: ../DistUpgrade/DistUpgradeViewGtk3.py:309
#: ../DistUpgrade/DistUpgradeViewKDE.py:223
#: ../DistUpgrade/DistUpgradeViewKDE.py:371
#, python-format
msgid "About %s remaining"
msgstr "Restan aproximadamente %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:152
#: ../DistUpgrade/DistUpgradeViewGtk3.py:155
#: ../DistUpgrade/DistUpgradeViewKDE.py:225
#, python-format
msgid "Fetching file %li of %li"
msgstr "Obtendo o ficheiro %li de %li"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:183
#: ../DistUpgrade/DistUpgradeViewGtk3.py:186
#: ../DistUpgrade/DistUpgradeViewKDE.py:262
msgid "Applying changes"
msgstr "Aplicando os cambios"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk.py:208
#: ../DistUpgrade/DistUpgradeViewGtk3.py:212
#: ../DistUpgrade/DistUpgradeViewKDE.py:275
msgid "dependency problems - leaving unconfigured"
msgstr "problemas de dependencias - déixase sen configurar"

#: ../DistUpgrade/DistUpgradeViewGtk.py:213
#: ../DistUpgrade/DistUpgradeViewGtk3.py:217
#: ../DistUpgrade/DistUpgradeViewKDE.py:277
#, python-format
msgid "Could not install '%s'"
msgstr "Non foi posíbel instalar «%s»"

#: ../DistUpgrade/DistUpgradeViewGtk.py:214
#: ../DistUpgrade/DistUpgradeViewGtk3.py:218
#: ../DistUpgrade/DistUpgradeViewKDE.py:278
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""
"A anovación continuará mais o paquete «%s» podería estar instalado "
"incorrectamente. Considere o envío dun informe de erro sobre iso."

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:231
#: ../DistUpgrade/DistUpgradeViewGtk3.py:235
#: ../DistUpgrade/DistUpgradeViewKDE.py:299
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"Substituír o ficheiro de configuración personalizado\n"
"«%s»?"

#: ../DistUpgrade/DistUpgradeViewGtk.py:232
#: ../DistUpgrade/DistUpgradeViewGtk3.py:236
#: ../DistUpgrade/DistUpgradeViewKDE.py:300
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"Perderá as modificacións feitas neste ficheiro de configuración se escolle "
"substituílo por unha versión máis nova."

#: ../DistUpgrade/DistUpgradeViewGtk.py:251
#: ../DistUpgrade/DistUpgradeViewGtk3.py:256
#: ../DistUpgrade/DistUpgradeViewKDE.py:323
msgid "The 'diff' command was not found"
msgstr "Non se atopou a orde «diff»"

#: ../DistUpgrade/DistUpgradeViewGtk.py:464
#: ../DistUpgrade/DistUpgradeViewGtk3.py:477
#: ../DistUpgrade/DistUpgradeViewText.py:92
msgid "A fatal error occurred"
msgstr "Produciuse un erro fatal"

#: ../DistUpgrade/DistUpgradeViewGtk.py:465
#: ../DistUpgrade/DistUpgradeViewGtk3.py:478
msgid ""
"Please report this as a bug (if you haven't already) and include the files /"
"var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Informe deste fallo (se aínda non o fixo) e inclúa os ficheiros /var/log/"
"dist-upgrade/main.log e /var/log/dist-upgrade/apt.log no informe. A "
"actualización foi cancelada.\n"
"O seu ficheiro sources.list orixinal foi gardado en /etc/apt/sources.list."
"distUpgrade."

#: ../DistUpgrade/DistUpgradeViewGtk.py:482
#: ../DistUpgrade/DistUpgradeViewGtk3.py:495
msgid "Ctrl-c pressed"
msgstr "Ctrl+C premido"

#: ../DistUpgrade/DistUpgradeViewGtk.py:483
#: ../DistUpgrade/DistUpgradeViewGtk3.py:496
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"Isto interromperá a operación e podería deixar o sistema estragado. Seguro "
"que quere facelo?"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:631
#: ../DistUpgrade/DistUpgradeViewGtk3.py:629
msgid "To prevent data loss close all open applications and documents."
msgstr "Para previr a perda de datos peche todos os aplicativos e documentos."

#: ../DistUpgrade/DistUpgradeViewGtk.py:645
#: ../DistUpgrade/DistUpgradeViewGtk3.py:643
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr "Sen máis asistencia por parte de Canonical (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:646
#: ../DistUpgrade/DistUpgradeViewGtk3.py:644
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr "<b>Desactualizar (%s)</b>"

#: ../DistUpgrade/DistUpgradeViewGtk.py:647
#: ../DistUpgrade/DistUpgradeViewGtk3.py:645
#, python-format
msgid "Remove (%s)"
msgstr "Retirar (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:648
#: ../DistUpgrade/DistUpgradeViewGtk3.py:646
#, python-format
msgid "No longer needed (%s)"
msgstr "Non se necesita máis (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:649
#: ../DistUpgrade/DistUpgradeViewGtk3.py:647
#, python-format
msgid "Install (%s)"
msgstr "Instalar (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:650
#: ../DistUpgrade/DistUpgradeViewGtk3.py:648
#, python-format
msgid "Upgrade (%s)"
msgstr "Anovar (%s)"

#. change = QMessageBox.question(None, _("Media Change"), msg, QMessageBox.Ok, QMessageBox.Cancel)
#: ../DistUpgrade/DistUpgradeViewKDE.py:196
#: ../UpdateManager/DistUpgradeFetcherKDE.py:157
msgid "Media Change"
msgstr "Cambio de medio"

#: ../DistUpgrade/DistUpgradeViewKDE.py:335
msgid "Show Difference >>>"
msgstr "Mostrar a diferenza >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:338
msgid "<<< Hide Difference"
msgstr "<<< Agochar a diferenza"

#: ../DistUpgrade/DistUpgradeViewKDE.py:554
msgid "Error"
msgstr "Erro"

#: ../DistUpgrade/DistUpgradeViewKDE.py:568
msgid "&Cancel"
msgstr "&Cancelar"

#: ../DistUpgrade/DistUpgradeViewKDE.py:572
#: ../DistUpgrade/DistUpgradeViewKDE.py:813
msgid "&Close"
msgstr "&Pechar"

#: ../DistUpgrade/DistUpgradeViewKDE.py:618
msgid "Show Terminal >>>"
msgstr "Mostrar o terminal >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:621
msgid "<<< Hide Terminal"
msgstr "<<< Agochar o terminal"

#: ../DistUpgrade/DistUpgradeViewKDE.py:701
msgid "Information"
msgstr "Información"

#: ../DistUpgrade/DistUpgradeViewKDE.py:751
#: ../DistUpgrade/DistUpgradeViewKDE.py:796
#: ../DistUpgrade/DistUpgradeViewKDE.py:799 ../DistUpgrade/DistUpgrade.ui.h:7
msgid "Details"
msgstr "Detalles"

#: ../DistUpgrade/DistUpgradeViewKDE.py:777
#, python-format
msgid "No longer supported %s"
msgstr "Sen máis asistencia (%s)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:779
#, python-format
msgid "Remove %s"
msgstr "Retirar %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:781
#: ../DistUpgrade/DistUpgradeViewText.py:182
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "Retirar (instalado automaticamente) %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:783
#, python-format
msgid "Install %s"
msgstr "Instalar %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:785
#, python-format
msgid "Upgrade %s"
msgstr "Anovar %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:809
#: ../DistUpgrade/DistUpgradeViewText.py:230
msgid "Restart required"
msgstr "Cómpre reiniciar"

#: ../DistUpgrade/DistUpgradeViewKDE.py:809
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr "<b><big>Reinicie o sistema para completar a anovación</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:812 ../DistUpgrade/DistUpgrade.ui.h:14
#: ../data/gtkbuilder/UpdateManager.ui.h:26
msgid "_Restart Now"
msgstr "_Reiniciar agora"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:830
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>Anular a anovación en curso?</big></b>\n"
"\n"
"O sistema podería quedar inutilizado se anula a anovación. Recomendámoslle "
"encarecidamente que continúe a anovación."

#: ../DistUpgrade/DistUpgradeViewKDE.py:834
msgid "Cancel Upgrade?"
msgstr "Anular a anovación?"

#: ../DistUpgrade/DistUpgradeView.py:61
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li día"
msgstr[1] "%li días"

#: ../DistUpgrade/DistUpgradeView.py:63
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li hora"
msgstr[1] "%li horas"

#: ../DistUpgrade/DistUpgradeView.py:65
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li minuto"
msgstr[1] "%li minutos"

#: ../DistUpgrade/DistUpgradeView.py:66
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li segundo"
msgstr[1] "%li segundos"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:82
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:100
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:151
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""
"Esta descarga durará arredor de  %s nunha conexión DSL a 1Mbit e sobre  %s "
"nunha conexión de módem a  56k."

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:155
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "Esta descarga levará aproximadamente %s coa súa conexión. "

#. Declare these translatable strings from the .ui files here so that
#. xgettext picks them up.
#: ../DistUpgrade/DistUpgradeView.py:259 ../DistUpgrade/DistUpgrade.ui.h:21
msgid "Preparing to upgrade"
msgstr "Preparando a anovación"

#: ../DistUpgrade/DistUpgradeView.py:260
msgid "Getting new software channels"
msgstr "Obtendo as canles de software novas"

#: ../DistUpgrade/DistUpgradeView.py:261 ../DistUpgrade/DistUpgrade.ui.h:23
msgid "Getting new packages"
msgstr "Obtendo os paquetes novos"

#: ../DistUpgrade/DistUpgradeView.py:262 ../DistUpgrade/DistUpgrade.ui.h:26
msgid "Installing the upgrades"
msgstr "Instalando as anovacións"

#: ../DistUpgrade/DistUpgradeView.py:263 ../DistUpgrade/DistUpgrade.ui.h:25
msgid "Cleaning up"
msgstr "Limpando"

#: ../DistUpgrade/DistUpgradeView.py:348
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
"%(amount)d paquete instalado non seguirá tendo asistencia de Canonical. "
"Aínda así, pode obter asistencia desde a comunidade."
msgstr[1] ""
"%(amount)d paquetes instalados non seguirán tendo asistencia de Canonical. "
"Aínda así, pode obter asistencia desde a comunidade."

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:357
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "Retirarase %d paquete."
msgstr[1] "Retiraranse %d paquetes."

#: ../DistUpgrade/DistUpgradeView.py:362
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "Instalarase %d paquete novo."
msgstr[1] "Instalaranse %d paquetes novos."

#: ../DistUpgrade/DistUpgradeView.py:368
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "Anovarase %d paquete."
msgstr[1] "Anovaranse %d paquetes."

#: ../DistUpgrade/DistUpgradeView.py:373
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"Ten que descargar un total de %s. "

#: ../DistUpgrade/DistUpgradeView.py:378
msgid ""
"Installing the upgrade can take several hours. Once the download has "
"finished, the process cannot be canceled."
msgstr ""
"A instalación da anovación pode levar varias horas. En canto remate a "
"descarga, o proceso non se pode cancelar."

#: ../DistUpgrade/DistUpgradeView.py:382
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be canceled."
msgstr ""
"Obter e instalar a anovación pode levar varias horas. En canto remate a "
"descarga, o proceso non se pode cancelar."

#: ../DistUpgrade/DistUpgradeView.py:387
msgid "Removing the packages can take several hours. "
msgstr "A eliminación dos paquetes pode levar varias horas. "

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:392 ../UpdateManager/UpdateManager.py:676
msgid "The software on this computer is up to date."
msgstr "O software deste computador está actualizado."

#: ../DistUpgrade/DistUpgradeView.py:393
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"Non hai anovacións dispoñíbeis para o seu sistema. Anularase a anovación."

#: ../DistUpgrade/DistUpgradeView.py:406
msgid "Reboot required"
msgstr "Cómpre reiniciar"

#: ../DistUpgrade/DistUpgradeView.py:407
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr "A anovación finalizou e cómpre reiniciar. Quere facelo agora?"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:72
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:72
#, python-format
msgid "authenticate '%(file)s' against '%(signature)s' "
msgstr "autenticar «%(file)s» contra «%(signature)s» "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:131
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:131
#, python-format
msgid "extracting '%s'"
msgstr "a extraer «%s»"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:151
#: ../DistUpgrade/DistUpgradeFetcherCore.py:152
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:151
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:152
msgid "Could not run the upgrade tool"
msgstr "Non foi posíbel executar a ferramenta de anovación"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:152
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:152
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug "
"using the command 'ubuntu-bug update-manager'."
msgstr ""
"Isto pode ser un erro na ferramenta de actualización Informe de este erro "
"usando a orde «ubuntu-bug update-manager» desde o seu terminal."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:227
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:227
msgid "Upgrade tool signature"
msgstr "Sinatura da ferramenta de anovación"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:234
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:234
msgid "Upgrade tool"
msgstr "Ferramenta de anovación"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:268
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:268
msgid "Failed to fetch"
msgstr "Erro ao obter"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:269
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:269
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr "Fallou a obtención da anovación. Pode haber un problema coa rede. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:273
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:273
msgid "Authentication failed"
msgstr "Fallou a autenticación"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:274
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:274
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"Fallou a autenticación da anovación. Pode haber un problema coa rede ou co "
"servidor. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:279
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:279
msgid "Failed to extract"
msgstr "Erro ao extraer"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:280
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:280
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"Fallou a extracción da anovación. Pode haber un problema coa rede ou co "
"servidor. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:285
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:285
msgid "Verification failed"
msgstr "Fallou a verificación"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:286
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:286
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"Fallou a verificación da anovación. Pode haber un problema coa rede ou co "
"servidor. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:300
#: ../DistUpgrade/DistUpgradeFetcherCore.py:306
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:300
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:306
msgid "Can not run the upgrade"
msgstr "Non foi posíbel executar a anovación"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:301
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:301
msgid ""
"This usually is caused by a system where /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"Isto a miúdo é causado por un sistema onde /tmp está montado como parámetro "
"«noexec». Remónte a partición sen o parámetro noexec antes de realizar a "
"anovación."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:307
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:307
#, python-format
msgid "The error message is '%s'."
msgstr "A mensaxe do erro é «%s»."

#: ../DistUpgrade/DistUpgradeViewText.py:93
msgid ""
"Please report this as a bug and include the files /var/log/dist-upgrade/main."
"log and /var/log/dist-upgrade/apt.log in your report. The upgrade has "
"aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Informe deste fallo e inclúa os ficheiros /var/log/dist-upgrade/main.log e /"
"var/log/dist-upgrade/apt.log no informe. A actualización foi cancelada.\n"
"O seu ficheiro sources.list orixinal gardouse en /etc/apt/sources.list."
"distUpgrade."

#: ../DistUpgrade/DistUpgradeViewText.py:117
msgid "Aborting"
msgstr "Interrompendo"

#: ../DistUpgrade/DistUpgradeViewText.py:122
msgid "Demoted:\n"
msgstr "Degradado:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:129
msgid "To continue please press [ENTER]"
msgstr "Para continuar prema [INTRO]"

#: ../DistUpgrade/DistUpgradeViewText.py:157
#: ../DistUpgrade/DistUpgradeViewText.py:196
#: ../DistUpgrade/DistUpgradeViewText.py:203
msgid "Continue [yN] "
msgstr "Continuar [sN] "

#: ../DistUpgrade/DistUpgradeViewText.py:157
#: ../DistUpgrade/DistUpgradeViewText.py:196
msgid "Details [d]"
msgstr "Detalles [d]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:162
#: ../DistUpgrade/DistUpgradeViewText.py:206
msgid "y"
msgstr "s"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:165
#: ../DistUpgrade/DistUpgradeViewText.py:213
msgid "n"
msgstr "n"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:168
msgid "d"
msgstr "d"

#: ../DistUpgrade/DistUpgradeViewText.py:173
#, python-format
msgid "No longer supported: %s\n"
msgstr "Sen máis asistencia: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:178
#, python-format
msgid "Remove: %s\n"
msgstr "Retirar: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:188
#, python-format
msgid "Install: %s\n"
msgstr "Instalar: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:193
#, python-format
msgid "Upgrade: %s\n"
msgstr "Anovar: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:210
msgid "Continue [Yn] "
msgstr "Continuar [Sn] "

#: ../DistUpgrade/DistUpgradeViewText.py:231
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"Para concluír a anovación compre reiniciar.\n"
"Se selecciona «s» o sistema reiniciarase."

#: ../DistUpgrade/DistUpgrade.ui.h:1
msgid "_Cancel Upgrade"
msgstr "_Anular a anovación"

#: ../DistUpgrade/DistUpgrade.ui.h:2
msgid "_Resume Upgrade"
msgstr "_Continuar a anovación"

#: ../DistUpgrade/DistUpgrade.ui.h:3
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>Cancelar a anovación en curso?</big></b>\n"
"\n"
"O sistema podería quedar nun estado non usábel se anula a anovación. "
"Recomendámoslle encarecidamente que continúe a anovación."

#: ../DistUpgrade/DistUpgrade.ui.h:6
msgid "_Start Upgrade"
msgstr "_Iniciar a anovación"

#: ../DistUpgrade/DistUpgrade.ui.h:9
msgid "_Replace"
msgstr "_Substituír"

#: ../DistUpgrade/DistUpgrade.ui.h:10
msgid "Difference between the files"
msgstr "Diferenza entre os ficheiros"

#: ../DistUpgrade/DistUpgrade.ui.h:11
msgid "_Report Bug"
msgstr "_Informar dun fallo"

#: ../DistUpgrade/DistUpgrade.ui.h:12
msgid "_Continue"
msgstr "_Continuar"

#: ../DistUpgrade/DistUpgrade.ui.h:13
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>Comezar a anovación?</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:15
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>Reinicie o sistema para completar a anovación</big></b>\n"
"\n"
"Garde o seu traballo antes de continuar."

#: ../DistUpgrade/DistUpgrade.ui.h:18
msgid "Distribution Upgrade"
msgstr "Anovación da distribución"

#: ../DistUpgrade/DistUpgrade.ui.h:19
#, fuzzy
msgid "<b><big>Upgrading Ubuntu to version 12.10</big></b>"
msgstr "<b><big>Anovando Ubuntu á versión 11.10</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:20
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.ui.h:22
msgid "Setting new software channels"
msgstr "Estabelecendo novas canles de software"

#: ../DistUpgrade/DistUpgrade.ui.h:24
msgid "Restarting the computer"
msgstr "Reiniciando o computador"

#: ../DistUpgrade/DistUpgrade.ui.h:27
msgid "Terminal"
msgstr "Terminal"

#: ../UpdateManager/backend/InstallBackendSynaptic.py:64
msgid "Please wait, this can take some time."
msgstr "Agarde, por favor; isto pode tardar un pouco."

#: ../UpdateManager/backend/InstallBackendSynaptic.py:66
msgid "Update is complete"
msgstr "Completouse a actualización"

#: ../UpdateManager/DistUpgradeFetcher.py:114
#: ../UpdateManager/DistUpgradeFetcherKDE.py:109
msgid "Could not find the release notes"
msgstr "Non foi posíbel atopar as notas da versión"

#: ../UpdateManager/DistUpgradeFetcher.py:115
#: ../UpdateManager/DistUpgradeFetcherKDE.py:110
msgid "The server may be overloaded. "
msgstr "Poida que o servidor estea sobrecargado. "

#: ../UpdateManager/DistUpgradeFetcher.py:125
#: ../UpdateManager/DistUpgradeFetcherKDE.py:114
msgid "Could not download the release notes"
msgstr "Non foi posíbel descargar as notas da versión"

#: ../UpdateManager/DistUpgradeFetcher.py:126
#: ../UpdateManager/DistUpgradeFetcherKDE.py:115
msgid "Please check your internet connection."
msgstr "Por favor, comprobe a conexión á Internet."

#: ../UpdateManager/DistUpgradeFetcherKDE.py:68
#: ../UpdateManager/DistUpgradeFetcherKDE.py:91
msgid "Upgrade"
msgstr "Anovar"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:95
#: ../data/gtkbuilder/UpdateManager.ui.h:20
#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:2
msgid "Release Notes"
msgstr "Notas da versión"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:134
#: ../UpdateManager/DistUpgradeFetcherKDE.py:148
#: ../UpdateManager/DistUpgradeFetcherKDE.py:150
msgid "Downloading additional package files..."
msgstr "Descargando os ficheiros de paquetes adicionais..."

#: ../UpdateManager/DistUpgradeFetcherKDE.py:148
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "Ficheiro %s de %s a %sB/s"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:150
#, python-format
msgid "File %s of %s"
msgstr "Ficheiro %s de %s"

#: ../UpdateManager/ChangelogViewer.py:75
msgid "Open Link in Browser"
msgstr "Abrir a ligazón no navegador"

#: ../UpdateManager/ChangelogViewer.py:78
msgid "Copy Link to Clipboard"
msgstr "Copiar a ligazón no portapapeis"

#: ../UpdateManager/GtkProgress.py:162
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "Descargando o ficheiro %(current)li de %(total)li a %(speed)s/s"

#: ../UpdateManager/GtkProgress.py:167
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "Descargando o ficheiro %(current)li de %(total)li"

#: ../UpdateManager/UpdateManager.py:106 ../do-release-upgrade:100
msgid "Your Ubuntu release is not supported anymore."
msgstr "A súa versión de Ubuntu xa non está asistida."

#: ../UpdateManager/UpdateManager.py:107
msgid ""
"You will not get any further security fixes or critical updates. Please "
"upgrade to a later version of Ubuntu."
msgstr ""
"Non recibirá máis arranxos de problemas de seguranza ou actualizacións "
"críticas. Actualice a unha versión posterior de Ubuntu."

#: ../UpdateManager/UpdateManager.py:115
msgid "Upgrade information"
msgstr "Información sobre a anovación"

#: ../UpdateManager/UpdateManager.py:233
#: ../UpdateManagerText/UpdateManagerText.py:35
msgid "Install"
msgstr "Instalar"

#: ../UpdateManager/UpdateManager.py:235
msgid "Name"
msgstr "Nome"

#. upload_archive = version_match.group(2).strip()
#: ../UpdateManager/UpdateManager.py:395
#, python-format
msgid "Version %s: \n"
msgstr "Versión %s: \n"

#: ../UpdateManager/UpdateManager.py:453
msgid ""
"No network connection detected, you can not download changelog information."
msgstr ""
"Non se detectou ningunha conexión de rede, non pode descargar a información "
"do rexistro de cambios."

#: ../UpdateManager/UpdateManager.py:463
msgid "Downloading list of changes..."
msgstr "Descargando a lista de cambios..."

#: ../UpdateManager/UpdateManager.py:507
msgid "_Deselect All"
msgstr "_Deseleccionar todo"

#: ../UpdateManager/UpdateManager.py:513
msgid "Select _All"
msgstr "Seleccionar _todo"

#: ../UpdateManager/UpdateManager.py:572
#, python-format
msgid "%s will be downloaded."
msgstr "Vanse descargar %s."

#: ../UpdateManager/UpdateManager.py:584
#, fuzzy
msgid "The update has already been downloaded."
msgid_plural "The updates have already been downloaded."
msgstr[0] "Xa se descargou a actualización, mais non se instalou."
msgstr[1] "Xa se descargaron as actualizacións, mais non se instalaron."

#: ../UpdateManager/UpdateManager.py:589
msgid "There are no updates to install."
msgstr "Non hai actualizacións que instalar."

#: ../UpdateManager/UpdateManager.py:598
msgid "Unknown download size."
msgstr "Tamaño da descarga descoñecida."

#: ../UpdateManager/UpdateManager.py:624
msgid ""
"It is unknown when the package information was updated last. Please click "
"the 'Check' button to update the information."
msgstr ""
"Non se sabe cando se actualizou a última vez esta información. Prema no "
"botón «Comprobar» para actualizar a información."

#: ../UpdateManager/UpdateManager.py:630
#, python-format
msgid ""
"The package information was last updated %(days_ago)s days ago.\n"
"Press the 'Check' button below to check for new software updates."
msgstr ""
"A información sobre os paquetes foi actualizada por ultima vez hai "
"%(days_ago)s días.\n"
"Prema o botón «Comprobar» de embaixo para consultar se hai novas "
"actualizacións de software."

#: ../UpdateManager/UpdateManager.py:635
#, python-format
msgid "The package information was last updated %(days_ago)s day ago."
msgid_plural "The package information was last updated %(days_ago)s days ago."
msgstr[0] ""
"A información sobre os paquetes foi actualizada hai %(days_ago)s día."
msgstr[1] "A información dos paquetes foi actualizada hai %(days_ago)s días."

#: ../UpdateManager/UpdateManager.py:639
#, python-format
msgid "The package information was last updated %(hours_ago)s hour ago."
msgid_plural ""
"The package information was last updated %(hours_ago)s hours ago."
msgstr[0] ""
"A información sobre os paquetes actualizouse por última vez hai "
"%(hours_ago)s hora."
msgstr[1] ""
"A información dos paquetes actualizouse por última vez hai %(hours_ago)s "
"horas."

#. TRANSLATORS: only in plural form, as %s minutes ago is one of 15, 30, 45 minutes ago
#: ../UpdateManager/UpdateManager.py:644 ../UpdateManager/UpdateManager.py:646
#: ../UpdateManager/UpdateManager.py:648
#, python-format
msgid "The package information was last updated about %s minutes ago."
msgstr "A información dos paquetes foi actualizada hai %s minutos."

#: ../UpdateManager/UpdateManager.py:650
msgid "The package information was just updated."
msgstr "A información sobre os paquetes foi actualizada hai un intre."

#: ../UpdateManager/UpdateManager.py:689
msgid "Software updates may be available for your computer."
msgstr "É posíbel que haxa actualizacións dispoñíbeis para o seu computador."

#: ../UpdateManager/UpdateManager.py:697
#, python-format
msgid ""
"Updated software has been issued since %s was released. Do you want to "
"install it now?"
msgstr ""

#: ../UpdateManager/UpdateManager.py:700
msgid ""
"Updated software is available for this computer. Do you want to install it "
"now?"
msgstr ""

#: ../UpdateManager/UpdateManager.py:758
#, python-format
msgid ""
"The upgrade needs a total of %s free space on disk '%s'. Please free at "
"least an additional %s of disk space on '%s'. Empty your trash and remove "
"temporary packages of former installations using 'sudo apt-get clean'."
msgstr ""
"A anovación necesita un total de %s de espazo libre no disco «%s». Libere "
"polo menos %s de espazo adicional de disco en «%s». Baleire o lixo e retire "
"paquetes temporais de instalacións anteriores utilizando «sudo apt-get "
"clean»."

#: ../UpdateManager/UpdateManager.py:783
msgid ""
"The computer needs to restart to finish installing updates. Please save your "
"work before continuing."
msgstr ""
"O computador precisa reiniciarse para rematar a instalación das "
"actualizacións. Garde o seu traballo antes de continuar."

#: ../UpdateManager/UpdateManager.py:847
msgid "Reading package information"
msgstr "Lendo a información do paquete"

#: ../UpdateManager/UpdateManager.py:862
msgid "Connecting..."
msgstr "Conectando…"

#: ../UpdateManager/UpdateManager.py:879
msgid "You may not be able to check for updates or download new updates."
msgstr ""
"Vostede non pode comprobar as actualizacións ou descargar novas "
"actualizacións."

#: ../UpdateManager/UpdateManager.py:1002
msgid "Could not initialize the package information"
msgstr "Non foi posíbel inicializar a información do paquete"

#: ../UpdateManager/UpdateManager.py:1003
msgid ""
"An unresolvable problem occurred while initializing the package "
"information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""
"Produciuse un erro irresolúbel ao inicializar a información do paquete.\n"
"\n"
"Por favor, informe deste erro do paquete «update-manager» e inclúa a "
"seguinte mensaxe de erro:\n"

#: ../UpdateManager/UpdateManager.py:1032
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr ""
"Produciuse un erro irresolúbel ao calcular a anovación.\n"
"\n"
"Por favor, informe deste erro do paquete «update-manager» e inclúa a "
"seguinte mensaxe de erro:"

#: ../UpdateManager/UpdateManager.py:1056
msgid " (New install)"
msgstr " (Instalación nova)"

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:1063
#, python-format
msgid "(Size: %s)"
msgstr "(Tamaño: %s)"

#: ../UpdateManager/UpdateManager.py:1067
#, python-format
msgid "From version %(old_version)s to %(new_version)s"
msgstr "Desde a versión %(old_version)s á %(new_version)s"

#: ../UpdateManager/UpdateManager.py:1071
#, python-format
msgid "Version %s"
msgstr "Versión %s"

#: ../UpdateManager/UpdateManager.py:1104 ../do-release-upgrade:112
msgid "Release upgrade not possible right now"
msgstr "Non é posíbel actualizar a versión neste momento"

#: ../UpdateManager/UpdateManager.py:1105 ../do-release-upgrade:113
#, c-format, python-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr ""
"Non é posíbel realizar a actualización de versión neste momento, probe de "
"novo máis tarde. O servidor informou: «%s»"

#: ../UpdateManager/UpdateManager.py:1107 ../check-new-release-gtk:126
msgid "Downloading the release upgrade tool"
msgstr "Descargando a ferramenta de anovación"

#: ../UpdateManager/UpdateManager.py:1114
#, python-format
msgid "<b>New Ubuntu release '%s' is available</b>"
msgstr "<b>Existe unha nova versión de Ubuntu «%s» dispoñíbel</b>"

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:1153
msgid "Software index is broken"
msgstr "O índice de software está roto"

#: ../UpdateManager/UpdateManager.py:1154
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""
"Non é posíbel instalar ou desinstalar ningún programa. Por favor, utilice o "
"xestor de paquetes «Synaptic» ou execute «sudo apt-get install -f» nun "
"terminal para corrixir este problema primeiro."

#: ../UpdateManager/UnitySupport.py:57
msgid "Check for Updates"
msgstr "Comprobar actualizacións"

#: ../UpdateManager/UnitySupport.py:66
msgid "Install All Available Updates"
msgstr "Instalar tódalas actualizacións dispoñíbeis"

#: ../UpdateManagerText/UpdateManagerText.py:34
msgid "Cancel"
msgstr "Cancelar"

#: ../UpdateManagerText/UpdateManagerText.py:37
msgid "Changelog"
msgstr "Rexistro de cambios"

#: ../UpdateManagerText/UpdateManagerText.py:40
msgid "Updates"
msgstr "Actualizacións"

#: ../UpdateManagerText/UpdateManagerText.py:53
msgid "Building Updates List"
msgstr "Construíndo a lista de actualizacións"

#: ../UpdateManagerText/UpdateManagerText.py:56
msgid ""
"\n"
"A normal upgrade can not be calculated, please run: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""
"\n"
"Non é posíbel calcular unha anovación normal; execute:\n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"Isto pode ser causado por:\n"
" * Unha anovación previa que non se completou\n"
" * Problemas con algún software instalado\n"
" * Paquetes de software non oficiais non fornecidos por Ubuntu\n"
" * Alteracións normais dunha versión de prelanzamento de Ubuntu"

#: ../UpdateManagerText/UpdateManagerText.py:125
msgid "Downloading changelog"
msgstr "Descargando o informe de cambios"

#: ../UpdateManager/Core/MyCache.py:147
#, python-format
msgid "Other updates (%s)"
msgstr "Outras actualizacións (%s)"

#: ../UpdateManager/Core/MyCache.py:325
msgid "This update does not come from a source that supports changelogs."
msgstr ""
"Esta actualización non pertence a unha orixe que admite ficheiros  de "
"cambios (changelog)."

#: ../UpdateManager/Core/MyCache.py:331 ../UpdateManager/Core/MyCache.py:359
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""
"Non foi posíbel descargar a lista de cambios.\n"
"Comprobe a súa conexión á Internet."

#: ../UpdateManager/Core/MyCache.py:338
#, python-format
msgid ""
"Changes for the versions:\n"
"Installed version: %s\n"
"Available version: %s\n"
"\n"
msgstr ""
"Cambios para estas versións:\n"
"Versión instalada: %s\n"
"Versión dispoñíbel: %s\n"
"\n"

#: ../UpdateManager/Core/MyCache.py:348
#, python-format
msgid ""
"The changelog does not contain any relevant changes.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"O informe de cambios non contén ningún cambio relevante.\n"
"\n"
"\n"
"Utilice http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"ata que os cambios estean dispoñíbeis ou probe máis tarde."

#: ../UpdateManager/Core/MyCache.py:353
#, python-format
msgid ""
"The list of changes is not available yet.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"A lista de cambios aínda non está dispoñíbel.\n"
"\n"
"Por favor, utilice http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"ata que os cambios estean dispoñíbeis ou probe máis tarde."

#: ../UpdateManager/Core/UpdateList.py:51
msgid "Failed to detect distribution"
msgstr "Non foi posíbel detectar a distribución"

#: ../UpdateManager/Core/UpdateList.py:52
#, python-format
msgid "A error '%s' occurred while checking what system you are using."
msgstr "Produciuse un erro «%s» ao comprobar o que está a usar o seu sistema."

#: ../UpdateManager/Core/UpdateList.py:63
msgid "Important security updates"
msgstr "Actualizacións de seguranza importantes"

#: ../UpdateManager/Core/UpdateList.py:64
msgid "Recommended updates"
msgstr "Actualizacións recomendadas"

#: ../UpdateManager/Core/UpdateList.py:65
msgid "Proposed updates"
msgstr "Actualizacións aconselladas"

#: ../UpdateManager/Core/UpdateList.py:66
msgid "Backports"
msgstr "Adaptacións regresivas (backports)"

#: ../UpdateManager/Core/UpdateList.py:67
msgid "Distribution updates"
msgstr "Actualizacións da distribución"

#: ../UpdateManager/Core/UpdateList.py:72
msgid "Other updates"
msgstr "Outras actualizacións"

#: ../data/gtkbuilder/UpdateManager.ui.h:1
#, fuzzy
msgid "<big><b>Starting Software Updater</b></big>"
msgstr "<big><b>Iniciando o Xestor de actualizacións</b></big>"

#: ../data/gtkbuilder/UpdateManager.ui.h:2
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr ""
"As actualizacións de software corrixen erros, eliminan fallos de seguranza e "
"fornecen funcionalidades novas."

#: ../data/gtkbuilder/UpdateManager.ui.h:3
msgid "_Partial Upgrade"
msgstr "Anovación _Parcial"

#: ../data/gtkbuilder/UpdateManager.ui.h:4
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr "<big><b>Non se poden instalar todas as actualizacións</b></big>"

#: ../data/gtkbuilder/UpdateManager.ui.h:5
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""
"Executar unha anovación parcial para instalar cantas actualizacións sexan "
"posíbeis. \n"
"\n"
"Isto pódese deber a:\n"
" * Unha anovación anterior da versión que non rematou\n"
" * Problemas con algún software instalado\n"
" * Paquetes de software non oficiais non fornecidos por Ubuntu\n"
" * Alteracións normais dunha versión de prelanzamento de Ubuntu"

#: ../data/gtkbuilder/UpdateManager.ui.h:12
msgid "Chec_k"
msgstr "Compro_bar"

#: ../data/gtkbuilder/UpdateManager.ui.h:13
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Updates</i> tab."
msgstr ""
"<b><big>Ten que comprobar as actualizacións manualmente</big></b>\n"
"\n"
"O seu sistema non comproba as actualizacións automaticamente. Pode "
"configurar este comportamento en <i>Fontes de software</i> na lapela "
"<i>Actualizacións</i>."

#: ../data/gtkbuilder/UpdateManager.ui.h:16
msgid "_Hide this information in the future"
msgstr "_Agochar esta información no futuro"

#: ../data/gtkbuilder/UpdateManager.ui.h:17
msgid "Co_ntinue"
msgstr "Con_tinuar"

#: ../data/gtkbuilder/UpdateManager.ui.h:18
msgid "<big><b>Running on battery</b></big>"
msgstr "<big><b>Executando con batería</b></big>"

#: ../data/gtkbuilder/UpdateManager.ui.h:19
msgid "Your system is running on battery. Are you sure you want to continue?"
msgstr "Estase esgotando a batería. Está seguro de que quere continuar?"

#: ../data/gtkbuilder/UpdateManager.ui.h:21
msgid "_Upgrade"
msgstr "A_novar"

#: ../data/gtkbuilder/UpdateManager.ui.h:22
#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:8
msgid "Show progress of individual files"
msgstr "Mostrar o progreso de cada ficheiro individual"

#: ../data/gtkbuilder/UpdateManager.ui.h:23
#: ../data/update-manager.desktop.in.h:1
#, fuzzy
msgid "Software Updater"
msgstr "Actualizacións de software"

#: ../data/gtkbuilder/UpdateManager.ui.h:24
#, fuzzy
msgid "Starting Software Updater"
msgstr "Actualizacións de software"

#: ../data/gtkbuilder/UpdateManager.ui.h:25
msgid "U_pgrade"
msgstr "A_novar"

#: ../data/gtkbuilder/UpdateManager.ui.h:27
msgid "updates"
msgstr "actualizacións"

#: ../data/gtkbuilder/UpdateManager.ui.h:28
msgid "Changes"
msgstr "Cambios"

#: ../data/gtkbuilder/UpdateManager.ui.h:29
msgid "Description"
msgstr "Descrición"

#: ../data/gtkbuilder/UpdateManager.ui.h:30
#, fuzzy
msgid "Details of updates"
msgstr "Descrición da actualización"

#: ../data/gtkbuilder/UpdateManager.ui.h:31
msgid ""
"You are connected via roaming and may be charged for the data consumed by "
"this update."
msgstr ""
"Agora está conectado en itinerancia e poden producirse cargos polos datos "
"consumidos nesta actualización."

#: ../data/gtkbuilder/UpdateManager.ui.h:32
msgid ""
"You may want to wait until you’re not using a mobile broadband connection."
msgstr ""

#: ../data/gtkbuilder/UpdateManager.ui.h:33
msgid "It’s safer to connect the computer to AC power before updating."
msgstr "Por seguridade, conecte o equipo á toma eléctrica antes de actualizar."

#: ../data/gtkbuilder/UpdateManager.ui.h:34
msgid "_Settings..."
msgstr "_Opcións..."

#: ../data/gtkbuilder/UpdateManager.ui.h:35
#, fuzzy
msgid "_Install Now"
msgstr "Instalar"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:1
msgid "<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr "<b>Existe unha nova versión de Ubuntu dispoñíbel. Desexa anovar?</b>"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:3
msgid "Don't Upgrade"
msgstr "Non anovar"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:4
msgid "Ask Me Later"
msgstr "Preguntarme máis tarde"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:5
msgid "Yes, Upgrade Now"
msgstr "Si, anovar agora"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:6
msgid "You have declined to upgrade to the new Ubuntu"
msgstr "Vostede rexeitou a anovación ao novo Ubuntu"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:7
#, fuzzy
msgid ""
"You can upgrade at a later time by opening Software Updater and click on "
"\"Upgrade\"."
msgstr ""
"Pode anovar máis tarde abrindo o Xestor de actualizacións e premendo "
"«Anovar»."

#: ../data/update-manager.desktop.in.h:2
msgid "Software Updates"
msgstr "Actualizacións de software"

#: ../data/update-manager.desktop.in.h:3
msgid "Show and install available updates"
msgstr "Mostrar e instalar as actualizacións dispoñíbeis"

#: ../update-manager:66 ../update-manager-text:55 ../do-release-upgrade:51
msgid "Show version and exit"
msgstr "Mostrar a versión e saír"

#: ../update-manager:69
msgid "Directory that contains the data files"
msgstr "Directorio que contén os ficheiros de datos"

#: ../update-manager:72
msgid "Check if a new Ubuntu release is available"
msgstr "Comprobar se hai unha nova versión de Ubuntu dispoñíbel"

#: ../update-manager:75 ../do-release-upgrade:54 ../check-new-release-gtk:186
msgid "Check if upgrading to the latest devel release is possible"
msgstr ""
"Comprobar se resulta posíbel anovar á versión en desenvolvemento máis recente"

#: ../update-manager:79
msgid "Upgrade using the latest proposed version of the release upgrader"
msgstr ""
"Anovación usando a última versión aconsellada polo anovador de versións."

#: ../update-manager:86
msgid "Do not focus on map when starting"
msgstr "Non enfocar o mapa ao comezar"

#: ../update-manager:89
msgid "Try to run a dist-upgrade"
msgstr "Tente executar dist-upgrade"

#: ../update-manager:92
msgid "Do not check for updates when starting"
msgstr "Non comprobar no inicio se hai actualizacións"

#: ../update-manager:96 ../do-release-upgrade:70
msgid "Test upgrade with a sandbox aufs overlay"
msgstr "O test de anovación con área de probas aufs devolve superposición"

#: ../update-manager:116
msgid "Running partial upgrade"
msgstr "Executando unha anovación parcial"

#: ../update-manager-text:59
msgid "Show description of the package instead of the changelog"
msgstr "Mostrar a descrición do paquete no canto do rexistro de cambios"

#: ../do-release-upgrade:58 ../check-new-release-gtk:190
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""
"Tente anovarse á última versión usando o anovador desde $distro-proposed"

#: ../do-release-upgrade:62
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"Executar nun modo de anovación especial.\n"
"Actualmente existen «desktop» para actualizacións normais dun sistema de "
"escritorio e «server» para sistemas servidores."

#: ../do-release-upgrade:68
msgid "Run the specified frontend"
msgstr "Execute a interface gráfica indicada"

#: ../do-release-upgrade:73
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""
"Comprobar só se está dispoñíbel unha nova versión da distribución e informar "
"do resultado mediante o código de saída."

#: ../do-release-upgrade:87
msgid "Checking for a new Ubuntu release"
msgstr "Buscando novas publicacións de Ubuntu"

#: ../do-release-upgrade:101
msgid ""
"For upgrade information, please visit:\n"
"%(url)s\n"
msgstr ""
"Para obter máis información sobre esta anovación, visite:\n"
"%(url)s\n"

#: ../do-release-upgrade:107
msgid "No new release found"
msgstr "Non se atopou unha versión nova"

#: ../do-release-upgrade:119
#, c-format
msgid "New release '%s' available."
msgstr "Unha versión nova «%s» dispoñíbel"

#: ../do-release-upgrade:120
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "Execute «do-release-upgrade» para anovarse."

#: ../check-new-release-gtk:101
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "Está dispoñíbel unha anovación á %(version)s de Ubuntu"

#: ../check-new-release-gtk:143
#, c-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr "Vostede rexeitou a anovación a Ubuntu %s"

#: ../check-new-release-gtk:196
msgid "Add debug output"
msgstr "Engadir a saída de depuración"

#: ../ubuntu-support-status:91
msgid "Show unsupported packages on this machine"
msgstr "Mostrar os paquetes non compatíbeis con este equipo"

#: ../ubuntu-support-status:94
msgid "Show supported packages on this machine"
msgstr "Mostrar os paquetes non compatíbeis con esta máquina"

#: ../ubuntu-support-status:97
msgid "Show all packages with their status"
msgstr "Mostrar todos os paquetes co seu estado"

#: ../ubuntu-support-status:100
msgid "Show all packages in a list"
msgstr "Mostrar todos os paquetes nunha lista"

#: ../ubuntu-support-status:142
#, c-format
msgid "Support status summary of '%s':"
msgstr "Resumo do estado de compatibilidade de «%s»:"

#: ../ubuntu-support-status:145
msgid "You have %(num)s packages (%(percent).1f%%) supported until %(time)s"
msgstr ""
"Ten %(num)s paquetes (%(percent).1f%%) con asistencia técnica até %(time)s"

#: ../ubuntu-support-status:151
msgid ""
"You have %(num)s packages (%(percent).1f%%) that can not/no-longer be "
"downloaded"
msgstr "Ten %(num)s paquetes (%(percent).1f%%) que non poden descargarse máis"

#: ../ubuntu-support-status:154
msgid "You have %(num)s packages (%(percent).1f%%) that are unsupported"
msgstr "Ten %(num)s paquetes (%(percent).1f%%) que non teñen asistencia"

#: ../ubuntu-support-status:162
msgid ""
"Run with --show-unsupported, --show-supported or --show-all to see more "
"details"
msgstr ""
"Execute con --show-unsupported, --show-supported ou --show-all para ver máis "
"información"

#: ../ubuntu-support-status:166
msgid "No longer downloadable:"
msgstr "Xa non se poden descargar:"

#: ../ubuntu-support-status:169
msgid "Unsupported: "
msgstr "Sen asistencia: "

#: ../ubuntu-support-status:174
#, c-format
msgid "Supported until %s:"
msgstr "Con asistencia até %s:"

#: ../ubuntu-support-status:183
msgid "Unsupported"
msgstr "Sen asistencia"

#. Why do we use %s here instead of $strings or {} format placeholders?
#. It's because we don't want to break existing translations.
#: ../janitor/plugincore/exceptions.py:42
#, python-format
msgid "Unimplemented method: %s"
msgstr "Método non implementado: %s"

#: ../janitor/plugincore/core/file_cruft.py:41
msgid "A file on disk"
msgstr "Un ficheiro nun disco"

#: ../janitor/plugincore/core/missing_package_cruft.py:39
msgid "Install missing package."
msgstr "Instalar o paquete que falta."

#. 2012-06-08 BAW: i18n string; don't use {} or PEP 292.
#: ../janitor/plugincore/core/missing_package_cruft.py:49
#, python-format
msgid "Package %s should be installed."
msgstr "Habería que instalar o paquete %s."

#: ../janitor/plugincore/core/package_cruft.py:49
msgid ".deb package"
msgstr "paquete .deb"

#: ../janitor/plugincore/plugins/langpack_manual_plugin.py:46
#, python-format
msgid "%s needs to be marked as manually installed."
msgstr "Hai que marcar %s como instalado manualmente."

#: ../janitor/plugincore/plugins/kdelibs4to5_plugin.py:49
msgid ""
"When upgrading, if kdelibs4-dev is installed, kdelibs5-dev needs to be "
"installed. See bugs.launchpad.net, bug #279621 for details."
msgstr ""
"Ao anovar a versión, se kdelibs4-dev estiver instalado hai que instalar "
"kdelibs5-dev. Vexa o erro núm. 279621 de bugs.launchpad.net para máis "
"detalles."

#: ../janitor/plugincore/plugins/dpkg_status_plugin.py:44
#, python-format
msgid "%i obsolete entries in the status file"
msgstr "%i entradas obsoletas no ficheiro de status"

#: ../janitor/plugincore/plugins/dpkg_status_plugin.py:47
msgid "Obsolete entries in dpkg status"
msgstr "Entradas obsoletas no status de dpkg"

#. pragma: no cover
#: ../janitor/plugincore/plugins/dpkg_status_plugin.py:50
msgid "Obsolete dpkg status entries"
msgstr "Entradas obsoletas no status de dpkg"

#: ../janitor/plugincore/plugins/remove_lilo_plugin.py:42
msgid "Remove lilo since grub is also installed.(See bug #314004 for details.)"
msgstr ""
"Eliminar lilo, pois  grub tamén está instalado. (Ver o erro #314004 para "
"máis detalles)."

#~ msgid ""
#~ "After your package information was updated the essential package '%s' can "
#~ "not be found anymore so a bug reporting process is being started."
#~ msgstr ""
#~ "Despois de actualizar a información de paquetes, non é posíbel atopar o "
#~ "paquete esencial «%s» polo que estase iniciando un proceso de informe de "
#~ "erro."

#~ msgid "<b><big>Upgrading Ubuntu to version 12.04</big></b>"
#~ msgstr "<b><big>A actualizar Ubuntu á versión 12.04</big></b>"

#~ msgid "%(count)s update has been selected."
#~ msgid_plural "%(count)s updates have been selected."
#~ msgstr[0] "Seleccionouse %(count)s actualización."
#~ msgstr[1] "Seleccionáronse %(count)s actualizacións."

#~ msgid "%(count_str)s %(download_str)s"
#~ msgstr "%(count_str)s %(download_str)s"

#~ msgid "Welcome to Ubuntu"
#~ msgstr "Benvida/o a Ubuntu"

#~ msgid ""
#~ "These software updates have been issued since this version of Ubuntu was "
#~ "released."
#~ msgstr ""
#~ "Estas actualizacións de software foron publicadas despois de que o fose "
#~ "esta versión de Ubuntu."

#~ msgid "Software updates are available for this computer."
#~ msgstr ""
#~ "Existen actualizacións de software dispoñíbeis para este computador."

#~ msgid "Update Manager"
#~ msgstr "Xestor de actualizacións"

#~ msgid "Starting Update Manager"
#~ msgstr "Iniciando o Xestor de actualizacións"

#~ msgid "You are connected via a wireless modem."
#~ msgstr "Está conectado a través dun módem sen fíos."

#~ msgid "_Install Updates"
#~ msgstr "_Instalar as actualizacións"

#~ msgid "Your system is up-to-date"
#~ msgstr "O sistema está actualizado"

#~ msgid "Checking for a new ubuntu release"
#~ msgstr "Comprobando se existe unha nova versión da distribución"

#~ msgid "Software updates are available for this computer"
#~ msgstr "Actualizacións de software dispoñíbeis para este computador"

#~ msgid ""
#~ "If you don't want to install them now, choose \"Update Manager\" from the "
#~ "Administration menu later."
#~ msgstr ""
#~ "Se non as quere instalar agora, escolla «Xestor de actualizacións» máis "
#~ "tarde no menú Administración."

#~ msgid ""
#~ "This upgrade is running in sandbox (test) mode. All changes are written "
#~ "to '%s' and will be lost on the next reboot.\n"
#~ "\n"
#~ "*No* changes written to a systemdir from now until the next reboot are "
#~ "permanent."
#~ msgstr ""
#~ "Esta anovación está executandose en modo de probas (test). Todos os "
#~ "cambios escribense en  «%s» e perderanse no seguinte reinicio.\n"
#~ "\n"
#~ "*Ningún* cambio escrito desde agora no systemdir é permanente ata o "
#~ "seguinte reinicio."

#~ msgid ""
#~ "Fetching and installing the upgrade can take several hours. Once the "
#~ "download has finished, the process cannot be cancelled."
#~ msgstr ""
#~ "Descargar e instalar a anovación pode levar varias horas e unha vez "
#~ "rematada a descarga non se pode anular o proceso de instalación."

#~ msgid "There are no updates to install"
#~ msgstr "Non hai actualizacións para instalar"

#~ msgid "The update has already been downloaded, but not installed"
#~ msgid_plural "The updates have already been downloaded, but not installed"
#~ msgstr[0] "Xa se descargou a actualización, pero non se instalou."
#~ msgstr[1] "Xa se descargaron as actualizacións, pero non se instalaron."

#~ msgid ""
#~ "You will not get any further security fixes or critical updates. Please "
#~ "upgrade to a later version of Ubuntu Linux."
#~ msgstr ""
#~ "No obterá máis actualizacións de seguranza ou actualizacións críticas. "
#~ "Anove a unha versión máis recente de Ubuntu Linux."

#~ msgid ""
#~ "If you don't want to install them now, choose \"Update Manager\" from "
#~ "Applications later."
#~ msgstr ""
#~ "Se non desexa instalalas agora, seleccione máis tarde o «Xestor de "
#~ "actualizacións» no menú Aplicativos."

#~ msgid "0 kB"
#~ msgstr "0 kB"

#~ msgid "1 kB"
#~ msgstr "1 kB"

#~ msgid "%.0f kB"
#~ msgstr "%.0f kB"

#~ msgid "Your graphics hardware may not be fully supported in Ubuntu 11.04."
#~ msgstr "A súa tarxeta gráfica non é totalmente compatíbel con Ubuntu 11.04."

#~ msgid ""
#~ "The support in Ubuntu 11.04 for your intel graphics hardware is limited "
#~ "and you may encounter problems after the upgrade. Do you want to continue "
#~ "with the upgrade?"
#~ msgstr ""
#~ "A compatibilidade de Ubuntu 11.04 para as tarxetas gráficas de intel é "
#~ "limitada e pode encontrar erros logo da anovación. Ten certeza que quere "
#~ "realizar a anovación?"

#~ msgid ""
#~ "These software updates have been issued since this version of Ubuntu was "
#~ "released. If you don't want to install them now, choose \"Update Manager"
#~ "\" from Applications later."
#~ msgstr ""
#~ "Estas actualizacións de software foron enviadas desde que a última "
#~ "versión de Ubuntu fora publicada. Se non quere instalalas agora "
#~ "seleccione «Xestor de actualizacións» desde Aplicativos máis tarde."

#~ msgid ""
#~ "These software updates have been issued since this version of Ubuntu was "
#~ "released. If you don't want to install them now, choose \"Update Manager"
#~ "\" from the Administration Menu later."
#~ msgstr ""
#~ "Estas actualizacións de software foron enviadas desde que a última "
#~ "versión de Ubuntu fora publicada. Se non quere instalalas agora, "
#~ "seleccione «Xestor de actualizacións» desde o menú Administración máis "
#~ "tarde."

#~ msgid ""
#~ "The system was unable to get the prerequisites for the upgrade. The "
#~ "upgrade will abort now and restore the original system state.\n"
#~ "\n"
#~ "Please report this as a bug using the command 'ubuntu-bug update-manager' "
#~ "in a terminal and include the files in /var/log/dist-upgrade/ in the bug "
#~ "report."
#~ msgstr ""
#~ "O sistema non puido cumprir os prerequisitos da actualización polo que a "
#~ "actualización foi abortada e restaourouse o seu sistema ao estado "
#~ "orixinal.\n"
#~ "\n"
#~ "Informe de este erro usando a orde «ubuntu-bug update-manager» desde o "
#~ "seu terminal e inclúa os ficheiros de /var/log/dist-upgrade/ no informe "
#~ "de erro."

#~ msgid ""
#~ "After your package information was updated the essential package '%s' can "
#~ "not be found anymore.\n"
#~ "This indicates a serious error, please report this bug using the command "
#~ "'ubuntu-bug update-manager' in a terminal and include the files in /var/"
#~ "log/dist-upgrade/ in the bug report."
#~ msgstr ""
#~ "Despois de que se actualizara a información dos paquetes, non foi posíbel "
#~ "atopar o paquete esencial «%s» en ningures.\n"
#~ "Isto indica un erro importante, informe de este erro usando a orde "
#~ "«ubuntu-bug update-manager» desde o seu terminal e inclúa os ficheiros "
#~ "de /var/log/dist-upgrade/ no informe de erro."

#~ msgid ""
#~ "\n"
#~ "\n"
#~ "Please report this bug using the command 'ubuntu-bug update-manager' in a "
#~ "terminal and include the files in /var/log/dist-upgrade/ in the bug "
#~ "report.\n"
#~ "%s"
#~ msgstr ""
#~ "\n"
#~ "\n"
#~ "Informe de este erro usando a orde «ubuntu-bug update-manager» desde o "
#~ "seu terminal e inclúa os ficheiros de /var/log/dist-upgrade/ no informe "
#~ "de erro.\n"
#~ "%s"

#~ msgid ""
#~ "Preparing the system for the upgrade failed. Please report this using the "
#~ "command 'ubuntu-bug update-manager' in a terminal and include the files "
#~ "in /var/log/dist-upgrade/ in the bug report."
#~ msgstr ""
#~ "Fallou a preparación do seu sistema para a actualización. Informe de este "
#~ "erro usando a orde «ubuntu-bug update-manager» desde o seu terminal e "
#~ "inclúa os ficheiros de /var/log/dist-upgrade/ no informe de erro."

#~ msgid ""
#~ "Upgrading the repository information resulted in a invalid file. Please "
#~ "report this as a bug using the command 'ubuntu-bug update-manager' in a "
#~ "terminal."
#~ msgstr ""
#~ "Ao actualizar a información do repositorio obtívose un ficheiro non "
#~ "válido. Informe de este erro usando a orde «ubuntu-bug update-manager» "
#~ "desde o seu terminal."
